import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { runCommand } from "../process.js";
import type { WorkerConfig, WorkerRoot, WorkerWorkspace } from "./config.js";
import { cloneGitRepository, createGithubPullRequest, executeGitOperation, gitBranches, gitDiff as coreGitDiff, githubPullRequestPreview, gitLog, gitStatus as coreGitStatus, validateGitRemoteUrl } from "../git-core.js";
import { decodeEditableText, resolveWorkspaceTextPath, writeEditableTextFile } from "../workspace-file-edit.js";
import { formatByteLimit, MAX_WORKSPACE_DOWNLOAD_BYTES } from "../workspace-limits.js";

function inside(root:string,target:string){const relative=path.relative(root,target);return relative===""||(!relative.startsWith(`..${path.sep}`)&&relative!==".."&&!path.isAbsolute(relative));}
function linuxMountPoints(){if(process.platform!=="linux")return new Set<string>();try{return new Set(fs.readFileSync("/proc/self/mountinfo","utf8").split("\n").map(line=>line.split(" ")[4]).filter(Boolean).map(value=>path.resolve(value!.replace(/\\040/g," ").replace(/\\011/g,"\t").replace(/\\134/g,"\\"))));}catch{return new Set<string>();}}
function assertWorkspaceNotMounted(target:string){if(linuxMountPoints().has(path.resolve(target)))throw new Error("Mounted workspace deletion is not allowed.");const targetStat=fs.statSync(target),parentStat=fs.statSync(path.dirname(target));if(targetStat.dev!==parentStat.dev)throw new Error("Filesystem mount boundary deletion is not allowed.");}
function assertNoProcessCwd(target:string){if(process.platform!=="linux")return;for(const entry of fs.readdirSync("/proc")){if(!/^\d+$/.test(entry))continue;try{const cwd=fs.realpathSync(`/proc/${entry}/cwd`);if(inside(target,cwd))throw Object.assign(new Error("A running process is using this workspace."),{code:"WORKSPACE_IN_USE"});}catch(error){if((error as any)?.code==="WORKSPACE_IN_USE")throw error;}}}
function folder(value:string){if(!/^[A-Za-z0-9][A-Za-z0-9._ -]{0,79}$/.test(value)||/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$/i.test(value)||/[\\/:*?"<>|\u0000-\u001f]/.test(value))throw new Error("Invalid workspace folder name.");return value;}
function sign(config:WorkerConfig,rootId:string,relativePath:string){const payload=Buffer.from(JSON.stringify({rootId,relativePath})).toString("base64url");return`${payload}.${crypto.createHmac("sha256",config.entryKey).update(payload).digest("base64url")}`;}
function verify(config:WorkerConfig,value:string){const [payload,signature]=value.split(".");if(!payload||!signature)throw new Error("Invalid directory entry.");const expected=crypto.createHmac("sha256",config.entryKey).update(payload).digest(),actual=Buffer.from(signature,"base64url");if(expected.length!==actual.length||!crypto.timingSafeEqual(expected,actual))throw new Error("Invalid directory entry.");return JSON.parse(Buffer.from(payload,"base64url").toString()) as{rootId:string;relativePath:string};}
function root(config:WorkerConfig,id:string,permission:keyof Pick<WorkerRoot,"allowCreate"|"allowRegister"|"allowClone"|"allowDelete">){const item=config.roots.find(r=>r.id===id&&r[permission]);if(!item)throw new Error("Workspace root is not permitted for this operation.");return item;}
function workspace(config:WorkerConfig,id:string){const item=config.workspaces.find(w=>w.id===id);if(!item)throw new Error("Workspace not found.");const base=config.roots.find(r=>r.id===item.rootId);if(!base)throw new Error("Workspace root is unavailable.");const real=fs.realpathSync(item.canonicalPath);if(!inside(base.canonicalPath,real))throw new Error("Workspace escaped its approved root.");return{item,base,real};}
export function addRoot(config:WorkerConfig,rawPath:string,displayName?:string,allowDelete=false){const canonicalPath=fs.realpathSync(path.resolve(rawPath));if(!fs.statSync(canonicalPath).isDirectory())throw new Error("Root is not a directory.");fs.accessSync(canonicalPath,fs.constants.R_OK|fs.constants.X_OK);if(config.roots.some(item=>item.canonicalPath.toLowerCase()===canonicalPath.toLowerCase()))throw new Error("Root is already registered.");const item:WorkerRoot={id:crypto.randomUUID(),displayName:displayName??(path.basename(canonicalPath)||canonicalPath),canonicalPath,allowCreate:true,allowRegister:true,allowClone:true,allowDelete};config.roots.push(item);return item;}
export function removeRoot(config:WorkerConfig,id:string){if(config.workspaces.some(item=>item.rootId===id))throw new Error("Root still has registered workspaces.");const before=config.roots.length;config.roots=config.roots.filter(item=>item.id!==id);return before!==config.roots.length;}
export async function workspaceCommand(config:WorkerConfig,command:string,payload:any,hostId:string){
  if(command==="workspace.list")return config.roots.map(item=>({...item,hostId,createdAt:new Date().toISOString(),verifiedAt:new Date().toISOString(),disabledAt:null}));
  if(command==="workspace.browse"){
    const base=root(config,payload.rootId,"allowRegister");let relative=".";if(payload.entryId){const entry=verify(config,payload.entryId);if(entry.rootId!==base.id)throw new Error("Entry belongs to another root.");relative=entry.relativePath;}
    const current=fs.realpathSync(path.resolve(base.canonicalPath,relative));if(!inside(base.canonicalPath,current))throw new Error("Workspace root escape rejected.");const currentRelative=path.relative(base.canonicalPath,current)||".",entries=fs.readdirSync(current,{withFileTypes:true}).filter(item=>item.isDirectory()&&!item.isSymbolicLink()).slice(0,500).map(item=>{const real=fs.realpathSync(path.join(current,item.name));if(!inside(base.canonicalPath,real))return null;const rel=path.relative(base.canonicalPath,real)||".";return{id:sign(config,base.id,rel),name:item.name,relativePath:rel};}).filter(Boolean);return{root:{id:base.id,displayName:base.displayName},current:{id:sign(config,base.id,currentRelative),relativePath:currentRelative},entries};
  }
  if(command==="workspace.git.status"){const found=workspace(config,payload.workspaceId);return gitStatus(found.real);}
  if(command==="workspace.git.operation"){const found=workspace(config,payload.workspaceId);return executeGitOperation(found.real,payload.operation);}
  if(command==="workspace.git.log"){const found=workspace(config,payload.workspaceId);return gitLog(found.real,Number(payload.limit)||50);}
  if(command==="workspace.git.branches"){const found=workspace(config,payload.workspaceId);return gitBranches(found.real);}
  if(command==="workspace.github.pr.preview"){const found=workspace(config,payload.workspaceId);return githubPullRequestPreview(found.real);}
  if(command==="workspace.github.pr.create"){const found=workspace(config,payload.workspaceId);return createGithubPullRequest(found.real,payload.input);}
  if(command==="workspace.git.diff-path"){const found=workspace(config,payload.workspaceId);return coreGitDiff(found.real,{path:typeof payload.path==="string"?payload.path:undefined,staged:payload.staged===true});}
  if(command==="workspace.files.browse"){
    const found=workspace(config,payload.workspaceId),entry=payload.entryId?verify(config,payload.entryId):{rootId:`workspace:${found.item.id}`,relativePath:"."};if(entry.rootId!==`workspace:${found.item.id}`)throw new Error("Entry belongs to another workspace.");const current=safeWorkspaceEntry(found.real,entry.relativePath);if(!fs.statSync(current).isDirectory())throw new Error("Directory expected.");const relative=path.relative(found.real,current)||".";const entries=fs.readdirSync(current,{withFileTypes:true}).filter(item=>!item.isSymbolicLink()&&item.name!==".git").slice(0,1000).map(item=>{const target=path.join(current,item.name),stat=fs.statSync(target),rel=path.relative(found.real,target);return{id:sign(config,`workspace:${found.item.id}`,rel),name:item.name,type:item.isDirectory()?"directory":item.isFile()?"file":"other",size:item.isFile()?stat.size:null,modifiedAt:stat.mtime.toISOString(),sensitive:item.isFile()&&sensitiveFile(rel),relativePath:rel};});return{current:{id:sign(config,`workspace:${found.item.id}`,relative),relativePath:relative},entries};
  }
  if(command==="workspace.files.resolve"){
    const found=workspace(config,payload.workspaceId);
    if(payload.pathBase==="task-cwd"){
      const task=config.tasks.find(item=>item.id===payload.sourceTaskId&&item.workspaceId===found.item.id);
      if(!task)throw Object.assign(new Error("Source task does not belong to this workspace."),{code:"SOURCE_TASK_WORKSPACE_MISMATCH"});
    }else if(payload.pathBase!=="workspace")throw Object.assign(new Error("File path cannot be resolved."),{code:"FILE_PATH_UNRESOLVED"});
    const target=resolveWorkspaceTextPath(found.real,found.real,String(payload.path??""));
    return{entry:{id:sign(config,`workspace:${found.item.id}`,target.relative),name:path.basename(target.real),type:"file",size:target.stat.size,modifiedAt:target.stat.mtime.toISOString(),sensitive:sensitiveFile(target.relative),relativePath:target.relative}};
  }
  if(command==="workspace.files.edit.read"){
    const found=workspace(config,payload.workspaceId),entry=verify(config,payload.fileId);if(entry.rootId!==`workspace:${found.item.id}`)throw Object.assign(new Error("File entry belongs to another workspace."),{code:"WORKSPACE_FILE_ID_MISMATCH"});
    const target=resolveWorkspaceTextPath(found.real,found.real,entry.relativePath);
    return{fileId:payload.fileId,relativePath:target.relative,modifiedAt:target.stat.mtime.toISOString(),...decodeEditableText(fs.readFileSync(target.real))};
  }
  if(command==="workspace.files.write"){
    const found=workspace(config,payload.workspaceId),entry=verify(config,payload.fileId);if(entry.rootId!==`workspace:${found.item.id}`)throw Object.assign(new Error("File entry belongs to another workspace."),{code:"WORKSPACE_FILE_ID_MISMATCH"});
    const target=resolveWorkspaceTextPath(found.real,found.real,entry.relativePath);
    const result=writeEditableTextFile(target.real,String(payload.content??""),String(payload.expectedRevision??""),typeof payload.expectedCurrentRevision==="string"?payload.expectedCurrentRevision:undefined),status=await gitStatus(found.real).catch(()=>null);
    return{relativePath:target.relative,...result,status};
  }
  if(command==="workspace.files.read"){
    const found=workspace(config,payload.workspaceId),entry=verify(config,payload.fileId);if(entry.rootId!==`workspace:${found.item.id}`)throw new Error("Entry belongs to another workspace.");const target=safeWorkspaceEntry(found.real,entry.relativePath),stat=fs.statSync(target);if(!stat.isFile())throw new Error("File expected.");const sensitive=sensitiveFile(entry.relativePath);const offset=Math.min(Math.max(0,Number(payload.offset)||0),stat.size),limit=Math.min(Math.max(1,Number(payload.limit)||65536),128*1024),length=Math.min(limit,stat.size-offset),buffer=Buffer.alloc(length),fd=fs.openSync(target,"r");try{fs.readSync(fd,buffer,0,length,offset);}finally{fs.closeSync(fd);}const binary=buffer.includes(0);return{relativePath:entry.relativePath,size:stat.size,modifiedAt:stat.mtime.toISOString(),sensitive,requiresConfirmation:false,binary,content:binary?null:buffer.toString("utf8"),offset,nextOffset:offset+length<stat.size?offset+length:null};
  }
  if(command==="workspace.git.diff"){const found=workspace(config,payload.workspaceId);let relative:string|undefined;if(payload.fileId){const entry=verify(config,payload.fileId);if(entry.rootId!==`workspace:${found.item.id}`)throw new Error("Entry belongs to another workspace.");safeWorkspaceEntry(found.real,entry.relativePath);relative=entry.relativePath;}return coreGitDiff(found.real,{path:relative,head:true});}
  if(command==="workspace.register"){
    const base=root(config,payload.rootId,"allowRegister"),entry=verify(config,payload.entryId);if(entry.rootId!==base.id)throw new Error("Entry belongs to another root.");const target=fs.realpathSync(path.resolve(base.canonicalPath,entry.relativePath));if(!inside(base.canonicalPath,target))throw new Error("Workspace root escape rejected.");return{workspace:saveWorkspace(config,hostId,payload.projectId,base,target,payload.displayName??path.basename(target),"existing")};
  }
  if(command==="workspace.update"){
    const found=workspace(config,payload.workspaceId),displayName=String(payload.displayName??"").trim();if(!displayName)throw new Error("Workspace display name is required.");
    if(!payload.canonicalPath){found.item.displayName=displayName;found.item.updatedAt=new Date().toISOString();return{workspace:found.item,pathChanged:false};}
    const base=root(config,payload.rootId??found.item.rootId,"allowRegister"),requested=String(payload.canonicalPath).trim();if(!path.isAbsolute(requested))throw new Error("Workspace path must be absolute.");const lexical=path.resolve(requested);if(!inside(base.canonicalPath,lexical))throw new Error("Workspace path is outside the selected root.");
    let stat:fs.Stats,target:string;try{stat=fs.lstatSync(lexical);target=fs.realpathSync(lexical);}catch{throw new Error("Workspace path does not exist.");}if(!stat.isDirectory()||stat.isSymbolicLink()||target!==lexical||!inside(base.canonicalPath,target))throw new Error("Workspace path must be an exact real directory without a symlink escape.");
    const pathChanged=target!==found.item.canonicalPath||base.id!==found.item.rootId;if(pathChanged&&config.tasks.some(task=>task.workspaceId===found.item.id&&["pending","queued","starting","running","waiting","stopping","unknown"].includes(task.status)))throw new Error("Workspace path cannot change while a task is active or unconfirmed.");if(pathChanged&&config.workspaces.some(item=>item.id!==found.item.id&&item.canonicalPath.toLowerCase()===target.toLowerCase()))throw new Error("Workspace path is already registered.");
    Object.assign(found.item,{rootId:base.id,relativePath:path.relative(base.canonicalPath,target)||".",canonicalPath:target,displayName,updatedAt:new Date().toISOString()});return{workspace:found.item,pathChanged};
  }
  if(command==="workspace.create"){
    const base=root(config,payload.rootId,"allowCreate"),target=path.resolve(base.canonicalPath,folder(payload.folderName));if(!inside(base.canonicalPath,target)||fs.existsSync(target))throw new Error("Workspace destination exists or is invalid.");fs.mkdirSync(target,{mode:0o700});try{if(payload.readme)fs.writeFileSync(path.join(target,"README.md"),`# ${payload.displayName??payload.folderName}\n`,{mode:0o600,flag:"wx"});if(payload.mode==="git-init"){const branch=String(payload.defaultBranch??"main");if(!/^[A-Za-z0-9._/-]{1,100}$/.test(branch))throw new Error("Invalid branch.");const result=await runCommand("git",["init","-b",branch],{cwd:target,timeoutMs:30000,outputLimit:1024*1024});if(result.exitCode!==0)throw new Error("Git init failed.");}return{workspace:saveWorkspace(config,hostId,payload.projectId,base,fs.realpathSync(target),payload.displayName??payload.folderName,payload.mode)};}catch(error){try{if(fs.readdirSync(target).length===0)fs.rmdirSync(target);}catch{}throw error;}
  }
  if(command==="workspace.git.clone"){
    const base=root(config,payload.rootId,"allowClone"),repo=validateGitRemoteUrl(String(payload.repository??"")),target=path.resolve(base.canonicalPath,folder(payload.folderName));if(!inside(base.canonicalPath,target)||fs.existsSync(target))throw new Error("Clone destination exists or is invalid.");await cloneGitRepository(base.canonicalPath,target,{url:repo,branch:payload.branch,shallow:payload.shallow===true});return{workspace:saveWorkspace(config,hostId,payload.projectId,base,fs.realpathSync(target),payload.displayName??payload.folderName,"git-clone")};
  }
  if(command==="workspace.git.worktree"){
    const source=workspace(config,payload.workspaceId),base=root(config,source.base.id,"allowCreate"),status=await gitStatus(source.real);if(!status.repository||!status.commit)throw new Error("A committed Git workspace is required.");const name=folder(payload.folderName),target=path.resolve(base.canonicalPath,name);if(!inside(base.canonicalPath,target)||fs.existsSync(target))throw new Error("Worktree destination exists or is invalid.");const branch=String(payload.branch??"").trim();if(branch&&!/^[A-Za-z0-9][A-Za-z0-9._/-]{0,99}$/.test(branch))throw new Error("Invalid worktree branch name.");const result=await runCommand("git",["worktree","add",...(branch?["-b",branch]:["--detach"]),target,status.commit],{cwd:source.real,timeoutMs:60_000,outputLimit:1024*1024});if(result.exitCode!==0)throw new Error("Git worktree creation failed.");try{return{workspace:saveWorkspace(config,hostId,source.item.projectId,base,fs.realpathSync(target),payload.displayName??name,"git-worktree")};}catch(error){await runCommand("git",["worktree","remove","--force",target],{cwd:source.real,timeoutMs:30_000,outputLimit:1024*1024}).catch(()=>{});throw error;}
  }
  if(command==="workspace.unregister"){
    const found=workspace(config,payload.workspaceId);config.workspaces=config.workspaces.filter(item=>item.id!==found.item.id);return{unregistered:true,filesDeleted:false};
  }
  if(command==="workspace.delete"){
    const found=workspace(config,payload.workspaceId),base=root(config,found.base.id,"allowDelete");
    if(config.tasks.some(task=>task.workspaceId===found.item.id&&["pending","queued","running","waiting","unknown"].includes(task.status)))throw new Error("Workspace has an active or unconfirmed task.");
    if(found.real===base.canonicalPath||path.dirname(found.real)===found.real)throw new Error("Workspace root cannot be deleted.");
    if(payload.confirmName!==found.item.displayName&&payload.confirmName!==path.basename(found.real))throw new Error("Workspace deletion confirmation did not match.");
    const stat=fs.lstatSync(found.item.canonicalPath);if(!stat.isDirectory()||stat.isSymbolicLink())throw new Error("Only a verified directory workspace can be deleted.");const initialReal=fs.realpathSync(found.item.canonicalPath),initial=fs.statSync(initialReal);assertWorkspaceNotMounted(initialReal);assertNoProcessCwd(initialReal);
    const finalLink=fs.lstatSync(found.item.canonicalPath),finalReal=fs.realpathSync(found.item.canonicalPath),final=fs.statSync(finalReal);if(!inside(base.canonicalPath,finalReal)||finalReal===base.canonicalPath)throw new Error("Workspace root escape rejected.");if(finalLink.isSymbolicLink()||finalReal!==initialReal||final.dev!==initial.dev||final.ino!==initial.ino)throw new Error("Workspace identity changed during deletion verification.");
    fs.rmSync(finalReal,{recursive:true,force:false,maxRetries:2});config.workspaces=config.workspaces.filter(item=>item.id!==found.item.id);return{deleted:true,filesDeleted:true};
  }
  throw new Error("Unsupported workspace command.");
}
function sensitiveFile(relative:string){return/(^|[\\/])(?:\.env(?:\.|$)|credentials?(?:\.|$)|secrets?(?:\.|$)|id_(?:rsa|ed25519)|[^/\\]+\.(?:pem|key|p12|pfx)|\.npmrc|\.netrc)$/i.test(relative);}
function safeWorkspaceEntry(rootPath:string,relative:string){const lexical=path.resolve(rootPath,relative);if(!inside(rootPath,lexical))throw new Error("Workspace path escape rejected.");const stat=fs.lstatSync(lexical);if(stat.isSymbolicLink())throw new Error("Symbolic links are not exposed.");const real=fs.realpathSync(lexical);if(!inside(rootPath,real))throw new Error("Workspace path escape rejected.");return real;}
export function resolveWorkerWorkspaceDownload(config:WorkerConfig,workspaceId:string,relativePath:string){
  const found=workspace(config,workspaceId),requested=relativePath.trim();
  if(!requested||requested.includes("\0")||path.isAbsolute(requested))throw Object.assign(new Error("A relative workspace file path is required."),{code:"INVALID_WORKSPACE_FILE_PATH"});
  const real=safeWorkspaceEntry(found.real,requested),stat=fs.statSync(real);
  if(!stat.isFile())throw Object.assign(new Error("Download target must be a file."),{code:"WORKSPACE_FILE_EXPECTED"});
  if(stat.size>MAX_WORKSPACE_DOWNLOAD_BYTES)throw Object.assign(new Error(`Download file exceeds the ${formatByteLimit(MAX_WORKSPACE_DOWNLOAD_BYTES)} limit.`),{code:"WORKSPACE_DOWNLOAD_TOO_LARGE"});
  fs.accessSync(real,fs.constants.R_OK);
  return{real,relativePath:path.relative(found.real,real)||path.basename(real),name:path.basename(real),size:stat.size,modifiedAt:stat.mtime.toISOString(),device:stat.dev,inode:stat.ino};
}
function saveWorkspace(config:WorkerConfig,hostId:string,projectId:string,base:WorkerRoot,canonicalPath:string,displayName:string,workspaceType:WorkerWorkspace["workspaceType"]){if(config.workspaces.some(item=>item.canonicalPath.toLowerCase()===canonicalPath.toLowerCase()))throw new Error("Workspace already registered.");const timestamp=new Date().toISOString();const item:WorkerWorkspace={id:crypto.randomUUID(),projectId,hostId,rootId:base.id,relativePath:path.relative(base.canonicalPath,canonicalPath)||".",canonicalPath,displayName,workspaceType,createdAt:timestamp,updatedAt:timestamp};config.workspaces.push(item);return item;}
async function gitStatus(cwd:string){return coreGitStatus(cwd);}
export function requireWorkerWorkspace(config:WorkerConfig,id:string){return workspace(config,id);}
export function requireWorkerExecutionWorkspace(config:WorkerConfig,id:string){const item=config.workspaces.find(workspace=>workspace.id===id);if(!item)throw new Error("Workspace not found.");const workspacePath=item.canonicalPath,stat=fs.statSync(workspacePath);if(!stat.isDirectory())throw Object.assign(new Error("Workspace is not a directory."),{code:"ENOTDIR"});fs.accessSync(workspacePath,fs.constants.R_OK|fs.constants.X_OK);return{item,real:workspacePath};}
export async function createWorkspacePatch(config:WorkerConfig,id:string){const found=workspace(config,id),status=await gitStatus(found.real);if(!status.repository)throw new Error("Patch is available only for Git workspaces.");const excluded=status.changedFiles.filter((item:string)=>/(^|\/)(\.env(?:\.|$)|id_(?:rsa|ed25519)|.*\.(?:pem|key|p12|pfx)|credentials?(?:\.|$)|secrets?(?:\.|$))/i.test(item)),args=["diff","--binary","--no-ext-diff","--",".",...excluded.map((item:string)=>`:(exclude,literal)${item}`)];const result=await runCommand("git",args,{cwd:found.real,timeoutMs:30000,outputLimit:8*1024*1024+1});if(result.overflow||Buffer.byteLength(result.stdout)>8*1024*1024)throw new Error("Patch exceeds the 8 MiB limit.");return Buffer.from(result.stdout);}
