import dns from"node:dns/promises";
import net from"node:net";
import type{ExternalAccessCheck}from"../types.js";
const checked=()=>new Date().toISOString();
const result=(code:string,status:ExternalAccessCheck["status"],detail:string):ExternalAccessCheck=>({code,status,detail,checkedAt:checked()});
export async function runConnectionTests(input:{localOrigin:string;externalOrigin:string|null;configuredOrigin?:string;provider:"local"|"tailscale"|"cloudflare";fetcher?:typeof fetch}){
 const fetcher=input.fetcher??fetch,checks:ExternalAccessCheck[]=[];
 try{const response=await fetcher(new URL("/api/health/live",input.localOrigin),{signal:AbortSignal.timeout(4000)});checks.push(result("local_health",response.ok?"passed":"failed",response.ok?"Local health endpoint responded.":`Local health returned HTTP ${response.status}.`));}catch{checks.push(result("local_health","failed","Local health endpoint did not respond."));}
 if(!input.externalOrigin)return checks;
 const origin=new URL(input.externalOrigin);try{const addresses=await dns.lookup(origin.hostname,{all:true});if(input.provider==="cloudflare"&&addresses.some(item=>!publicAddress(item.address)))throw new Error("private-address");checks.push(result("dns","passed","External hostname resolved."));}catch(error){checks.push(result("dns","failed",(error as Error).message==="private-address"?"External hostname resolved to a private or local address; the server-side probe was blocked.":"External hostname did not resolve."));return checks;}
 let html:Response|null=null;try{html=await fetcher(origin,{redirect:"manual",signal:AbortSignal.timeout(8000),headers:{Accept:"text/html"}});const cloudflareRedirect=html.status>=300&&html.status<400&&/cloudflareaccess\.com|\/cdn-cgi\/access\//i.test(html.headers.get("location")??"");checks.push(result("tls",origin.protocol==="https:"?"passed":"failed",origin.protocol==="https:"?"HTTPS connection completed.":"External origin is not HTTPS."));checks.push(result("auth_boundary",input.provider==="cloudflare"&&cloudflareRedirect||html.status===401||html.status===403?"passed":input.provider==="local"&&html.ok?"passed":"warning",cloudflareRedirect||html.status===401||html.status===403?"Anonymous access was blocked.":"Authentication boundary requires an authenticated browser check."));checks.push(result("html",html.ok||cloudflareRedirect?"passed":"warning",html.ok?"Workhouse HTML endpoint responded.":`HTML probe returned HTTP ${html.status}.`));}catch{checks.push(result("tls","failed","HTTPS connection failed."));checks.push(result("html","failed","Workhouse HTML could not be reached."));}
 try{const response=await fetcher(new URL("/api/health/live",origin),{redirect:"manual",signal:AbortSignal.timeout(5000)}),protectedResponse=[302,303,307,401,403].includes(response.status);checks.push(result("api_health",response.ok||protectedResponse?"passed":"failed",response.ok?"External API health responded.":protectedResponse?"External API health is behind the authentication boundary.":`External API health returned HTTP ${response.status}.`));const location=response.headers.get("location");checks.push(result("origin_redirect",location&&location.startsWith(input.localOrigin)?"failed":"passed",location&&location.startsWith(input.localOrigin)?"External traffic redirected to the internal origin.":"No redirect to the internal origin was observed."));}catch{checks.push(result("api_health","warning","External API health probe could not complete."));}
 try{const response=await fetcher(new URL("/manifest.webmanifest",origin),{redirect:"manual",signal:AbortSignal.timeout(5000)});checks.push(result("pwa_manifest",response.ok||response.status===302||response.status===403?"passed":"warning",`Manifest probe returned HTTP ${response.status}.`));}catch{checks.push(result("pwa_manifest","warning","Manifest probe could not complete."));}
 const originMatches=!input.configuredOrigin||new URL(input.configuredOrigin).origin===origin.origin;checks.push(result("notification_origin",originMatches?"passed":"warning",originMatches?"Configured deep-link origin matches the tested address.":"Workhouse must restart before notification deep links use the new external origin."));checks.push(result("sse","warning","SSE requires an authenticated browser probe and was not claimed healthy by the server-side anonymous test."));checks.push(result("websocket","skipped","No browser WebSocket endpoint is exposed; Worker WSS is verified by infrastructure diagnostics."));
 return checks;
}
export function publicAddress(address:string){if(net.isIPv4(address)){const[a,b]=address.split(".").map(Number);return !(a===10||a===127||a===0||a===169&&b===254||a===172&&b>=16&&b<=31||a===192&&b===168||a===100&&b>=64&&b<=127||a>=224);}const value=address.toLowerCase();return !(value==="::"||value==="::1"||value.startsWith("fe80:")||value.startsWith("fc")||value.startsWith("fd")||value.startsWith("::ffff:127.")||value.startsWith("::ffff:10.")||value.startsWith("::ffff:192.168."));}
