import { writable, type Readable } from "svelte/store";
import { deriveCollaborationContinuation } from "../server/collaboration/continuation.js";
import { assertUniqueKeys } from "./identity-selectors";
import { collaborationAvatarKey, collaborationMessageKey, collaborationParticipantKey, collaborationRunKey } from "./collaboration-identity";

export type CollaborationLiveState={detail:any|null;revision:number;sequence:number;connection:"live"|"delayed"|"offline";gap:boolean};

function revisionOf(value:any){return Math.max(0,Number(value?.revision??value?.session?.revision)||0);}

export class CollaborationStore implements Readable<CollaborationLiveState>{
  private state:CollaborationLiveState={detail:null,revision:0,sequence:0,connection:"delayed",gap:false};
  private subject=writable(this.state);
  subscribe=this.subject.subscribe;
  private publish(){this.subject.set(this.state);}
  reset(){this.state={detail:null,revision:0,sequence:0,connection:"delayed",gap:false};this.publish();}
  connection(value:CollaborationLiveState["connection"]){if(this.state.connection===value)return;this.state={...this.state,connection:value};this.publish();}
  cursor(sequence:number){const next=Math.max(this.state.sequence,Math.max(0,Number(sequence)||0));if(next===this.state.sequence)return;this.state={...this.state,sequence:next};this.publish();}
  snapshot(next:any){
    const revision=revisionOf(next),current=this.state.detail,stale=Boolean(current&&revision&&revision<this.state.revision),sameRevision=Boolean(current&&revision&&revision===this.state.revision);
    const sessionId=String(next?.session?.id??current?.session?.id??"");
    const mergeRows=(keyFor:(item:any)=>string,previous:any[]=[],incoming:any[]=[])=>{const rows=new Map<string,any>();for(const item of stale?incoming:previous)rows.set(keyFor(item),item);for(const item of stale?previous:incoming){const key=keyFor(item),existing=rows.get(key);rows.set(key,existing?{...existing,...item}:item);}return [...rows.values()];},mergeRuns=(previous:any[]=[],incoming:any[]=[])=>{const rows=new Map<string,any>();for(const item of previous)rows.set(collaborationRunKey(sessionId,item),item);for(const item of incoming){const key=collaborationRunKey(sessionId,item),existing=rows.get(key),existingGeneration=Number(existing?.generation)||0,incomingGeneration=Number(item?.generation)||0;if(existing&&existingGeneration>incomingGeneration)continue;if(existing&&existingGeneration===incomingGeneration&&["completed","failed","timed-out","cancelled","stop-unconfirmed"].includes(existing.status)&&!["completed","failed","timed-out","cancelled","stop-unconfirmed"].includes(item.status))continue;rows.set(key,existing?{...existing,...item}:item);}return [...rows.values()];};
    const session=stale?current.session:sameRevision&&current&&["completed","partial","failed","cancelled","stop-unconfirmed"].includes(current.session?.status)&&!["completed","partial","failed","cancelled","stop-unconfirmed"].includes(next?.session?.status)?current.session:{...(current?.session??{}),...(next?.session??{})};
    const runs=mergeRuns(current?.runs,next?.runs),messages=mergeRows(item=>collaborationMessageKey(sessionId,item),current?.messages,next?.messages),preferCurrent=stale||sameRevision,detail={...(stale?next:current??{}),...(stale?current:next),revision:Math.max(revisionOf(current),revision),session,runs,messages,participants:mergeRows(item=>collaborationParticipantKey(sessionId,item),current?.participants,next?.participants),avatarStates:mergeRows(item=>collaborationAvatarKey(sessionId,item),current?.avatarStates,next?.avatarStates),tasks:preferCurrent?{...(next?.tasks??{}),...(current?.tasks??{})}:{...(current?.tasks??{}),...(next?.tasks??{})},runOutputs:preferCurrent?{...(next?.runOutputs??{}),...(current?.runOutputs??{})}:{...(current?.runOutputs??{}),...(next?.runOutputs??{})}};
    if(import.meta.env?.DEV)assertUniqueKeys("CollaborationStore runs",runs,(run:any)=>collaborationRunKey(sessionId,run));
    detail.continuation=deriveCollaborationContinuation(session,runs);
    this.state={...this.state,detail,revision:Math.max(this.state.revision,revision),gap:false};this.publish();return true;
  }
  event(raw:any){
    const incoming=Math.max(0,Number(raw?.revision)||0),sequence=Math.max(0,Number(raw?.sequence)||0),gap=Boolean(sequence&&this.state.sequence&&sequence>this.state.sequence+1);if(sequence&&sequence<=this.state.sequence)return{applied:false,gap:false};
    const detail=this.state.detail;if(!detail){this.state={...this.state,revision:Math.max(this.state.revision,incoming),sequence:Math.max(this.state.sequence,sequence),gap:this.state.gap||gap};this.publish();return{applied:false,gap};}
    if(!raw.runId&&Number(raw.generation)>0&&Number(raw.generation)<Math.max(0,Number(detail.session?.controllerGeneration)||0)){this.state={...this.state,revision:Math.max(this.state.revision,incoming),sequence:Math.max(this.state.sequence,sequence),gap:this.state.gap||gap};this.publish();return{applied:false,gap};}
    let runs=[...(detail.runs??[])],index=runs.findIndex((run:any)=>run.id===raw.runId);
    if(index>=0&&Number(raw.generation)>0&&Number(raw.generation)<Math.max(0,Number(runs[index].generation)||0)){this.state={...this.state,revision:Math.max(this.state.revision,incoming),sequence:Math.max(this.state.sequence,sequence),gap:this.state.gap||gap};this.publish();return{applied:false,gap};}
    if(index<0&&raw.runId&&raw.type==="run/started")runs.push({id:raw.runId,collaborationSessionId:raw.collaborationSessionId,participantId:raw.participantId,providerTaskId:raw.metadata?.providerTaskId??null,status:"running",sequence:Number(raw.metadata?.sequence)||runs.length+1,round:Number(raw.metadata?.round)||1,generation:Number(raw.generation)||1,purpose:raw.metadata?.purpose??"conversation-turn",attempt:1,errorCategory:null,startedAt:raw.timestamp,completedAt:null,failedAt:null,cancelledAt:null});
    else if(index>=0){const run=runs[index],generation=Math.max(0,Number(raw.generation)||0),runGeneration=Math.max(0,Number(run.generation)||0);if(!generation||generation>=runGeneration){const status=raw.type==="run/started"?"running":raw.type==="run/completed"?"completed":raw.type==="run/waiting-approval"?"waiting-approval":raw.type==="run/failed"?"failed":raw.type==="run/cancelled"?"cancelled":raw.type==="run/stop-unconfirmed"?"stop-unconfirmed":raw.metadata?.status??run.status,sameGeneration=!generation||generation===runGeneration,terminal=["completed","failed","timed-out","cancelled","stop-unconfirmed"];if(!(sameGeneration&&terminal.includes(run.status)&&!terminal.includes(status)))runs[index]={...run,status,generation:generation||run.generation,providerTaskId:raw.metadata?.providerTaskId??run.providerTaskId};}}
    const sessionEvent=["collaboration/status","collaboration/completed","collaboration/partial"].includes(raw.type),sessionMetadata=raw.metadata?.sessionMetadata&&typeof raw.metadata.sessionMetadata==="object"?raw.metadata.sessionMetadata:null,session=sessionEvent?{...detail.session,status:raw.metadata?.status??(raw.type==="collaboration/completed"?"completed":raw.type==="collaboration/partial"?"partial":detail.session.status),currentStep:raw.metadata?.currentStep??detail.session.currentStep,outcome:Object.prototype.hasOwnProperty.call(raw.metadata??{},"outcome")?raw.metadata.outcome:detail.session.outcome,maxTurnsPerParticipant:Object.prototype.hasOwnProperty.call(raw.metadata??{},"maxTurnsPerParticipant")?raw.metadata.maxTurnsPerParticipant:detail.session.maxTurnsPerParticipant,revision:Math.max(Number(detail.session.revision)||0,incoming),metadata:sessionMetadata?{...detail.session.metadata,...sessionMetadata}:detail.session.metadata}:detail.session;
    if(import.meta.env?.DEV)assertUniqueKeys("CollaborationStore runs",runs,(run:any)=>collaborationRunKey(detail.session?.id,run));
    const continuation=deriveCollaborationContinuation(session,runs);this.state={...this.state,detail:{...detail,revision:Math.max(revisionOf(detail),incoming),session,runs,continuation},revision:Math.max(this.state.revision,incoming),sequence:Math.max(this.state.sequence,sequence),gap:this.state.gap||gap};this.publish();return{applied:true,gap};
  }
}
