<script lang="ts">
  import{onMount}from"svelte";
  import QRCode from"qrcode";
  import{CheckCircle2,ChevronLeft,Copy,ExternalLink,Globe2,RefreshCw,ShieldCheck,X}from"@lucide/svelte";
  import{t}from"./i18n";
  export let api:(path:string,init?:RequestInit)=>Promise<any>;
  let open=false,step=1,provider:"local"|"tailscale"|"cloudflare"="local",busy=false,error="",detections:any[]=[];
  let configuration:any=null,plan:any=null,operation:any=null,checks:any[]=[];
  let hostname="",allowedEmail="",teamDomain="",audience="",token="",runMode:"existing"|"host"|"sidecar"="existing",qr="";
  $: current=detections.find(item=>item.provider===provider);
  $: finalUrl=operation?.profileId&&provider!=="local"?`https://${hostname}`:configuration?.externalOrigin??"";
  async function load(){try{[configuration,detections]=await Promise.all([api("/api/external-access/v1/configuration"),api("/api/external-access/v1/detect",{method:"POST",body:JSON.stringify({})})]);provider=configuration.authMode==="tailscale"||configuration.authMode==="cloudflare"?configuration.authMode:"local";}catch(e){error=e instanceof Error?e.message:String(e)}}
  async function detect(){busy=true;error="";try{detections=await api("/api/external-access/v1/detect",{method:"POST",body:JSON.stringify({})});step=2;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  function planBody(){if(provider==="local")return{provider,action:"local_configuration_apply"};if(provider==="tailscale")return{provider,action:"tailscale_serve_apply",...(hostname?{hostname}:{}),...(allowedEmail?{allowedEmail}:{}),localTarget:"http://127.0.0.1:3410"};return{provider,action:runMode==="existing"?"cloudflare_validate":"cloudflare_managed_config_apply",hostname,...(teamDomain?{teamDomain}:{}),...(audience?{audience}:{}),...(allowedEmail?{allowedEmail}:{}),localTarget:"http://127.0.0.1:3410",runMode,...(token?{token}:{})};}
  async function createPlan(){busy=true;error="";try{plan=await api("/api/external-access/v1/plans",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(planBody())});token="";step=4;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function apply(){busy=true;error="";try{operation=await api(`/api/external-access/v1/plans/${plan.id}/apply`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({planDigest:plan.planDigest,configurationRevision:plan.configurationRevision})});step=5;watch(operation.id);}catch(e){error=e instanceof Error?e.message:String(e);busy=false}}
  function watch(id:string){const source=new EventSource(`/api/external-access/v1/operations/${id}/events`);source.addEventListener("operation",async event=>{operation=JSON.parse((event as MessageEvent).data);checks=operation.checks??[];if(["succeeded","degraded","failed","interrupted","rolled_back","rollback_failed","waiting_external_action"].includes(operation.status)){source.close();busy=false;step=operation.status==="failed"||operation.status==="waiting_external_action"?6:7;if(finalUrl)qr=await QRCode.toDataURL(finalUrl,{width:240,margin:1});}});source.onerror=()=>{source.close();void poll(id);};}
  async function poll(id:string){try{operation=await api(`/api/external-access/v1/operations/${id}`);checks=operation.checks??[];if(["pending","running","verifying","rolling_back"].includes(operation.status))setTimeout(()=>void poll(id),1000);else{busy=false;step=operation.status==="failed"||operation.status==="waiting_external_action"?6:7;if(finalUrl)qr=await QRCode.toDataURL(finalUrl,{width:240,margin:1});}}catch(e){error=e instanceof Error?e.message:String(e);busy=false}}
  async function runTests(){busy=true;error="";try{checks=await api("/api/external-access/v1/tests",{method:"POST",body:JSON.stringify({provider,...(operation?.profileId?{profileId:operation.profileId}:{})})});step=6;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function rollback(){if(!operation?.id)return;busy=true;error="";try{const result=await api(`/api/external-access/v1/operations/${operation.id}/rollback`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({})});plan=result.plan;step=4;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function removeConfiguration(){if(!operation?.profileId)return;busy=true;error="";try{plan=await api(`/api/external-access/v1/configuration/${operation.profileId}`,{method:"DELETE",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({})});step=4;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function copyUrl(){if(finalUrl)await navigator.clipboard.writeText(finalUrl)}
  onMount(()=>void load());
</script>
<section class="external-access" aria-labelledby="external-access-title">
  <header><Globe2 size={21}/><span><h4 id="external-access-title">{$t("externalAccess.title")}</h4><small>{$t("externalAccess.body")}</small></span><button type="button" onclick={()=>open=!open}>{$t(open?"common.close":"externalAccess.configure")}</button></header>
  <div class="summary"><span><small>{$t("externalAccess.currentMode")}</small><strong>{configuration?.authMode??"—"}</strong></span><span><small>{$t("externalAccess.address")}</small><strong>{configuration?.externalOrigin??$t("infrastructure.notConfigured")}</strong></span></div>
  {#if open}<div class="wizard">
    <div class="wizard-head"><b>{$t("externalAccess.step",{current:step,total:7})}</b>{#if step>1}<button type="button" class="icon" aria-label={$t("common.back")} onclick={()=>step=Math.max(1,step-1)}><ChevronLeft size={18}/></button>{/if}</div>
    {#if step===1}<h5>{$t("externalAccess.choose")}</h5><div class="choices"><button class:active={provider==="local"} onclick={()=>provider="local"}><b>{$t("externalAccess.local")}</b><small>{$t("externalAccess.localBody")}</small></button><button class:active={provider==="tailscale"} onclick={()=>provider="tailscale"}><b>{$t("externalAccess.provider.tailscale")}</b><small>{$t("externalAccess.tailscaleBody")}</small></button><button class:active={provider==="cloudflare"} onclick={()=>provider="cloudflare"}><b>{$t("externalAccess.provider.cloudflare")}</b><small>{$t("externalAccess.cloudflareBody")}</small></button></div><button class="primary" onclick={detect} disabled={busy}><RefreshCw size={15}/>{$t("externalAccess.detect")}</button>
    {:else if step===2}<h5>{$t("externalAccess.detected")}</h5>{#if current}<dl class="detected"><div><dt>{$t("externalAccess.installation")}</dt><dd>{current.installed?$t("externalAccess.installed"):$t("externalAccess.notInstalled")}</dd></div><div><dt>{$t("externalAccess.service")}</dt><dd>{current.serviceRunning===true?$t("externalAccess.running"):current.serviceRunning===false?$t("externalAccess.stopped"):$t("common.unknown")}</dd></div><div><dt>{$t("externalAccess.login")}</dt><dd>{current.authenticated===true?$t("externalAccess.loggedIn"):current.authenticated===false?$t("externalAccess.loginRequired"):$t("common.unknown")}</dd></div><div><dt>{$t("externalAccess.state")}</dt><dd>{$t(`externalAccess.state.${current.state}`)}</dd></div></dl>{/if}<button class="primary" onclick={()=>step=3}>{$t("common.next")}</button>
    {:else if step===3}<h5>{$t("externalAccess.input")}</h5>{#if provider==="local"}<p>{$t("externalAccess.localReady")}</p>{:else}<label>{$t("externalAccess.hostname")}<input bind:value={hostname} placeholder={$t(provider==="tailscale"?"externalAccess.hostnamePlaceholder.tailscale":"externalAccess.hostnamePlaceholder.cloudflare")}/></label><label>{$t("externalAccess.allowedEmail")}<input type="email" bind:value={allowedEmail} autocomplete="email"/></label>{#if provider==="cloudflare"}<label>{$t("externalAccess.runMode")}<select bind:value={runMode}><option value="existing">{$t("externalAccess.existing")}</option><option value="host">{$t("externalAccess.hostService")}</option><option value="sidecar">{$t("externalAccess.sidecar")}</option></select></label><label>{$t("externalAccess.teamDomain")}<input bind:value={teamDomain} placeholder={$t("externalAccess.teamDomainPlaceholder")}/></label><label>{$t("externalAccess.audience")}<input bind:value={audience}/></label>{#if runMode!=="existing"}<label>{$t("externalAccess.token")}<input type="password" bind:value={token} autocomplete="new-password"/><small>{$t("externalAccess.tokenHelp")}</small></label>{/if}{/if}{/if}<button class="primary" onclick={createPlan} disabled={busy}>{$t("externalAccess.review")}</button>
    {:else if step===4}<h5>{$t("externalAccess.plan")}</h5><ul>{#each plan?.steps??[] as item}<li><CheckCircle2 size={15}/>{item.label}</li>{/each}</ul>{#if plan?.commands?.length}<div class="commands"><b>{$t("externalAccess.commands")}</b>{#each plan.commands as command}<code>{command.argv.join(" ")}</code><small>{command.execution==="automatic"?$t("externalAccess.commandAutomatic"):$t("externalAccess.commandOperator")}</small>{/each}</div>{/if}<div class="warnings"><p><b>{$t("externalAccess.exposure")}</b> {plan.publicExposure}</p><p><b>{$t("externalAccess.authBoundary")}</b> {plan.authenticationBoundary}</p><p><b>{$t("externalAccess.adminRequired")}</b> {plan.adminRequired?$t("common.yes"):$t("common.no")}</p>{#each plan.externalActions??[] as item}<p>{item}</p>{/each}</div><button class="primary" onclick={apply} disabled={busy}><ShieldCheck size={15}/>{$t("externalAccess.approve")}</button>
    {:else if step===5}<h5>{$t("externalAccess.applying")}</h5><p class="progress"><RefreshCw size={16} class="spin"/>{operation?.stage??"queued"}</p>
    {:else if step===6}<h5>{$t("externalAccess.tests")}</h5><div class="checks">{#each checks as check}<div class={check.status}><b>{check.code}</b><span>{check.detail}</span></div>{/each}</div><button onclick={runTests} disabled={busy}><RefreshCw size={15}/>{$t("externalAccess.testAgain")}</button>{#if operation?.status==="failed"&&operation?.profileId}<button class="danger" onclick={rollback} disabled={busy}>{$t("externalAccess.rollback")}</button>{:else}<button class="primary" onclick={()=>step=7}>{$t("common.next")}</button>{/if}
    {:else}<h5>{$t("externalAccess.complete")}</h5>{#if finalUrl}<a class="url" href={finalUrl} target="_blank" rel="noreferrer">{finalUrl}<ExternalLink size={15}/></a><div class="finish-actions"><button onclick={copyUrl}><Copy size={15}/>{$t("common.copy")}</button><a href={finalUrl} target="_blank" rel="noreferrer">{$t("externalAccess.open")}</a></div>{#if qr}<img class="qr" src={qr} alt={$t("externalAccess.qrAlt")}/>{/if}{/if}<button onclick={runTests} disabled={busy}><RefreshCw size={15}/>{$t("externalAccess.testAgain")}</button>{#if operation?.profileId}<button class="danger" onclick={removeConfiguration} disabled={busy}>{$t("externalAccess.remove")}</button>{/if}{/if}
    {#if error}<p class="error" role="alert"><X size={15}/>{error}</p>{/if}
  </div>{/if}
</section>
<style>
  .external-access{display:grid;gap:.7rem;padding:.8rem;border:1px solid var(--line);border-radius:14px;background:var(--panel)}header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:.65rem}header span{display:grid;min-width:0}h4,h5,p{margin:0}small{color:var(--muted)}.summary{display:grid;grid-template-columns:1fr 2fr;gap:.4rem}.summary span{display:grid;min-width:0;padding:.5rem;border-radius:9px;background:var(--bg)}.summary strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.wizard{display:grid;gap:.7rem;padding:.75rem;border-top:1px solid var(--line)}.wizard-head{display:flex;align-items:center;justify-content:space-between}.choices{display:grid;grid-template-columns:repeat(3,1fr);gap:.5rem}.choices button{display:grid;gap:.25rem;text-align:left;padding:.7rem}.choices button.active{border-color:var(--accent);background:var(--accent-soft)}label{display:grid;gap:.3rem}input,select{width:100%;min-height:42px}.primary{display:inline-flex;align-items:center;justify-content:center;gap:.35rem;background:var(--accent);color:var(--on-accent)}.detected{display:grid;grid-template-columns:1fr 1fr;gap:.4rem;margin:0}.detected div{padding:.5rem;border-radius:9px;background:var(--bg)}dt{font-size:.7rem;color:var(--muted)}dd{margin:0}.wizard ul{display:grid;gap:.4rem;padding:0;list-style:none}.wizard li{display:flex;gap:.4rem;align-items:center}.commands,.warnings,.checks{display:grid;gap:.35rem}.commands{min-width:0}.commands code{overflow:auto;padding:.55rem;border-radius:9px;background:var(--bg);white-space:nowrap}.warnings p,.checks div{padding:.5rem;border-radius:9px;background:var(--bg)}.checks div{display:grid}.checks .passed{border-left:3px solid var(--good)}.checks .warning{border-left:3px solid var(--warn)}.checks .failed{border-left:3px solid var(--danger)}.progress,.error{display:flex;align-items:center;gap:.4rem}.error{color:var(--danger)}.url{display:flex;align-items:center;gap:.35rem;word-break:break-all}.finish-actions{display:flex;gap:.5rem;flex-wrap:wrap}.finish-actions a{padding:.55rem .75rem;border:1px solid var(--line);border-radius:9px}.qr{width:180px;max-width:100%;border-radius:10px}.icon{padding:.35rem}
  @media(max-width:600px){.summary,.detected{grid-template-columns:1fr}.choices{grid-template-columns:1fr}.external-access>header{grid-template-columns:auto 1fr}.external-access>header button{grid-column:1/-1;min-height:44px}.wizard>.primary{width:100%;min-height:46px}}
</style>
