<script lang="ts">
  import { FileCode2, GitBranch, RefreshCw } from "@lucide/svelte";
  import { onMount } from "svelte";
  import { locale, t as i18n, formatDateTime } from "./i18n";
  export let api:(path:string,init?:RequestInit)=>Promise<any>;
  export let workspace:{id:string;displayName:string;lastGitStatus?:any};
  export let onopenfile:(path:string)=>void=()=>{};
  type View="changes"|"branches"|"remotes"|"log";
  let status:any=workspace.lastGitStatus??null,view:View="changes",branches:any[]=[],commits:any[]=[],selected=new Set<string>(),diff="",activePath="",message="",busy=false,notice="",pullStrategy=(localStorage.getItem("claudex-workhouse-git-pull-strategy")||"ff-only") as "ff-only"|"merge"|"rebase",branchName="",remoteName="origin",remoteUrl="",cloneUrl="",cloneBranch="",cloneShallow=false;
  const t=(key:string)=>$i18n(`git.${key}`);
  async function refresh(){busy=true;notice="";try{status=(await api(`/api/workspaces/${workspace.id}/git-status`)).status;workspace.lastGitStatus=status;selected=new Set([...selected].filter(item=>status.changedFiles?.includes(item)));}catch(error){notice=error instanceof Error?error.message:String(error)}finally{busy=false;}}
  async function operation(operation:any){busy=true;notice="";try{const result=await api(`/api/workspaces/${workspace.id}/git/operation`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(operation)});status=result.status??status;workspace.lastGitStatus=status;notice=t("operationDone");selected=new Set();if(view==="branches")await loadBranches();if(view==="log")await loadLog();return true;}catch(error){const text=error instanceof Error?error.message:String(error);if(operation.type==="push"&&!operation.confirmDanger&&/protected branch/i.test(text)&&confirm(t("protectedPushConfirm")))return operation({...operation,confirmDanger:true});notice=text;return false;}finally{busy=false;}}
  async function showDiff(path:string,staged=false){activePath=path;try{const data=await api(`/api/workspaces/${workspace.id}/git/diff`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({path,staged})});diff=data.diff||t("noChanges");}catch(error){notice=error instanceof Error?error.message:String(error)}}
  async function loadBranches(){try{branches=(await api(`/api/workspaces/${workspace.id}/git/branches`)).branches??[];}catch(error){notice=error instanceof Error?error.message:String(error)}}
  async function loadLog(){try{commits=(await api(`/api/workspaces/${workspace.id}/git/log?limit=100`)).commits??[];}catch(error){notice=error instanceof Error?error.message:String(error)}}
  function chooseView(next:View){view=next;if(next==="branches")void loadBranches();if(next==="log")void loadLog();}
  function toggle(path:string){const next=new Set(selected);next.has(path)?next.delete(path):next.add(path);selected=next;}
  function checkedPaths(){return [...selected];}
  async function commit(push=false){if(!await operation({type:"commit",message}))return;message="";if(push)await operation({type:"push",force:"none"});}
  async function publish(){if(!status?.branch||!confirm($i18n("git.publishConfirm",{branch:status.branch})))return;await operation({type:"push",remote:"origin",branch:status.branch,setUpstream:true,force:"none",confirmDanger:true});}
  function setStrategy(value:string){pullStrategy=value as typeof pullStrategy;localStorage.setItem("claudex-workhouse-git-pull-strategy",value);}
  onMount(refresh);
</script>
<section class="git-panel">
  {#if !status}<p>{t("loading")}</p>
  {:else if !status.repository}<div class="not-repo"><GitBranch size={32}/><strong>{t("notRepository")}</strong><button class="primary" disabled={busy} onclick={()=>operation({type:"init",branch:"main"})}>{t("init")}</button><form onsubmit={(event)=>{event.preventDefault();void operation({type:"clone",url:cloneUrl,branch:cloneBranch||undefined,shallow:cloneShallow});}}><input bind:value={cloneUrl} maxlength="2048" inputmode="url" placeholder="https://github.com/owner/repository.git" required/><input bind:value={cloneBranch} maxlength="200" placeholder={t("optionalBranch")}/><label><input type="checkbox" bind:checked={cloneShallow}/>{t("shallowClone")}</label><button disabled={busy}>{t("clone")}</button></form><small>{t("cloneEmptyOnly")}</small></div>
  {:else}
    <header><div><strong>{status.detached?t("detached"):status.branch}</strong><small>{status.root} · {status.upstream??t("noUpstream")}</small></div><button aria-label={t("refresh")} onclick={refresh} disabled={busy}><RefreshCw size={16}/></button></header>
    <div class="summary"><span>{t("changes")} <b>{status.changedFiles?.length??0}</b></span><span>{t("staged")} <b>{status.staged??0}</b></span><span>{t("untracked")} <b>{status.untracked??0}</b></span><span class:danger={status.conflicts}>{t("conflicts")} <b>{status.conflicts??0}</b></span><span>{t("ahead")} <b>{status.ahead??0}</b></span><span>{t("behind")} <b>{status.behind??0}</b></span></div>
    <div class="network"><button onclick={()=>operation({type:"fetch",remote:"origin",prune:true,tags:false,all:false})} disabled={busy||!status.remotes?.length}>{t("fetch")}</button><label>{t("strategy")}<select value={pullStrategy} onchange={(event)=>setStrategy((event.currentTarget as HTMLSelectElement).value)}><option value="ff-only">{t("fastForwardOnly")}</option><option value="merge">{t("merge")}</option><option value="rebase">{t("rebase")}</option></select></label><button onclick={()=>operation({type:"pull",strategy:pullStrategy,autoStash:false})} disabled={busy||status.dirty||status.detached}>{t("pull")}</button>{#if status.upstream}<button class="primary" onclick={()=>operation({type:"push",force:"none"})} disabled={busy}>{t("push")}</button><button class="danger" onclick={()=>confirm(t("forcePushConfirm"))&&operation({type:"push",force:"force-with-lease",confirmDanger:true})} disabled={busy}>{t("forceWithLease")}</button>{:else}<button class="primary" onclick={publish} disabled={busy||status.detached||!status.remotes?.length}>{t("publishBranch")}</button>{/if}</div>{#if status.dirty}<small class="dirty-hint">{t("dirtyPull")}</small>{/if}
    {#if status.operation}<div class="conflict"><strong>{status.operation} · {t("conflicts")} {status.conflicts}</strong><button onclick={()=>operation({type:"continue",operation:status.operation})} disabled={status.conflicts>0}>{t("continue")}</button><button class="danger" onclick={()=>confirm($i18n("git.abortConfirm",{operation:status.operation}))&&operation({type:"abort",operation:status.operation,confirmDanger:true})}>{t("abort")}</button></div>{/if}
    <nav><button class:active={view==="changes"} onclick={()=>chooseView("changes")}>{t("changes")}</button><button class:active={view==="branches"} onclick={()=>chooseView("branches")}>{t("branch")}</button><button class:active={view==="remotes"} onclick={()=>chooseView("remotes")}>{t("remotes")}</button><button class:active={view==="log"} onclick={()=>chooseView("log")}>{t("log")}</button></nav>
    {#if view==="changes"}<div class="changes-layout"><section class="change-list">{#each status.changes??[] as change}<article class:conflicted={change.conflict}><input type="checkbox" checked={selected.has(change.path)} onchange={()=>toggle(change.path)} aria-label={$i18n("git.selectPath",{path:change.path})}/><button onclick={()=>showDiff(change.path,change.staged&&!change.unstaged)}><code>{change.index}{change.worktree}</code><span>{change.path}</span></button><button class="open-file" onclick={()=>onopenfile(change.path)} title={$i18n("workspace.openFile")} aria-label={$i18n("workspace.openFile")}><FileCode2 size={15}/></button></article>{/each}{#if !status.changes?.length}<p>{t("noChanges")}</p>{/if}<div class="stage-actions"><button disabled={!status.changes?.length} onclick={()=>selected=new Set((status.changes??[]).map((item:any)=>item.path))}>{t("selectAll")}</button><button disabled={!selected.size} onclick={()=>operation({type:"stage",paths:checkedPaths()})}>{t("stage")}</button><button disabled={!selected.size} onclick={()=>operation({type:"unstage",paths:checkedPaths()})}>{t("unstage")}</button></div><form onsubmit={(event)=>{event.preventDefault();void commit(false);}}><textarea bind:value={message} maxlength="10000" rows="3" placeholder={t("message")} required></textarea><div><button class="primary" disabled={!message.trim()||!status.staged}>{t("commit")}</button><button type="button" disabled={!message.trim()||!status.staged} onclick={()=>commit(true)}>{t("commitPush")}</button></div></form></section><pre class="diff">{diff||activePath||t("noChanges")}</pre></div>
    {:else if view==="branches"}<section class="branch-view"><form onsubmit={(event)=>{event.preventDefault();void operation({type:"branch-create",branch:branchName,checkout:true});branchName="";}}><input bind:value={branchName} maxlength="200" placeholder={t("createBranch")} required/><button class="primary">{t("createBranch")}</button></form>{#each branches as item}<article class:current={item.name===status.branch}><span><strong>{item.name}{item.merged?` · ${t("merged")}`:""}</strong><small>{item.commit} · {item.upstream??"—"} {item.track??""}</small></span>{#if item.remote&&item.name&&!item.name.endsWith("/HEAD")}<button onclick={()=>operation({type:"branch-switch",branch:item.name.split("/").slice(1).join("/"),track:item.name})}>{t("checkout")}</button>{:else if !item.remote&&item.name!==status.branch}<button onclick={()=>operation({type:"branch-switch",branch:item.name})}>{t("switchBranch")}</button><button class="danger" onclick={()=>confirm($i18n("git.deleteLocalBranchConfirm",{name:item.name}))&&operation({type:"branch-delete",branch:item.name,force:false,confirmDanger:true})}>{$i18n("common.delete")}</button>{/if}</article>{/each}</section>
    {:else if view==="remotes"}<section class="remote-view"><form onsubmit={(event)=>{event.preventDefault();void operation({type:"remote-add",name:remoteName,url:remoteUrl});remoteUrl="";}}><input bind:value={remoteName} maxlength="100" placeholder="origin" required/><input bind:value={remoteUrl} maxlength="2048" inputmode="url" placeholder="https://github.com/owner/repo.git" required/><button class="primary">{t("addRemote")}</button></form>{#each status.remotes??[] as item}<article><span><strong>{item.name}</strong><code>{item.fetchUrl}</code></span><button onclick={()=>{remoteName=item.name;remoteUrl=item.fetchUrl??""}}>{$i18n("common.edit")}</button><button class="danger" onclick={()=>confirm($i18n("git.removeRemoteConfirm",{name:item.name}))&&operation({type:"remote-remove",name:item.name,confirmDanger:true})}>{$i18n("common.delete")}</button></article>{/each}{#if status.remotes?.some((item:any)=>item.name===remoteName)&&remoteUrl}<button onclick={()=>operation({type:"remote-update",name:remoteName,url:remoteUrl})}>{$i18n("common.update")} {remoteName}</button>{/if}</section>
    {:else}<section class="log-view">{#each commits as item}<article><code>{item.shortSha}</code><span><strong>{item.subject}</strong><small>{item.author} · {formatDateTime(item.authoredAt,$locale)}</small></span></article>{/each}</section>{/if}
    <footer><span>{t("lastCommit")}: {status.lastCommit?`${status.lastCommit.shortSha} ${status.lastCommit.subject}`:"—"}</span><span>{t("lastFetch")}: {status.lastFetchAt?formatDateTime(status.lastFetchAt,$locale):"—"}</span></footer>
  {/if}
  {#if notice}<p class="notice">{notice}</p>{/if}
</section>
<style>
  .git-panel{display:grid;gap:.65rem;padding:.7rem;min-height:0;overflow:auto}.git-panel>header,.network,.conflict,.git-panel nav,.summary,.stage-actions,.change-list form div,.git-panel footer{display:flex;align-items:center;gap:.45rem;flex-wrap:wrap}.git-panel>header{justify-content:space-between}.git-panel>header div{display:grid}.git-panel small,.git-panel footer{color:var(--muted)}.summary span{padding:.3rem .48rem;background:var(--bg);border-radius:999px;font-size:.75rem}.summary .danger,.conflicted{color:var(--danger)}.network label{display:flex;align-items:center;gap:.3rem}.git-panel nav{border-bottom:1px solid var(--line)}.git-panel nav button{border:0;border-radius:0}.git-panel nav button.active{border-bottom:2px solid var(--accent)}.changes-layout{display:grid;grid-template-columns:minmax(260px,38%) 1fr;min-height:360px}.change-list{display:grid;align-content:start;gap:.3rem;border-right:1px solid var(--line);padding-right:.5rem}.change-list article{display:grid;grid-template-columns:auto 1fr auto;align-items:center}.change-list article>button:not(.open-file){display:grid;grid-template-columns:2rem 1fr;text-align:left;overflow:hidden}.change-list article .open-file{display:inline-flex;padding:.3rem}.change-list article span{overflow:hidden;text-overflow:ellipsis}.change-list form{display:grid;gap:.4rem;margin-top:.35rem}.change-list textarea{width:100%;resize:vertical}.diff{margin:0;padding:.55rem;overflow:auto;white-space:pre;font:12px/1.5 ui-monospace,SFMono-Regular,monospace}.branch-view,.remote-view,.log-view{display:grid;align-content:start;gap:.4rem}.branch-view form,.remote-view form{display:flex;gap:.4rem}.branch-view article,.remote-view article,.log-view article{display:flex;align-items:center;gap:.5rem;padding:.5rem;border:1px solid var(--line);border-radius:10px}.branch-view article.current{border-color:var(--accent)}.branch-view article span,.remote-view article span,.log-view article span{display:grid;min-width:0;flex:1}.remote-view code{overflow:hidden;text-overflow:ellipsis}.danger{color:var(--danger)}.conflict{padding:.55rem;border:1px solid var(--danger);border-radius:10px}.not-repo{display:grid;place-items:center;gap:.7rem;min-height:280px;text-align:center}.not-repo form{display:grid;grid-template-columns:minmax(220px,2fr) 1fr auto auto;gap:.4rem;align-items:center;width:min(760px,100%)}.not-repo label{display:flex;align-items:center;gap:.25rem}.notice{color:var(--warn);margin:0}.git-panel footer{justify-content:space-between;font-size:.75rem}
  @media(max-width:700px){.changes-layout{grid-template-columns:1fr;grid-template-rows:auto minmax(240px,1fr)}.change-list{border-right:0;border-bottom:1px solid var(--line);padding:0 0 .5rem}.network button,.stage-actions button{min-height:44px}.branch-view form,.remote-view form,.not-repo form{display:grid;grid-template-columns:1fr}.branch-view article,.remote-view article{flex-wrap:wrap}.git-panel footer{display:grid}}
</style>
