<script lang="ts">
  import { ArrowRight, Clipboard, GitCompareArrows, X } from "@lucide/svelte";
  import { t } from "./i18n";
  import ProviderExecutionPicker from "./ProviderExecutionPicker.svelte";
  export let api:(path:string,init?:RequestInit)=>Promise<any>;export let source:any;export let onclose:()=>void;export let oncomplete:(task:any)=>void;
  type ProviderId="codex"|"claude"|"deepseek"|"ollama"|"antigravity"|"grok";
  let hosts:any[]=[],workspaces:any[]=[],targetHostId="",targetWorkspaceId="",targetProvider:ProviderId=source.provider==="codex"?"claude":"codex",targetModel="",targetReasoningEffort="default",targetServiceTier:string|null=null,kind:"continue"|"review"|"review-return"="continue",includePatch=false;
  let purpose=source.title??"",completed=source.result??"",tests="",remaining="",warnings="",lastDecision="",step:1|2|3=1,busy=false,error="",draft:any=null,markdown="",validation:any=null;
  const targetWorkspaces=()=>workspaces.filter(item=>item.hostId===targetHostId&&item.projectId===source.projectId);const hostLabel=(id:string)=>hosts.find(item=>item.id===id)?.displayName??id;
  async function load(){try{const[h,w]=await Promise.all([api("/api/hosts"),api(`/api/workspaces?projectId=${encodeURIComponent(source.projectId)}`)]);hosts=h.hosts??[];workspaces=w.workspaces??[];const other=hosts.find(item=>item.id!==(source.executionHostId??"local")&&item.status==="online")??hosts.find(item=>item.status==="online");targetHostId=other?.id??"";targetWorkspaceId=targetWorkspaces()[0]?.id??"";}catch(e){error=e instanceof Error?e.message:String(e)}}
  async function hostChanged(){targetWorkspaceId=targetWorkspaces()[0]?.id??"";}
  async function createDraft(){busy=true;error="";try{const data=await api("/api/handoffs",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({sourceTaskId:source.id,targetHostId,targetWorkspaceId,targetProvider,targetModel:targetModel||null,targetReasoningEffort:targetReasoningEffort==="default"?null:targetReasoningEffort,targetServiceTier,kind,includePatch,purpose,completed,tests,remaining,warnings,lastDecision})});draft=data.artifact;markdown=data.markdown;step=2;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function validate(){busy=true;error="";try{await api(`/api/handoffs/${draft.id}`,{method:"PATCH",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({markdown})});validation=await api(`/api/handoffs/${draft.id}/validate`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({confirm:true})});step=3;}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function execute(){busy=true;error="";try{const data=await api(`/api/handoffs/${draft.id}/execute`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({confirmNewSession:true,confirmNoAutomaticPatch:true})});oncomplete(data.targetTask);}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function copy(){await navigator.clipboard.writeText(markdown)}
  load();
</script>
<div class="modal-backdrop" role="presentation" onclick={(event)=>event.target===event.currentTarget&&onclose()}><div class="modal handoff" role="dialog" aria-modal="true" aria-labelledby="handoff-title"><header><span><h2 id="handoff-title">{$t("handoff.title")}</h2><small>{$t("handoff.description")}</small></span><button class="icon-button" aria-label={$t("common.close")} onclick={onclose}><X size={20}/></button></header>
  <nav class="steps" aria-label={$t("handoff.steps")}><span class:active={step===1}>{$t("handoff.step.target")}</span><span class:active={step===2}>{$t("handoff.step.review")}</span><span class:active={step===3}>{$t("handoff.step.execute")}</span></nav>
  {#if step===1}<div class="handoff-fields"><fieldset><legend>{$t("handoff.targetHost")}</legend><div class="host-choices">{#each hosts.filter(item=>item.status==="online") as item}<button type="button" class:active={targetHostId===item.id} onclick={()=>{targetHostId=item.id;void hostChanged();}}><strong>{item.displayName}</strong><small>{item.platform} · {$t(`status.${item.status}`)}</small></button>{/each}</div></fieldset><label>{$t("handoff.targetWorkspace")}<select bind:value={targetWorkspaceId}>{#each targetWorkspaces() as item}<option value={item.id}>{item.displayName} · {item.canonicalPath}</option>{/each}</select></label><ProviderExecutionPicker {api} sourceProvider={source.provider} hostId={targetHostId} selectionKey="handoff" bind:provider={targetProvider} bind:model={targetModel} bind:effort={targetReasoningEffort} bind:tier={targetServiceTier}/><label>{$t("handoff.kind")}<select bind:value={kind}><option value="continue">{$t("handoff.kind.continue")}</option><option value="review">{$t("handoff.kind.review")}</option><option value="review-return">{$t("handoff.kind.reviewReturn")}</option></select></label><label>{$t("handoff.purpose")}<textarea bind:value={purpose} rows="2" maxlength="20000"></textarea></label><label>{$t("handoff.completed")}<textarea bind:value={completed} rows="2" maxlength="20000"></textarea></label><label>{$t("handoff.tests")}<textarea bind:value={tests} rows="2" maxlength="20000"></textarea></label><label>{$t("handoff.remaining")}<textarea bind:value={remaining} rows="2" maxlength="20000"></textarea></label><label>{$t("handoff.warnings")}<textarea bind:value={warnings} rows="2" maxlength="20000"></textarea></label><label>{$t("handoff.lastDecision")}<textarea bind:value={lastDecision} rows="2" maxlength="20000"></textarea></label><label class="check"><input type="checkbox" bind:checked={includePatch}/>{$t("handoff.includePatch")}</label><button class="primary" disabled={busy||!targetWorkspaceId||!targetModel} onclick={createDraft}>{$t("handoff.createDocument")} <ArrowRight size={17}/></button></div>
  {:else if step===2}<div class="preview"><div class="preview-heading"><span><strong>{hostLabel(source.executionHostId??"local")} → {hostLabel(targetHostId)}</strong><small>{source.provider} → {targetProvider} · {targetModel}</small></span><button type="button" onclick={copy}><Clipboard size={15}/>{$t("common.copy")}</button></div><textarea bind:value={markdown} rows="22" maxlength="100000" aria-label={$t("handoff.documentContent")}></textarea><div class="footer-actions"><button type="button" onclick={()=>step=1}>{$t("common.back")}</button><button class="primary" disabled={busy} onclick={validate}>{$t("handoff.validate")} <GitCompareArrows size={17}/></button></div></div>
  {:else}<div class="validation" class:blocked={!validation?.ok}><h3>{validation?.ok?$t("handoff.ready"):$t("handoff.blocked")}</h3>{#each validation?.errors??[] as item}<p class="error">{item}</p>{/each}{#each validation?.warnings??[] as item}<p class="warn">{item}</p>{/each}{#if validation?.targetGit}<dl><dt>{$t("handoff.targetCommit")}</dt><dd><code>{validation.targetGit.commit??$t("common.notAvailable")}</code></dd><dt>{$t("handoff.targetStatus")}</dt><dd>{validation.targetGit.dirty?$t("handoff.dirty"):$t("git.clean")}</dd></dl>{/if}<p class="scope">{$t("handoff.scope")}</p><div class="footer-actions"><button type="button" onclick={()=>step=2}>{$t("handoff.backDocument")}</button><button class="primary" disabled={busy||!validation?.ok} onclick={execute}>{busy?$t("handoff.creatingSession"):$t("handoff.execute")}</button></div></div>{/if}
  {#if error}<p class="handoff-error" aria-live="polite">{error}</p>{/if}
</div></div>
<style>
  .handoff{width:min(760px,calc(100vw - 2rem));max-height:min(900px,calc(var(--visual-viewport-height,100dvh) - 1rem));overflow:auto}.handoff header span small{color:var(--muted)}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:.35rem}.steps span{padding:.55rem;text-align:center;border-radius:9px;background:var(--panel);color:var(--muted);font-size:.78rem}.steps span.active{background:var(--accent-soft);color:var(--accent)}.handoff-fields{display:grid;gap:.7rem}.handoff-fields label,.preview{display:grid;gap:.3rem}.handoff fieldset{border:0;padding:0;margin:0}.host-choices{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:.45rem}.host-choices button{display:grid;text-align:left;min-height:58px}.host-choices button.active{border-color:var(--accent);background:var(--accent-soft)}.host-choices small{color:var(--muted)}.check{display:flex!important;align-items:center}.primary{display:flex;align-items:center;justify-content:center;gap:.4rem}.preview-heading,.footer-actions{display:flex;align-items:center;justify-content:space-between;gap:.5rem}.preview-heading span{display:grid}.preview-heading small{color:var(--muted)}.preview textarea{font-family:ui-monospace,monospace;font-size:.78rem}.validation{padding:.8rem;border:1px solid var(--good);border-radius:14px}.validation.blocked{border-color:var(--danger)}.validation dl{display:grid;grid-template-columns:auto 1fr;gap:.35rem}.validation dd{min-width:0;margin:0;overflow:hidden;text-overflow:ellipsis}.error,.handoff-error{color:var(--danger)}.warn{color:var(--warn)}.scope{color:var(--muted)}
  @media(max-width:600px){.handoff{width:100%;height:calc(var(--visual-viewport-height,100dvh) - env(safe-area-inset-top));max-height:none;border-radius:18px 18px 0 0;margin-top:auto;padding-bottom:calc(env(safe-area-inset-bottom) + 1rem)}.host-choices{grid-template-columns:1fr}.footer-actions button{min-height:44px}.steps span{font-size:.7rem;padding:.45rem .2rem}}
</style>
