<script lang="ts">
  import {onMount} from "svelte";
  import {ArrowDown,ArrowUp,CircleAlert,KeyRound,Plus,RefreshCw,Save,Trash2} from "@lucide/svelte";
  import {t} from "./i18n";
  import {MCP_SERVER_ROLES,mcpServerDraftIsValid,mcpServerSavePayload,newMcpServer,normalizeMcpServerSettings,type McpServerDraft,type McpServerRole} from "./mcp-servers";
  export let api:(path:string,init?:RequestInit)=>Promise<any>;
  let servers:McpServerDraft[]=[],updatedAt:string|null=null,loading=false,saving=false,notice="",saved=false;
  const update=(index:number,patch:Partial<McpServerDraft>)=>servers=servers.map((server,i)=>i===index?{...server,...patch}:server);
  const toggleRole=(index:number,role:McpServerRole,checked:boolean)=>update(index,{roles:checked?[...new Set([...servers[index].roles,role])]:servers[index].roles.filter(item=>item!==role)});
  function add(){servers=[...servers,newMcpServer(`mcp-${crypto.randomUUID()}`)];saved=false;}
  function remove(index:number){servers=servers.filter((_,i)=>i!==index);saved=false;}
  function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=servers.length)return;const next=[...servers];[next[index],next[target]]=[next[target],next[index]];servers=next;saved=false;}
  async function load(){loading=true;notice="";try{const result=normalizeMcpServerSettings(await api("/api/system-settings/mcp-servers"));servers=result.settings.servers;updatedAt=result.updatedAt;saved=false;}catch(error){notice=error instanceof Error?error.message:String(error);}finally{loading=false;}}
  async function save(){if(saving||servers.some(server=>!mcpServerDraftIsValid(server))){notice=$t("mcp.validation");return;}saving=true;notice="";try{const result=normalizeMcpServerSettings(await api("/api/system-settings/mcp-servers",{method:"PUT",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(mcpServerSavePayload(servers,updatedAt))}));servers=result.settings.servers;updatedAt=result.updatedAt;saved=true;notice=$t("mcp.saved");}catch(error){saved=false;notice=error instanceof Error?error.message:String(error);}finally{saving=false;}}
  onMount(load);
</script>

<section class="mcp-settings">
  <header><span><h3>{$t("mcp.title")}</h3><small>{$t("mcp.body")}</small></span><div><button type="button" onclick={load} disabled={loading||saving}><RefreshCw size={15} class={loading?"spin":""}/>{$t("common.refresh")}</button><button type="button" onclick={add} disabled={loading||saving}><Plus size={15}/>{$t("mcp.add")}</button></div></header>
  <p class="boundary"><CircleAlert size={17}/><span><strong>{$t("mcp.remoteOnly")}</strong><small>{$t("mcp.remoteOnlyBody")}</small></span></p>
  <p class="grok"><CircleAlert size={16}/><span><strong>{$t("mcp.grokUnsupported")}</strong><small>{$t("mcp.grokUnsupportedBody")}</small></span></p>
  <p class="priority">{$t("mcp.priorityBody")}</p>
  {#if loading&&!servers.length}<p class="mcp-empty">{$t("common.loading")}</p>{/if}
  <div class="server-list">{#each servers as server,index (server.id)}<article>
    <div class="server-head"><label class="toggle"><input type="checkbox" checked={server.enabled} onchange={(event)=>update(index,{enabled:(event.currentTarget as HTMLInputElement).checked})}/><span><strong>{server.name||$t("mcp.unnamed")}</strong><small>{server.enabled?$t("mcp.enabled"):$t("mcp.disabled")}</small></span></label><div class="server-actions"><button type="button" title={$t("mcp.moveUp")} disabled={index===0} onclick={()=>move(index,-1)}><ArrowUp size={16}/></button><button type="button" title={$t("mcp.moveDown")} disabled={index===servers.length-1} onclick={()=>move(index,1)}><ArrowDown size={16}/></button><button class="delete" type="button" title={$t("common.delete")} onclick={()=>remove(index)}><Trash2 size={16}/></button></div></div>
    <div class="fields"><label>{$t("mcp.name")}<input required maxlength="80" value={server.name} oninput={(event)=>update(index,{name:(event.currentTarget as HTMLInputElement).value})} placeholder={$t("mcp.namePlaceholder")}/></label><label>{$t("mcp.url")}<input required type="url" maxlength="2048" value={server.url} oninput={(event)=>update(index,{url:(event.currentTarget as HTMLInputElement).value})} placeholder={$t("mcp.urlPlaceholder")}/></label></div>
    <fieldset><legend>{$t("mcp.roles")}</legend><div class="roles">{#each MCP_SERVER_ROLES as role}<label><input type="checkbox" checked={server.roles.includes(role)} onchange={(event)=>toggleRole(index,role,(event.currentTarget as HTMLInputElement).checked)}/><span>{$t(`mcp.role.${role}`)}</span></label>{/each}</div></fieldset>
    <label class="read-only"><input type="checkbox" checked={server.readOnly} onchange={(event)=>update(index,{readOnly:(event.currentTarget as HTMLInputElement).checked})}/><span><strong>{$t("mcp.readOnly")}</strong><small>{$t("mcp.readOnlyBody")}</small></span></label>
    <div class="secret"><span><KeyRound size={15}/>{$t("mcp.secret")}{#if server.secretConfigured}<em>{$t("mcp.secretConfigured")}{server.secretSource?` · ${server.secretSource}`:""}</em>{/if}</span><input aria-label={$t("mcp.secret")} type="password" autocomplete="new-password" maxlength="8192" disabled={server.clearSecret} value={server.secret} oninput={(event)=>update(index,{secret:(event.currentTarget as HTMLInputElement).value,clearSecret:false})} placeholder={$t(server.secretConfigured?"mcp.secretReplace":"mcp.secretEnter")}/>{#if server.secretConfigured}<label class="clear-secret"><input type="checkbox" checked={server.clearSecret} onchange={(event)=>update(index,{clearSecret:(event.currentTarget as HTMLInputElement).checked,secret:""})}/>{$t("mcp.secretClear")}</label>{/if}<small>{$t("mcp.secretBody")}</small></div>
  </article>{:else}{#if !loading}<p class="mcp-empty">{$t("mcp.empty")}</p>{/if}{/each}</div>
  <div class="save-row"><span class:success={saved} role="status" aria-live="polite">{notice}</span><button class="primary" type="button" onclick={save} disabled={loading||saving||servers.some(server=>!mcpServerDraftIsValid(server))}><Save size={15}/>{$t(saving?"common.saving":"common.save")}</button></div>
</section>

<style>
  .mcp-settings{display:grid;gap:.8rem}.mcp-settings>header{display:flex;align-items:flex-end;justify-content:space-between;gap:.7rem}.mcp-settings h3{margin:0}.mcp-settings header small,.mcp-empty,.secret small,.read-only small,.priority{color:var(--muted)}.mcp-settings header>div,.server-actions{display:flex;gap:.4rem}.mcp-settings button,.secret>span{display:inline-flex;align-items:center;gap:.35rem}.boundary,.grok{display:flex;align-items:flex-start;gap:.5rem;margin:0;padding:.65rem;border:1px solid var(--line);border-radius:10px}.boundary{color:var(--accent)}.grok{color:var(--warn)}.priority{margin:0;font-size:.82rem}.boundary span,.grok span{display:grid;gap:.12rem}.boundary small,.grok small{color:var(--muted)}.server-list{display:grid;gap:.7rem}.mcp-empty{margin:0;padding:.75rem;border:1px dashed var(--line);border-radius:10px;text-align:center}.server-list article{display:grid;gap:.65rem;padding:.8rem;border:1px solid var(--line);border-radius:12px;background:var(--panel)}.server-head{display:flex;align-items:center;justify-content:space-between}.toggle,.read-only{display:flex;align-items:center;gap:.55rem}.toggle span,.read-only span{display:grid}.delete{color:var(--danger)}.fields{display:grid;grid-template-columns:minmax(0,.6fr) minmax(0,1.4fr);gap:.55rem}.fields label,.secret{display:grid;gap:.3rem}fieldset{margin:0;padding:.55rem;border:1px solid var(--line);border-radius:9px}legend{padding:0 .25rem;color:var(--muted);font-size:.8rem}.roles{display:flex;flex-wrap:wrap;gap:.45rem .8rem}.roles label,.clear-secret{display:flex;align-items:center;gap:.3rem}.secret>span{font-weight:600}.secret em{margin-left:auto;color:var(--accent);font-size:.75rem;font-style:normal;font-weight:500}.clear-secret{font-size:.82rem;color:var(--muted)}.save-row{display:flex;align-items:center;justify-content:flex-end;gap:.7rem;position:sticky;bottom:0;padding:.65rem;background:color-mix(in srgb,var(--bg) 92%,transparent);backdrop-filter:blur(8px)}.save-row span{margin-right:auto;color:var(--danger)}.save-row span.success{color:var(--accent)}@media(max-width:720px){.mcp-settings>header{align-items:flex-start}.mcp-settings>header>div{flex-direction:column}.fields{grid-template-columns:1fr}.roles{display:grid;grid-template-columns:1fr 1fr}.save-row{align-items:flex-start}}
</style>
