<script lang="ts">
  import{CircleCheck,CloudUpload,ExternalLink,KeyRound,LoaderCircle,LogOut,RefreshCw,ShieldAlert}from"@lucide/svelte";
  import{onDestroy,onMount}from"svelte";
  import{t}from"./i18n";
  export let api:(path:string,init?:RequestInit)=>Promise<any>;
  let settings={version:1 as const,enabled:false,remoteRoot:"/my-files/Claudex-Workhouse",conflictStrategy:"skip" as const,verifyAfterUpload:true,maxUploadBytes:5*1024*1024*1024},updatedAt:string|null=null,status:any=null,uploads:any[]=[];
  const uploadSizes=[{value:512*1024*1024,label:"512 MiB"},{value:1024*1024*1024,label:"1 GiB"},{value:5*1024*1024*1024,label:"5 GiB"},{value:20*1024*1024*1024,label:"20 GiB"}];
  let loading=false,saving=false,notice="",attempt:any=null,timer:ReturnType<typeof setTimeout>|null=null;
  const stateKey=()=>status?.state==="ready"&&status?.connected?"proton.connected":status?.state==="ready"?"proton.loginRequired":status?.state==="incompatible"?"proton.incompatible":status?.state==="not-installed"?"proton.notInstalled":"proton.unavailable";
  const formatBytes=(value:number)=>value<1024**3?`${(value/1024**2).toFixed(0)} MiB`:`${(value/1024**3).toFixed(1)} GiB`;
  async function load(){loading=true;notice="";try{const[config,current,history]=await Promise.all([api("/api/system-settings/proton-drive"),api("/api/proton-drive/status"),api("/api/proton-drive/uploads?limit=10")]);settings=config.settings;updatedAt=config.updatedAt;status=current;uploads=history.uploads??[];}catch(e){notice=e instanceof Error?e.message:String(e)}finally{loading=false;}}
  async function save(){saving=true;notice="";try{const data=await api("/api/system-settings/proton-drive",{method:"PUT",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({settings,baseUpdatedAt:updatedAt})});settings=data.settings;updatedAt=data.updatedAt;notice=$t("proton.saved");}catch(e){notice=e instanceof Error?e.message:String(e)}finally{saving=false;}}
  function poll(){if(!attempt||attempt.status!=="running")return;timer=setTimeout(async()=>{try{attempt=(await api(`/api/proton-drive/auth/attempts/${encodeURIComponent(attempt.id)}`)).attempt;if(attempt.status==="completed")await load();else poll();}catch(e){notice=e instanceof Error?e.message:String(e)}},2000);}
  async function login(){notice="";try{attempt=(await api("/api/proton-drive/auth/attempts",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:"{}"})).attempt;poll();}catch(e){notice=e instanceof Error?e.message:String(e)}}
  async function logout(){if(!confirm($t("proton.logoutConfirm")))return;try{await api("/api/proton-drive/logout",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:"{}"});await load();}catch(e){notice=e instanceof Error?e.message:String(e)}}
  onMount(()=>void load());onDestroy(()=>{if(timer)clearTimeout(timer)});
</script>
<section class="proton-settings">
  <header><span><h3>{$t("proton.title")}</h3><small>{$t("proton.body")}</small></span><button type="button" disabled={loading} onclick={load}><RefreshCw size={15} class={loading?"spin":""}/>{$t("common.refreshStatus")}</button></header>
  {#if status}<div class="proton-state" class:good={status.connected} class:warn={!status.connected}>{#if status.connected}<CircleCheck size={22}/>{:else}<ShieldAlert size={22}/>{/if}<span><strong>{$t(stateKey() as any)}</strong><small>{status.version??status.detail??$t("proton.cliHint")}</small></span></div>{/if}
  <div class="proton-actions"><button class="primary" type="button" disabled={status?.state!=="ready"||status?.connected||attempt?.status==="running"} onclick={login}><KeyRound size={16}/>{$t("proton.login")}</button><button type="button" disabled={!status?.connected} onclick={logout}><LogOut size={16}/>{$t("proton.logout")}</button><a href="https://proton.me/download/drive/cli" target="_blank" rel="noreferrer">{$t("proton.downloadCli")}<ExternalLink size={14}/></a></div>
  {#if attempt}<div class="login-attempt"><strong>{$t(attempt.status==="running"?"proton.loginRunning":attempt.status==="completed"?"proton.loginCompleted":"proton.loginFailed")}</strong>{#if attempt.loginUrl}<a href={attempt.loginUrl} target="_blank" rel="noreferrer">{$t("proton.openLogin")}<ExternalLink size={14}/></a>{/if}{#if attempt.output}<pre>{attempt.output}</pre>{/if}</div>{/if}
  <form onsubmit={(event)=>{event.preventDefault();void save();}}>
    <label class="toggle"><input type="checkbox" bind:checked={settings.enabled}/><span><strong>{$t("proton.enable")}</strong><small>{$t("proton.enableBody")}</small></span></label>
    <label>{$t("proton.remoteRoot")}<input bind:value={settings.remoteRoot} maxlength="1024" autocomplete="off" spellcheck="false"/></label>
    <label>{$t("proton.maxSize")}<select bind:value={settings.maxUploadBytes}>{#each uploadSizes as item}<option value={item.value}>{item.label}</option>{/each}</select><small>{formatBytes(settings.maxUploadBytes)}</small></label>
    <label class="toggle"><input type="checkbox" bind:checked={settings.verifyAfterUpload}/><span><strong>{$t("proton.verify")}</strong><small>{$t("proton.verifyBody")}</small></span></label>
    <p class="boundary"><CloudUpload size={17}/><span><strong>{$t("proton.manualOnly")}</strong><small>{$t("proton.manualOnlyBody")}</small></span></p>
    <button class="primary" disabled={saving||!settings.remoteRoot.trim()}>{#if saving}<LoaderCircle class="spin" size={15}/>{/if}{$t("common.save")}</button>
  </form>
  <section class="proton-history"><h4>{$t("proton.history")}</h4>{#if uploads.length}{#each uploads as item}<article><span><strong>{item.sourceName}</strong><small>{item.remotePath}</small></span><em class={item.status}>{$t(`proton.status.${item.status}` as any)}</em></article>{/each}{:else}<small>{$t("proton.noUploads")}</small>{/if}</section>
  {#if notice}<p class="notice">{notice}</p>{/if}
</section>
<style>
  .proton-settings{display:grid;gap:1rem}.proton-settings>header,.proton-settings>header>span,.proton-actions,.proton-state,.toggle,.boundary,.proton-history article{display:flex;align-items:center;gap:.65rem}.proton-settings>header{justify-content:space-between}.proton-settings h3,.proton-settings h4{margin:0}.proton-settings small{color:var(--muted)}.proton-state{padding:.8rem;border:1px solid var(--line);border-radius:12px;background:var(--bg)}.proton-state span,.toggle span,.boundary span,.proton-history article span{display:grid;min-width:0}.proton-state.good{color:var(--good)}.proton-state.warn{color:var(--warn)}.proton-actions{flex-wrap:wrap}.proton-actions>*{display:inline-flex;align-items:center;justify-content:center;gap:.35rem;min-height:42px}.proton-actions a{padding:.5rem .75rem;border:1px solid var(--line);border-radius:8px;color:var(--text);text-decoration:none}.login-attempt{display:grid;gap:.45rem}.login-attempt a{display:inline-flex;align-items:center;gap:.35rem}.login-attempt pre{max-height:150px;margin:0;padding:.7rem;overflow:auto;white-space:pre-wrap;background:var(--bg);border:1px solid var(--line);border-radius:8px}.proton-settings form{display:grid;grid-template-columns:1fr 1fr;gap:.8rem;padding:.9rem;border:1px solid var(--line);border-radius:13px;background:var(--bg)}.proton-settings form>label:not(.toggle){display:grid;gap:.3rem}.proton-settings form input:not([type]),.proton-settings form select{width:100%}.toggle,.boundary{grid-column:1/-1}.toggle input{flex:none}.boundary{margin:0;padding:.7rem;border:1px solid color-mix(in srgb,var(--accent) 35%,var(--line));border-radius:10px}.proton-settings form>button{justify-self:end;min-width:120px;display:inline-flex;align-items:center;justify-content:center;gap:.35rem}.proton-history{display:grid;gap:.5rem}.proton-history article{justify-content:space-between;padding:.65rem;border:1px solid var(--line);border-radius:9px}.proton-history article small{overflow-wrap:anywhere}.proton-history em{font-style:normal}.proton-history em.completed{color:var(--good)}.proton-history em.failed,.proton-history em.delivery-uncertain{color:var(--warn)}.notice{margin:0;color:var(--warn)}
  @media(max-width:600px){.proton-settings>header{align-items:stretch;flex-direction:column}.proton-settings form{grid-template-columns:1fr}.toggle,.boundary{grid-column:auto}.proton-actions{display:grid;grid-template-columns:1fr}.proton-settings form>button{width:100%}}
</style>
