import { describe, expect, it } from "vitest";
import { boardAttachSchema, boardCardCreateSchema, CollaborationBoardService } from "./collaboration-board.js";
import type { WorkChain, WorkChainEvent } from "./types.js";
import { LocalTransport } from "./collaboration/provider-transport.js";

function fakeDb(){
  const cards=new Map<string,WorkChain>(),events:WorkChainEvent[]=[];
  const db:any={
    getWorkspace:async(id:string)=>id==="ws"?{id:"ws",projectId:"project",archivedAt:null}:null,getTask:async()=>null,listTasks:async()=>[],getCollaborationSession:async()=>null,listCollaborationSessions:async()=>[],
    getWorkChain:async(id:string)=>cards.get(id)??null,listBoardCards:async()=>[...cards.values()].filter(item=>item.boardVisible&&!item.archivedAt),
    createWorkChain:async(card:WorkChain)=>{cards.set(card.id,card);return card;},
    updateBoardCard:async(next:WorkChain,revision:number)=>{const current=cards.get(next.id);if(!current||current.revision!==revision)return{updated:false,current:current??null};cards.set(next.id,next);return{updated:true,current:next};},
    appendWorkChainEvent:async(event:WorkChainEvent)=>{events.push(event);const card=cards.get(event.chainId);if(card)cards.set(card.id,{...card,lastActivityAt:event.createdAt});return{inserted:true,event};},listWorkChainEvents:async(id:string)=>events.filter(item=>item.chainId===id),attachBoardSession:async()=>({attached:false,reason:"not-found",chain:null})
  };return{db,cards,events};
}

describe("collaboration board service",()=>{
  it("validates provider-aware execution roles and Git branch names",()=>{expect(boardCardCreateSchema.parse({title:"Ship",workspaceId:"ws",roles:{reviewer:{provider:"claude",model:"claude-opus",reasoningEffort:"high",permissionProfile:":read-only",workMode:"plan",automationLevel:"read"}},targetBranch:"feature/board"}).priority).toBe("normal");expect(()=>boardCardCreateSchema.parse({title:"Ship",workspaceId:"ws",roles:{implementer:{provider:"codex",permissionProfile:"workspace-write"}}})).toThrow();expect(()=>boardCardCreateSchema.parse({title:"Ship",workspaceId:"ws",roles:{implementer:{provider:"claude",serviceTier:"priority"}}})).toThrow();expect(()=>boardCardCreateSchema.parse({title:"Ship",workspaceId:"ws",roles:{implementer:{provider:"claude",automationLevel:"confirm"}}})).toThrow();expect(()=>boardCardCreateSchema.parse({title:"Ship",workspaceId:"ws",targetBranch:"bad branch"})).toThrow();expect(()=>boardAttachSchema.parse({revision:1,taskId:"task",collaborationSessionId:crypto.randomUUID()})).toThrow();});
  it("creates a visible persistent card and structured event",async()=>{const {db,events}=fakeDb(),service=new CollaborationBoardService(db);const card=await service.create(boardCardCreateSchema.parse({title:"Ship",workspaceId:"ws"}),{type:"user",id:"owner"});expect(card).toMatchObject({title:"Ship",projectId:"project",boardVisible:true,boardStatus:"queued",revision:1,rootSessionId:null});expect(events).toHaveLength(1);expect(events[0]).toMatchObject({eventType:"card_created",actorType:"user",actorId:"owner"});});
  it("uses revision compare-and-swap and keeps completion separate from archive",async()=>{const {db}=fakeDb(),service=new CollaborationBoardService(db),created=await service.create(boardCardCreateSchema.parse({title:"Ship",workspaceId:"ws"}),{type:"user",id:null});const completed=await service.patch(created.id,{revision:1,boardStatus:"completed"},{type:"user",id:null});expect(completed.completedAt).toBeTruthy();await expect(service.patch(created.id,{revision:1,title:"stale"},{type:"user",id:null})).rejects.toMatchObject({code:"BOARD_REVISION_CONFLICT"});const archived=await service.archive(created.id,completed.revision,{type:"user",id:null});expect(archived.archivedAt).toBeTruthy();expect(archived.boardStatus).toBe("completed");});
  it("rejects a stale action revision before provider execution",async()=>{const {db}=fakeDb(),service=new CollaborationBoardService(db),created=await service.create(boardCardCreateSchema.parse({title:"Ship",workspaceId:"ws"}),{type:"user",id:null});await service.patch(created.id,{revision:1,title:"Changed"},{type:"user",id:null});await expect(service.verifyRevision(created.id,1)).rejects.toMatchObject({code:"BOARD_REVISION_CONFLICT"});expect((await service.verifyRevision(created.id,2)).title).toBe("Changed");});
  it("persists the board chain on collaboration participant provider tasks",async()=>{let stored:any;const db:any={getSystemSetting:async()=>null,upsertTask:async(value:any)=>(stored=value)},provider:any={createTask:async()=>({id:"task",provider:"codex",threadId:"thread",metadata:{}})},transport=new LocalTransport(db,new Map([["codex",provider]]) as any);await transport.start({participant:{id:"participant",provider:"codex",collaborationSessionId:"collaboration",permissionMode:"read",capabilitySnapshot:{}},workspace:{id:"ws",projectId:"project",displayName:"Workspace",canonicalPath:"/workspace"},projectName:"Project",prompt:"Review",title:"Review",workChainId:"chain",collaborationMode:"review"} as any);expect(stored.workChainId).toBe("chain");expect(stored.metadata.collaborationMode).toBe("review");});
});
