// SPDX-License-Identifier: AGPL-3.0-only
// This file is part of Claudex Workhouse.

import crypto from "node:crypto";
import { z } from "zod";
import type { DeckDatabase } from "./db/client.js";
import type { CollaborationBoardAutomation, ProviderId, WorkChain, WorkChainEvent } from "./types.js";

export const boardStatusSchema=z.enum(["queued","in_progress","review","approval","completed"]);
export const boardPrioritySchema=z.enum(["low","normal","high","urgent"]);
const providerSchema=z.enum(["codex","claude","deepseek","ollama","antigravity","grok"]);
const roleSchema=z.object({provider:providerSchema,model:z.string().trim().min(1).max(120).nullable().optional(),reasoningEffort:z.string().trim().min(1).max(30).nullable().optional(),serviceTier:z.enum(["priority"]).nullable().optional(),permissionProfile:z.enum([":read-only",":workspace",":workspace-write",":danger-full-access"]).nullable().optional(),workMode:z.enum(["default","plan"]).optional(),automationLevel:z.enum(["full","auto","confirm","read"]).optional(),googleSearchMode:z.enum(["off","auto","always"]).optional()}).strict().superRefine((role,context)=>{if(role.provider!=="codex"&&role.permissionProfile===":workspace")context.addIssue({code:z.ZodIssueCode.custom,message:"Only Codex supports the workspace permission profile."});if(role.provider==="codex"&&role.permissionProfile===":workspace-write")context.addIssue({code:z.ZodIssueCode.custom,message:"Codex uses the workspace permission profile."});if(role.provider!=="codex"&&role.serviceTier)context.addIssue({code:z.ZodIssueCode.custom,message:"Service tier is available only for Codex."});if(role.provider!=="codex"&&role.automationLevel==="confirm")context.addIssue({code:z.ZodIssueCode.custom,message:"Confirm automation is available only for Codex."});if(role.provider!=="antigravity"&&role.googleSearchMode)context.addIssue({code:z.ZodIssueCode.custom,message:"Google Search mode is available only for Gemini."});});
export const boardRolesSchema=z.object({implementer:roleSchema.optional(),reviewer:roleSchema.optional(),secondaryReviewer:roleSchema.optional()}).strict();
const branchSchema=z.string().trim().max(200).refine(value=>!/[\u0000-\u001f\u007f ~^:?*[\\]/.test(value)&&!value.includes("..")&&!value.endsWith(".")&&!value.endsWith("/"),"Invalid Git branch name.");

const boardCardFields=z.object({projectId:z.string().regex(/^[a-z0-9-]+$/).optional(),title:z.string().trim().min(1).max(100),description:z.string().trim().max(10_000).default(""),boardStatus:boardStatusSchema.default("queued"),priority:boardPrioritySchema.default("normal"),workspaceId:z.string().min(1).max(100).nullable().default(null),targetBranch:branchSchema.nullable().default(null),roles:boardRolesSchema.default({}),sourceTaskId:z.string().min(1).max(200).optional(),sourceCollaborationSessionId:z.string().uuid().optional()}).strict();
export const boardCardCreateSchema=boardCardFields.refine(value=>!(value.sourceTaskId&&value.sourceCollaborationSessionId),"Only one source session may be promoted.");
export const boardCardPatchSchema=boardCardFields.omit({projectId:true,sourceTaskId:true,sourceCollaborationSessionId:true}).partial().extend({revision:z.number().int().positive()}).strict();
export const boardRevisionSchema=z.object({revision:z.number().int().positive()}).strict();
export const boardAutomationStartSchema=boardRevisionSchema.extend({stopAfter:z.enum(["work","review"]).nullable().default(null),fullAccessAcknowledged:z.boolean().default(false),acknowledgementVersion:z.literal(1).optional()}).strict();
export const boardAutomationDecisionSchema=boardRevisionSchema.extend({decision:z.enum(["approve","revise"])}).strict();
export const boardAttachSchema=boardRevisionSchema.extend({taskId:z.string().min(1).max(200).optional(),collaborationSessionId:z.string().uuid().optional()}).strict().refine(value=>Boolean(value.taskId)!==Boolean(value.collaborationSessionId),"Exactly one session identifier is required.");

const activeStatuses=new Set(["pending","queued","starting","running","waiting","waiting-user","cancel-requested","unknown"]);
const error=(message:string,statusCode:number,code:string)=>Object.assign(new Error(message),{statusCode,code});
const now=()=>new Date().toISOString();
export const defaultBoardAutomation=():CollaborationBoardAutomation=>({mode:"manual",state:"idle",stage:null,stopAfter:null,round:0,approvedProviders:[],fullAccessAcknowledged:false,pauseReason:null,lastSessionId:null,startedAt:null});
export const normalizeBoardAutomation=(value:Partial<CollaborationBoardAutomation>|null|undefined):CollaborationBoardAutomation=>({...defaultBoardAutomation(),...(value??{}),approvedProviders:Array.isArray(value?.approvedProviders)?value!.approvedProviders.filter((item):item is ProviderId=>providerSchema.safeParse(item).success):[]});

type Actor={type:string;id:string|null};
type BoardDb=Pick<DeckDatabase,"getWorkChain"|"createWorkChain"|"listBoardCards"|"updateBoardCard"|"appendWorkChainEvent"|"listWorkChainEvents"|"attachBoardSession"|"getWorkspace"|"getTask"|"listTasks"|"getCollaborationSession"|"listCollaborationSessions">;

export class CollaborationBoardService{
  constructor(private db:BoardDb){}

  private async requireCard(id:string,includeHidden=false){const raw=await this.db.getWorkChain(id) as WorkChain|null;if(!raw||(raw.boardVisible!==true&&!includeHidden))throw error("Collaboration board card not found.",404,"BOARD_CARD_NOT_FOUND");return{...raw,automation:normalizeBoardAutomation(raw.automation)};}
  private event(chainId:string,eventType:string,actor:Actor,extra:Partial<WorkChainEvent>={}):WorkChainEvent{return{id:crypto.randomUUID(),chainId,eventType,taskId:null,collaborationSessionId:null,actorType:actor.type,actorId:actor.id,dedupeKey:null,payload:{},createdAt:now(),...extra};}
  private decorateRows(card:WorkChain,tasks:Awaited<ReturnType<BoardDb["listTasks"]>>,collaborations:Awaited<ReturnType<BoardDb["listCollaborationSessions"]>>){
    const sessions=[...tasks.filter(item=>item.workChainId===card.id).map(item=>({id:item.id,kind:"task" as const,title:item.title,provider:item.provider,role:(item.metadata?.boardRole as string|undefined)??null,status:item.status,executionHostId:item.executionHostId??null,permissionProfile:item.permissionProfile??null,createdAt:item.createdAt,updatedAt:item.updatedAt,result:item.result,error:item.error})),...collaborations.filter(item=>item.workChainId===card.id).map(item=>({id:item.id,kind:"collaboration" as const,title:item.title,provider:null,role:(item.metadata?.boardRole as string|undefined)??"review",status:item.status,executionHostId:null,permissionProfile:null,createdAt:item.createdAt,updatedAt:item.updatedAt,result:item.outcome??null,error:null}))];
    return{...card,automation:normalizeBoardAutomation(card.automation),sessions,activeSessionCount:sessions.filter(item=>activeStatuses.has(item.status)).length};
  }
  private async decorate(card:WorkChain){const[tasks,collaborations]=await Promise.all([this.db.listTasks(),this.db.listCollaborationSessions(true)]);return this.decorateRows(card,tasks,collaborations);}
  async list(filters:{projectId?:string;workspaceId?:string;includeArchived?:boolean}={}){const cards=await this.db.listBoardCards(filters);if(!cards.length)return[];const[tasks,collaborations]=await Promise.all([this.db.listTasks(),this.db.listCollaborationSessions(true)]);return cards.map(card=>this.decorateRows(card,tasks,collaborations));}
  async listAutomationCards(){return(await this.db.listBoardCards()).map(card=>({...card,automation:normalizeBoardAutomation(card.automation)}));}
  async detail(id:string){return this.decorate(await this.requireCard(id));}
  async create(input:z.infer<typeof boardCardCreateSchema>,actor:Actor){
    const sourceTask=input.sourceTaskId?await this.db.getTask(input.sourceTaskId):null,sourceCollaboration=input.sourceCollaborationSessionId?await this.db.getCollaborationSession(input.sourceCollaborationSessionId):null,source=sourceTask??sourceCollaboration;if((input.sourceTaskId||input.sourceCollaborationSessionId)&&!source)throw error("Source session not found.",404,"BOARD_SESSION_NOT_FOUND");
    const workspace=input.workspaceId?await this.db.getWorkspace(input.workspaceId):null;if(input.workspaceId&&(!workspace||workspace.archivedAt))throw error("Workspace is unavailable.",409,"BOARD_WORKSPACE_UNAVAILABLE");
    const projectId=input.projectId??workspace?.projectId??source?.projectId;if(!projectId)throw error("projectId, workspaceId, or source session is required.",400,"BOARD_PROJECT_REQUIRED");if(workspace&&workspace.projectId!==projectId)throw error("Workspace does not belong to the selected project.",409,"BOARD_WORKSPACE_PROJECT_MISMATCH");
    if(source&&source.projectId!==projectId)throw error("Source session belongs to another project.",409,"BOARD_SESSION_PROJECT_MISMATCH");
    if(source?.workChainId){const legacy=await this.db.getWorkChain(source.workChainId);if(!legacy)throw error("Source execution chain was not found.",409,"BOARD_CHAIN_NOT_FOUND");if(legacy.boardVisible)throw error("Session is already linked to another collaboration board card.",409,"BOARD_SESSION_ALREADY_LINKED");const timestamp=now(),next={...legacy,title:input.title,description:input.description,boardStatus:input.boardStatus,priority:input.priority,workspaceId:input.workspaceId,targetBranch:input.targetBranch,roles:input.roles,boardVisible:true,lastActivityAt:timestamp,completedAt:input.boardStatus==="completed"?timestamp:null,updatedAt:timestamp,revision:legacy.revision+1},updated=await this.db.updateBoardCard(next,legacy.revision);if(!updated.updated)throw error("Execution chain changed while it was being promoted.",409,"BOARD_REVISION_CONFLICT");await this.db.appendWorkChainEvent(this.event(legacy.id,"chain_promoted",actor,{dedupeKey:`chain:${legacy.id}:promoted`,taskId:sourceTask?.id??null,collaborationSessionId:sourceCollaboration?.id??null,payload:{sourceKind:sourceTask?"task":"collaboration"}}));return this.decorate((await this.db.getWorkChain(legacy.id))??next);}
    const timestamp=now(),id=crypto.randomUUID(),card=await this.db.createWorkChain({id,projectId,title:input.title,rootSessionId:null,activeSessionId:null,createdAt:timestamp,updatedAt:timestamp,archivedAt:null,boardVisible:true,description:input.description,boardStatus:input.boardStatus,priority:input.priority,workspaceId:input.workspaceId,targetBranch:input.targetBranch,roles:input.roles,automation:defaultBoardAutomation(),lastActivityAt:timestamp,completedAt:input.boardStatus==="completed"?timestamp:null,revision:1}) as WorkChain;
    await this.db.appendWorkChainEvent(this.event(id,"card_created",actor,{dedupeKey:`card:${id}:created`,payload:{status:card.boardStatus,priority:card.priority}}));if(source){const attached=await this.db.attachBoardSession({chainId:id,taskId:sourceTask?.id,collaborationSessionId:sourceCollaboration?.id,event:this.event(id,"session_attached",actor,{taskId:sourceTask?.id??null,collaborationSessionId:sourceCollaboration?.id??null,dedupeKey:`${sourceTask?"task":"collaboration"}:${source.id}:attached`,payload:{kind:sourceTask?"task":"collaboration"}})});if(!attached.attached)throw error("Source session could not be linked to the new card.",409,"BOARD_SESSION_ATTACH_FAILED");}return this.decorate((await this.db.getWorkChain(id))??card);
  }
  private async update(id:string,revision:number,patch:Partial<WorkChain>,eventType:string,actor:Actor,payload:Record<string,unknown>={}){
    const current=await this.requireCard(id);if(current.revision!==revision)throw error("Collaboration board card changed in another session. Reload before saving.",409,"BOARD_REVISION_CONFLICT");
    if(patch.workspaceId!==undefined&&patch.workspaceId!==null){const workspace=await this.db.getWorkspace(patch.workspaceId);if(!workspace||workspace.archivedAt||workspace.projectId!==current.projectId)throw error("Workspace is unavailable or belongs to another project.",409,"BOARD_WORKSPACE_PROJECT_MISMATCH");}
    const timestamp=now(),next={...current,...patch,updatedAt:timestamp,completedAt:patch.boardStatus==="completed"?(current.completedAt??timestamp):patch.boardStatus?null:current.completedAt,revision:current.revision+1};const result=await this.db.updateBoardCard(next,current.revision);if(!result.updated)throw error("Collaboration board card changed in another session. Reload before saving.",409,"BOARD_REVISION_CONFLICT");
    await this.db.appendWorkChainEvent(this.event(id,eventType,actor,{dedupeKey:`chain:${id}:${eventType}:r${next.revision}`,payload}));return this.decorate((await this.db.getWorkChain(id))??next);
  }
  patch(id:string,input:z.infer<typeof boardCardPatchSchema>,actor:Actor){const{revision,...patch}=input;return this.update(id,revision,patch,"card_updated",actor,{fields:Object.keys(patch)});}
  archive(id:string,revision:number,actor:Actor){return this.update(id,revision,{archivedAt:now()},"card_archived",actor);}
  reopen(id:string,revision:number,actor:Actor){return this.update(id,revision,{archivedAt:null,boardStatus:"queued",completedAt:null},"card_reopened",actor);}
  setStatus(id:string,revision:number,status:z.infer<typeof boardStatusSchema>,actor:Actor,eventType="status_changed"){return this.update(id,revision,{boardStatus:status},eventType,actor,{status});}
  async events(id:string,limit=200){await this.requireCard(id);return this.db.listWorkChainEvents(id,limit);}
  async verifyRevision(id:string,revision:number){const card=await this.requireCard(id);if(card.revision!==revision)throw error("Collaboration board card changed in another session. Reload before starting a session.",409,"BOARD_REVISION_CONFLICT");return card;}
  async setAutomation(id:string,revision:number,automation:CollaborationBoardAutomation,eventType:string,payload:Record<string,unknown>={}){return this.update(id,revision,{automation:normalizeBoardAutomation(automation)},eventType,{type:"system",id:"board-automation"},payload);}
  async automationEvent(id:string,eventType:string,dedupeKey:string,payload:Record<string,unknown>,session?:{taskId?:string;collaborationSessionId?:string}){await this.requireCard(id);return this.db.appendWorkChainEvent(this.event(id,eventType,{type:"system",id:"board-automation"},{dedupeKey,payload,taskId:session?.taskId??null,collaborationSessionId:session?.collaborationSessionId??null}));}
  async attach(id:string,input:z.infer<typeof boardAttachSchema>,actor:Actor){
    const card=await this.requireCard(id);if(card.revision!==input.revision)throw error("Collaboration board card changed in another session. Reload before saving.",409,"BOARD_REVISION_CONFLICT");
    const task=input.taskId?await this.db.getTask(input.taskId):null,collaboration=input.collaborationSessionId?await this.db.getCollaborationSession(input.collaborationSessionId):null,session=task??collaboration;if(!session)throw error("Session not found.",404,"BOARD_SESSION_NOT_FOUND");
    if(session.projectId!==card.projectId)throw error("Session belongs to another project.",409,"BOARD_SESSION_PROJECT_MISMATCH");if(card.workspaceId&&task?.workspaceId&&task.workspaceId!==card.workspaceId)throw error("Session belongs to another workspace.",409,"BOARD_SESSION_WORKSPACE_MISMATCH");
    if(session.workChainId&&session.workChainId!==id){const existing=await this.db.getWorkChain(session.workChainId);if(existing?.boardVisible)throw error("Session is already linked to another collaboration board card.",409,"BOARD_SESSION_ALREADY_LINKED");throw error("This session belongs to an existing execution chain. Promote that entire chain instead.",409,"BOARD_CHAIN_PROMOTION_REQUIRED");}
    const event=this.event(id,"session_attached",actor,{taskId:task?.id??null,collaborationSessionId:collaboration?.id??null,dedupeKey:`${task?"task":"collaboration"}:${session.id}:attached`,payload:{kind:task?"task":"collaboration"}}),result=await this.db.attachBoardSession({chainId:id,taskId:task?.id,collaborationSessionId:collaboration?.id,event});
    if(!result.attached){if(result.reason==="conflict")throw error("Session is already linked to another collaboration board card.",409,"BOARD_SESSION_ALREADY_LINKED");throw error("Session or card no longer exists.",404,"BOARD_SESSION_NOT_FOUND");}return this.detail(id);
  }
  async recordStarted(id:string,revision:number,kind:"work"|"review"|"revision"|"resume",session:{task?:{id:string};collaboration?:{session:{id:string}}},actor:Actor){
    const attach=boardAttachSchema.parse({revision,...(session.task?{taskId:session.task.id}:{collaborationSessionId:session.collaboration!.session.id})});await this.attach(id,attach,actor);const status=kind==="review"?"review":"in_progress";const current=await this.requireCard(id);return this.setStatus(id,current.revision,status,actor,`${kind}_started`);
  }
}

export type BoardActionRole={provider:ProviderId;model?:string|null;reasoningEffort?:string|null;serviceTier?:string|null;permissionProfile?:string|null;workMode?:"default"|"plan";automationLevel?:"full"|"auto"|"confirm"|"read";googleSearchMode?:"off"|"auto"|"always"};
