// SPDX-License-Identifier: AGPL-3.0-only
// This file is part of Claudex Workhouse.

import type { FastifyInstance, FastifyRequest } from "fastify";
import { z } from "zod";
import { CollaborationBoardService, boardAttachSchema, boardAutomationDecisionSchema, boardAutomationStartSchema, boardCardCreateSchema, boardCardPatchSchema, boardRevisionSchema } from "./collaboration-board.js";

type Idempotent=(request:FastifyRequest,action:string,body:unknown,run:()=>Promise<unknown>)=>Promise<unknown>;
type Action=(request:FastifyRequest,chainId:string,body:Record<string,unknown>)=>Promise<{task?:{id:string};collaboration?:{session:{id:string}}}>;
type Automation={start:(request:FastifyRequest,id:string,body:z.infer<typeof boardAutomationStartSchema>)=>Promise<unknown>;pause:(id:string,revision:number)=>Promise<unknown>;resume:(id:string,revision:number)=>Promise<unknown>;decide:(id:string,revision:number,decision:"approve"|"revise")=>Promise<unknown>};

export function registerCollaborationBoardRoutes(app:FastifyInstance,options:{service:CollaborationBoardService;idempotent:Idempotent;actions?:Partial<Record<"start-work"|"request-review"|"start-revision"|"resume",Action>>;automation?:Automation}){
  const {service,idempotent}=options,params=z.object({id:z.string().uuid()}),actor=(request:FastifyRequest)=>({type:"user",id:typeof (request as any).actor==="string"?(request as any).actor:null});
  app.get("/api/collaboration-board/cards",async request=>{const query=z.object({projectId:z.string().regex(/^[a-z0-9-]+$/).optional(),workspaceId:z.string().min(1).max(100).optional(),archived:z.union([z.literal("1"),z.literal("true")]).optional()}).parse(request.query);return{cards:await service.list({projectId:query.projectId,workspaceId:query.workspaceId,includeArchived:Boolean(query.archived)})};});
  app.post("/api/collaboration-board/cards",async request=>{const body=boardCardCreateSchema.parse(request.body);return idempotent(request,"collaboration-board-create",body,async()=>({card:await service.create(body,actor(request))}));});
  app.get("/api/collaboration-board/cards/:id",async request=>({card:await service.detail(params.parse(request.params).id)}));
  app.patch("/api/collaboration-board/cards/:id",async request=>{const id=params.parse(request.params).id,body=boardCardPatchSchema.parse(request.body);return idempotent(request,`collaboration-board-update:${id}`,body,async()=>({card:await service.patch(id,body,actor(request))}));});
  app.post("/api/collaboration-board/cards/:id/archive",async request=>{const id=params.parse(request.params).id,body=boardRevisionSchema.parse(request.body);return idempotent(request,`collaboration-board-archive:${id}`,body,async()=>({card:await service.archive(id,body.revision,actor(request))}));});
  app.post("/api/collaboration-board/cards/:id/reopen",async request=>{const id=params.parse(request.params).id,body=boardRevisionSchema.parse(request.body);return idempotent(request,`collaboration-board-reopen:${id}`,body,async()=>({card:await service.reopen(id,body.revision,actor(request))}));});
  app.get("/api/collaboration-board/cards/:id/events",async request=>{const id=params.parse(request.params).id,query=z.object({limit:z.coerce.number().int().min(1).max(500).default(200)}).parse(request.query);return{events:await service.events(id,query.limit)};});
  app.post("/api/collaboration-board/cards/:id/sessions/attach",async request=>{const id=params.parse(request.params).id,body=boardAttachSchema.parse(request.body);return idempotent(request,`collaboration-board-attach:${id}`,body,async()=>({card:await service.attach(id,body,actor(request))}));});
  app.post("/api/collaboration-board/cards/:id/automation/start",async request=>{const id=params.parse(request.params).id,body=boardAutomationStartSchema.parse(request.body);if(!options.automation)throw Object.assign(new Error("Collaboration board automation is unavailable."),{statusCode:501,code:"BOARD_AUTOMATION_UNAVAILABLE"});return idempotent(request,`collaboration-board-automation-start:${id}`,body,async()=>({card:await options.automation!.start(request,id,body)}));});
  for(const action of ["pause","resume"] as const)app.post(`/api/collaboration-board/cards/:id/automation/${action}`,async request=>{const id=params.parse(request.params).id,body=boardRevisionSchema.parse(request.body);if(!options.automation)throw Object.assign(new Error("Collaboration board automation is unavailable."),{statusCode:501,code:"BOARD_AUTOMATION_UNAVAILABLE"});return idempotent(request,`collaboration-board-automation-${action}:${id}`,body,async()=>({card:await options.automation![action](id,body.revision)}));});
  app.post("/api/collaboration-board/cards/:id/automation/decision",async request=>{const id=params.parse(request.params).id,body=boardAutomationDecisionSchema.parse(request.body);if(!options.automation)throw Object.assign(new Error("Collaboration board automation is unavailable."),{statusCode:501,code:"BOARD_AUTOMATION_UNAVAILABLE"});return idempotent(request,`collaboration-board-automation-decision:${id}`,body,async()=>({card:await options.automation!.decide(id,body.revision,body.decision)}));});
  for(const action of ["start-work","request-review","start-revision","resume"] as const)app.post(`/api/collaboration-board/cards/:id/actions/${action}`,async request=>{const id=params.parse(request.params).id,body=z.object({revision:z.number().int().positive()}).passthrough().parse(request.body),handler=options.actions?.[action];if(!handler)throw Object.assign(new Error(`Collaboration board action ${action} is unavailable.`),{statusCode:501,code:"BOARD_ACTION_UNAVAILABLE"});return idempotent(request,`collaboration-board-${action}:${id}`,body,async()=>{await service.verifyRevision(id,body.revision);const result=await handler(request,id,body),card=await service.recordStarted(id,body.revision,action==="start-work"?"work":action==="request-review"?"review":action==="start-revision"?"revision":"resume",result,actor(request));return{...result,card};});});
}
