import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { z } from "zod";
import { runCommand, type CommandResult } from "./process.js";
import { sanitizeSensitiveText } from "./sensitive-data.js";

const NAME=/^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/;
const REF=/^(?!.*(?:\.\.|@\{|\\|\s|~|\^|:|\?|\*|\[))(?!\/)(?!.*\/$)(?!.*\.lock$)[A-Za-z0-9][A-Za-z0-9._/-]{0,199}$/;
const MAX_OUTPUT=512*1024;

export type GitChange={path:string;originalPath:string|null;index:string;worktree:string;staged:boolean;unstaged:boolean;untracked:boolean;conflict:boolean};
export type GitRemote={name:string;fetchUrl:string|null;pushUrl:string|null};
export type GitStatus={repository:boolean;root:string|null;branch:string|null;detached:boolean;commit:string|null;remote:string|null;remotes:GitRemote[];upstream:string|null;dirty:boolean;changedFiles:string[];changes:GitChange[];staged:number;unstaged:number;untracked:number;conflicts:number;ahead:number;behind:number;worktree:boolean;operation:"merge"|"rebase"|"cherry-pick"|"revert"|null;lastCommit:{sha:string;shortSha:string;subject:string;author:string;authoredAt:string}|null;lastFetchAt:string|null;error?:string};
export const pullRequestInputSchema=z.object({title:z.string().trim().min(1).max(256),body:z.string().max(65_536),base:z.string().trim().min(1).max(200),draft:z.boolean()}).strict();

const common=z.object({}).passthrough();
export const gitOperationSchema=z.discriminatedUnion("type",[
  common.extend({type:z.literal("clone"),url:z.string().min(1).max(2048),branch:z.string().max(200).optional(),shallow:z.boolean().default(false)}),
  common.extend({type:z.literal("init"),branch:z.string().max(200).default("main")}),
  common.extend({type:z.literal("fetch"),remote:z.string().max(100).default("origin"),all:z.boolean().default(false),prune:z.boolean().default(true),tags:z.boolean().default(false)}),
  common.extend({type:z.literal("pull"),strategy:z.enum(["ff-only","merge","rebase"]).default("ff-only"),remote:z.string().max(100).optional(),branch:z.string().max(200).optional(),autoStash:z.literal(false).default(false)}),
  common.extend({type:z.literal("push"),remote:z.string().max(100).optional(),branch:z.string().max(200).optional(),setUpstream:z.boolean().default(false),force:z.enum(["none","force-with-lease","force"]).default("none"),confirmDanger:z.boolean().default(false)}),
  common.extend({type:z.literal("stage"),paths:z.array(z.string().min(1).max(1000)).min(1).max(500)}),
  common.extend({type:z.literal("unstage"),paths:z.array(z.string().min(1).max(1000)).min(1).max(500)}),
  common.extend({type:z.literal("commit"),message:z.string().trim().min(1).max(10000)}),
  common.extend({type:z.literal("branch-create"),branch:z.string().min(1).max(200),startPoint:z.string().max(300).optional(),checkout:z.boolean().default(true)}),
  common.extend({type:z.literal("branch-switch"),branch:z.string().min(1).max(200),track:z.string().max(300).optional()}),
  common.extend({type:z.literal("branch-delete"),branch:z.string().min(1).max(200),force:z.boolean().default(false),confirmDanger:z.boolean().default(false)}),
  common.extend({type:z.literal("remote-add"),name:z.string().min(1).max(100),url:z.string().min(1).max(2048)}),
  common.extend({type:z.literal("remote-update"),name:z.string().min(1).max(100),url:z.string().min(1).max(2048)}),
  common.extend({type:z.literal("remote-remove"),name:z.string().min(1).max(100),confirmDanger:z.boolean().default(false)}),
  common.extend({type:z.literal("upstream-set"),upstream:z.string().min(1).max(300),confirmDanger:z.boolean().default(false)}),
  common.extend({type:z.literal("continue"),operation:z.enum(["merge","rebase"])}),
  common.extend({type:z.literal("abort"),operation:z.enum(["merge","rebase"]),confirmDanger:z.boolean().default(false)}),
]);
export type GitOperation=z.infer<typeof gitOperationSchema>;

function fail(message:string,statusCode=400,code="GIT_OPERATION_REJECTED"):never{throw Object.assign(new Error(message),{statusCode,code});}
function inside(root:string,target:string){const relative=path.relative(root,target);return relative===""||(!relative.startsWith(`..${path.sep}`)&&relative!==".."&&!path.isAbsolute(relative));}
function validName(value:string,label:string){if(!NAME.test(value))fail(`Invalid ${label}.`);return value;}
function validRef(value:string,label="Git branch"){if(!REF.test(value))fail(`Invalid ${label}.`);return value;}
function redact(value:string){return sanitizeSensitiveText(value).replace(/(https?:\/\/)[^/@\s]+@/gi,"$1[REDACTED]@").replace(/\b(?:gh[opsu]_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,})\b/g,"[REDACTED]");}
function safeError(result:CommandResult){const raw=redact(result.stderr||result.stdout).trim().slice(0,2000);if(/authentication|permission denied|could not read Username|publickey/i.test(raw))return Object.assign(new Error("Git authentication failed on this host."),{statusCode:401,code:"GIT_AUTH_FAILED"});if(result.timedOut)return Object.assign(new Error("Git operation timed out."),{statusCode:504,code:"GIT_TIMEOUT"});return Object.assign(new Error(raw||"Git operation failed."),{statusCode:409,code:"GIT_COMMAND_FAILED"});}
export function validateGitRemoteUrl(raw:string){
  const value=raw.trim();if(!value||/[\0\r\n]/.test(value))fail("Invalid repository URL.");
  if(/^https:\/\//i.test(value)){let parsed:URL;try{parsed=new URL(value);}catch{fail("Invalid HTTPS repository URL.");}if(parsed.protocol!=="https:"||!parsed.hostname)fail("Only HTTPS Git URLs are allowed.");if(parsed.username||parsed.password)fail("Credential-bearing repository URLs are not allowed.",400,"GIT_CREDENTIAL_URL_REJECTED");return value;}
  if(/^ssh:\/\//i.test(value)){let parsed:URL;try{parsed=new URL(value);}catch{fail("Invalid SSH repository URL.");}if(parsed.protocol!=="ssh:"||!parsed.hostname||parsed.password)fail("Invalid SSH repository URL.");return value;}
  if(/^git@[A-Za-z0-9.-]+:[A-Za-z0-9._~/-]+(?:\.git)?$/.test(value))return value;
  fail("Only HTTPS and SSH Git transports are allowed.");
}
function gitEnv(cwd:string){return{...process.env,GIT_TERMINAL_PROMPT:"0",GCM_INTERACTIVE:"Never",GIT_ASKPASS:process.platform==="win32"?"":"/bin/false",GIT_EDITOR:"true",GIT_SEQUENCE_EDITOR:"true",GIT_LFS_SKIP_SMUDGE:"1",GIT_CEILING_DIRECTORIES:path.dirname(cwd)};}
async function command(cwd:string,args:string[],timeoutMs=30_000,outputLimit=MAX_OUTPUT){const result=await runCommand("git",args,{cwd,timeoutMs,outputLimit,env:gitEnv(cwd)});if(result.exitCode!==0)throw safeError(result);return result;}
async function optional(cwd:string,args:string[],timeoutMs=10_000){return runCommand("git",args,{cwd,timeoutMs,outputLimit:MAX_OUTPUT,env:gitEnv(cwd)}).catch(()=>null);}
export async function cloneGitRepository(baseDirectory:string,targetDirectory:string,input:{url:string;branch?:string;shallow?:boolean;existingEmptyDirectory?:boolean}){const base=fs.realpathSync(baseDirectory),url=validateGitRemoteUrl(input.url),branch=input.branch?.trim(),target=path.resolve(targetDirectory);if(!inside(base,target))fail("Clone destination escaped the Workspace root.",403,"GIT_WORKSPACE_ESCAPE");if(branch)validRef(branch);if(input.existingEmptyDirectory){if(!fs.existsSync(target)||!fs.statSync(target).isDirectory()||fs.readdirSync(target).length)fail("Clone into the current Workspace requires an empty directory.",409,"GIT_CLONE_DESTINATION_NOT_EMPTY");}else if(fs.existsSync(target))fail("Clone destination already exists.",409,"GIT_CLONE_DESTINATION_NOT_EMPTY");const destination=target===base?".":target;await command(base,["-c","protocol.file.allow=never","-c","protocol.ext.allow=never","-c","submodule.recurse=false","-c","init.templateDir=","clone","--no-checkout","--no-recurse-submodules",...(input.shallow?["--depth","1"]:[]),...(branch?["--branch",branch]:[]),"--",url,destination],10*60_000);const canonicalTarget=fs.realpathSync(target),tree=await command(canonicalTarget,["ls-tree","-r","--name-only","HEAD"],30_000,2*1024*1024),attributeFiles=tree.stdout.split("\n").filter(item=>/(^|\/)\.gitattributes$/.test(item)).slice(0,100),filters=new Set<string>();for(const file of attributeFiles){const content=await optional(canonicalTarget,["show",`HEAD:${file}`]);for(const match of (content?.stdout??"").matchAll(/(?:^|\s)filter=([A-Za-z0-9._-]+)/gm))filters.add(match[1]!);}const filterArgs=[...filters].flatMap(name=>["-c",`filter.${name}.smudge=cat`,"-c",`filter.${name}.process=`,"-c",`filter.${name}.required=false`]);await command(canonicalTarget,[...filterArgs,"checkout","--force"],5*60_000);return{status:await gitStatus(canonicalTarget),suppressedFilters:[...filters]};}
function parseChanges(raw:string):GitChange[]{const values=raw.split("\0").filter(Boolean),out:GitChange[]=[];for(let index=0;index<values.length;index++){const line=values[index]!;if(line.length<3)continue;const x=line[0]??" ",y=line[1]??" ";let file=line.slice(3),originalPath:null|string=null;if((x==="R"||x==="C")&&values[index+1]){originalPath=values[++index]!;}const conflict=x==="U"||y==="U"||(x==="A"&&y==="A")||(x==="D"&&y==="D");out.push({path:file,originalPath,index:x,worktree:y,staged:x!==" "&&x!=="?",unstaged:y!==" ",untracked:x==="?",conflict});}return out.slice(0,1000);}
async function repoContext(cwd:string,required=true){const canonical=fs.realpathSync(cwd),probe=await optional(canonical,["rev-parse","--show-toplevel"]);if(!probe||probe.exitCode!==0){if(required)fail("This Workspace is not a Git repository.",409,"GIT_NOT_REPOSITORY");return{canonical,root:null};}const root=fs.realpathSync(probe.stdout.trim());if(!inside(canonical,root)&&root!==canonical)fail("The repository root is outside the canonical Workspace.",403,"GIT_WORKSPACE_ESCAPE");return{canonical,root};}
function operationState(gitDir:string){if(fs.existsSync(path.join(gitDir,"MERGE_HEAD")))return"merge" as const;if(fs.existsSync(path.join(gitDir,"rebase-merge"))||fs.existsSync(path.join(gitDir,"rebase-apply")))return"rebase" as const;if(fs.existsSync(path.join(gitDir,"CHERRY_PICK_HEAD")))return"cherry-pick" as const;if(fs.existsSync(path.join(gitDir,"REVERT_HEAD")))return"revert" as const;return null;}
function githubSlug(value:string|null|undefined){if(!value)return null;const match=/github\.com(?::|\/)([^/\s:]+)\/([^/\s]+?)(?:\.git)?$/.exec(value);return match?`${match[1]}/${match[2]}`:null;}
async function githubBranchProtected(cwd:string,status:GitStatus,remoteName:string,branch:string){const remote=status.remotes.find(item=>item.name===remoteName),slug=githubSlug(remote?.pushUrl??remote?.fetchUrl);if(!slug)return false;const result=await runCommand("gh",["api",`repos/${slug}/branches/${encodeURIComponent(branch)}`,"--jq",".protected"],{cwd,timeoutMs:15_000,outputLimit:64*1024,env:{...process.env,GH_PROMPT_DISABLED:"1"}}).catch(()=>null);return result?.exitCode===0&&result.stdout.trim()==="true";}
export async function gitStatus(cwd:string):Promise<GitStatus>{
  const context=await repoContext(cwd,false);if(!context.root)return{repository:false,root:null,branch:null,detached:false,commit:null,remote:null,remotes:[],upstream:null,dirty:false,changedFiles:[],changes:[],staged:0,unstaged:0,untracked:0,conflicts:0,ahead:0,behind:0,worktree:false,operation:null,lastCommit:null,lastFetchAt:null};
  const root=context.root,[branch,commit,status,remoteRows,upstream,divergence,common,gitDir,lastCommit]=await Promise.all([
    optional(root,["branch","--show-current"]),optional(root,["rev-parse","HEAD"]),command(root,["status","--porcelain=v1","-z","--untracked-files=all"]),optional(root,["remote","-v"]),optional(root,["rev-parse","--abbrev-ref","--symbolic-full-name","@{upstream}"]),optional(root,["rev-list","--left-right","--count","HEAD...@{upstream}"]),optional(root,["rev-parse","--git-common-dir"]),command(root,["rev-parse","--git-dir"]),optional(root,["log","-1","--format=%H%x00%h%x00%s%x00%an%x00%aI"])
  ]);
  const changes=parseChanges(status.stdout),remotes=new Map<string,GitRemote>();for(const line of (remoteRows?.stdout??"").split("\n")){const match=/^(\S+)\s+(\S+)\s+\((fetch|push)\)$/.exec(line.trim());if(!match)continue;const item=remotes.get(match[1]!)??{name:match[1]!,fetchUrl:null,pushUrl:null};if(match[3]==="fetch")item.fetchUrl=redact(match[2]!);else item.pushUrl=redact(match[2]!);remotes.set(item.name,item);}
  const counts=divergence?.exitCode===0?divergence.stdout.trim().split(/\s+/).map(Number):[0,0],gitPath=path.resolve(root,gitDir.stdout.trim()),fetchHead=path.join(gitPath,"FETCH_HEAD");let lastFetchAt:null|string=null;try{lastFetchAt=fs.statSync(fetchHead).mtime.toISOString();}catch{}
  const log=(lastCommit?.exitCode===0?lastCommit.stdout.trim().split("\0"):[]);return{repository:true,root,branch:branch?.stdout.trim()||null,detached:!(branch?.stdout.trim()),commit:commit?.exitCode===0?commit.stdout.trim():null,remote:remotes.get("origin")?.fetchUrl??[...remotes.values()][0]?.fetchUrl??null,remotes:[...remotes.values()],upstream:upstream?.exitCode===0?upstream.stdout.trim():null,dirty:changes.length>0,changedFiles:changes.map(item=>item.path),changes,staged:changes.filter(item=>item.staged).length,unstaged:changes.filter(item=>item.unstaged&&!item.untracked).length,untracked:changes.filter(item=>item.untracked).length,conflicts:changes.filter(item=>item.conflict).length,ahead:counts[0]||0,behind:counts[1]||0,worktree:Boolean(common?.exitCode===0&&common.stdout.trim()!==".git"),operation:operationState(gitPath),lastCommit:log.length>=5?{sha:log[0]!,shortSha:log[1]!,subject:log[2]!,author:log[3]!,authoredAt:log[4]!}:null,lastFetchAt};
}
function safePath(root:string,value:string){if(path.isAbsolute(value)||value.includes("\0"))fail("Invalid Git file path.");const target=path.resolve(root,value);if(!inside(root,target))fail("Git file path escaped the Workspace.",403,"GIT_WORKSPACE_ESCAPE");return path.relative(root,target)||".";}
export async function gitDiff(cwd:string,input:{path?:string;staged?:boolean;head?:boolean}={}){const {root}=await repoContext(cwd);const relative=input.path?safePath(root!,input.path):null,args=["diff","--no-ext-diff","--no-color",...(input.head?["HEAD"]:input.staged?["--cached"]:[])];if(relative)args.push("--",relative);let result;try{result=await command(root!,args,15_000,MAX_OUTPUT);}catch(error){if(!input.head)throw error;result=await command(root!,args.filter(item=>item!=="HEAD"),15_000,MAX_OUTPUT);}if(relative&&!input.staged&&!result.stdout){const status=await gitStatus(root!),change=status.changes.find(item=>item.path===relative);if(change?.untracked){const untracked=await runCommand("git",["diff","--no-index","--no-ext-diff","--no-color","--",os.devNull,relative],{cwd:root!,timeoutMs:15_000,outputLimit:MAX_OUTPUT,env:gitEnv(root!)});if(untracked.exitCode===0||untracked.exitCode===1)result=untracked;}}return{diff:result.stdout,limited:result.overflow};}
export async function gitLog(cwd:string,limit=50){const {root}=await repoContext(cwd),result=await optional(root!,["log",`-${Math.min(Math.max(limit,1),200)}`,"--format=%H%x00%h%x00%s%x00%an%x00%aI%x00%D"]);return{commits:(result?.exitCode===0?result.stdout:"").split("\n").filter(Boolean).map(line=>{const [sha,shortSha,subject,author,authoredAt,refs]=line.split("\0");return{sha,shortSha,subject,author,authoredAt,refs};})};}
export async function gitBranches(cwd:string){const {root}=await repoContext(cwd);const [result,mergedResult]=await Promise.all([command(root!,["for-each-ref","--format=%(refname)%00%(refname:short)%00%(objectname:short)%00%(upstream:short)%00%(upstream:track)%00%(committerdate:iso-strict)%00%(subject)","refs/heads","refs/remotes"],15_000),optional(root!,["branch","--merged","--format=%(refname:short)"])]),merged=new Set((mergedResult?.stdout??"").split("\n").filter(Boolean));return{branches:result.stdout.split("\n").filter(Boolean).map(line=>{const [ref,name,commit,upstream,track,committedAt,subject]=line.split("\0");return{ref,name,commit,upstream:upstream||null,track:track||null,committedAt,subject,remote:ref?.startsWith("refs/remotes/")??false,merged:merged.has(name!)};})};}
export async function githubPullRequestPreview(cwd:string){
  const {root}=await repoContext(cwd),status=await gitStatus(root!);
  if(status.detached||!status.branch)fail("Pull requests require a named current branch.",409,"PR_DETACHED_HEAD");
  const remoteName=status.upstream?.split("/")[0]??(status.remotes.some(item=>item.name==="origin")?"origin":status.remotes[0]?.name),remote=status.remotes.find(item=>item.name===remoteName),repository=githubSlug(remote?.pushUrl??remote?.fetchUrl);
  if(!remoteName||!repository)fail("The current branch needs a GitHub remote.",409,"PR_GITHUB_REMOTE_REQUIRED");
  const auth=await runCommand("gh",["auth","status","--hostname","github.com"],{cwd:root!,timeoutMs:15_000,outputLimit:64*1024,env:{...process.env,GH_PROMPT_DISABLED:"1"}}).catch(()=>null);
  if(!auth||auth.exitCode!==0)fail("GitHub CLI is not authenticated on this execution host.",401,"PR_GITHUB_AUTH_REQUIRED");
  const baseResult=await runCommand("gh",["repo","view",repository,"--json","defaultBranchRef","--jq",".defaultBranchRef.name"],{cwd:root!,timeoutMs:20_000,outputLimit:64*1024,env:{...process.env,GH_PROMPT_DISABLED:"1"}}),base=baseResult.exitCode===0?baseResult.stdout.trim():null;
  if(!base)throw safeError(baseResult);
  const existing=await runCommand("gh",["pr","list","--repo",repository,"--head",status.branch,"--state","open","--limit","1","--json","url","--jq",".[0].url // \"\""],{cwd:root!,timeoutMs:15_000,outputLimit:64*1024,env:{...process.env,GH_PROMPT_DISABLED:"1"}}).catch(()=>null),existingUrl=existing?.exitCode===0&&/^https:\/\/github\.com\//.test(existing.stdout.trim())?existing.stdout.trim():null;
  const pushed=Boolean(status.upstream)&&status.ahead===0;
  return{repository,remote:remoteName,branch:status.branch,base,upstream:status.upstream,pushed,ahead:status.ahead,behind:status.behind,dirty:status.dirty,changedFiles:status.changedFiles,existingUrl,eligible:!existingUrl&&pushed};
}
export async function createGithubPullRequest(cwd:string,input:{title:string;body:string;base:string;draft:boolean}){
  const parsed=pullRequestInputSchema.parse(input),{root}=await repoContext(cwd),preview=await githubPullRequestPreview(root!);
  if(preview.existingUrl)return{url:preview.existingUrl,reused:true,preview};
  if(!preview.eligible)fail("Push the current named branch and resolve PR preflight warnings before creating a pull request.",409,"PR_PREFLIGHT_REQUIRED");
  validRef(parsed.base,"Git base branch");
  if(parsed.base===preview.branch)fail("The pull request base must differ from the current branch.",409,"PR_BASE_EQUALS_HEAD");
  const baseProbe=await runCommand("gh",["api",`repos/${preview.repository}/branches/${encodeURIComponent(parsed.base)}`,"--silent"],{cwd:root!,timeoutMs:20_000,outputLimit:64*1024,env:{...process.env,GH_PROMPT_DISABLED:"1"}});
  if(baseProbe.exitCode!==0)fail("The selected GitHub base branch was not found.",409,"PR_BASE_NOT_FOUND");
  const result=await runCommand("gh",["pr","create","--repo",preview.repository,"--base",parsed.base,"--head",preview.branch,"--title",parsed.title,"--body",parsed.body,...(parsed.draft?["--draft"]:[])],{cwd:root!,timeoutMs:60_000,outputLimit:128*1024,env:{...process.env,GH_PROMPT_DISABLED:"1"}});
  if(result.exitCode!==0)throw safeError(result);
  const url=result.stdout.split(/\s+/).find(value=>/^https:\/\/github\.com\/[^/]+\/[^/]+\/pull\/\d+$/.test(value));
  if(!url)fail("GitHub CLI did not return a verifiable pull request URL.",502,"PR_URL_MISSING");
  return{url,reused:false,preview};
}
export async function executeGitOperation(cwd:string,raw:unknown){const operation=gitOperationSchema.parse(raw);if(operation.type==="clone"){const result=await cloneGitRepository(cwd,cwd,{url:operation.url,branch:operation.branch,shallow:operation.shallow,existingEmptyDirectory:true});return{ok:true,...result};}if(operation.type==="init"){const canonical=fs.realpathSync(cwd);validRef(operation.branch);await command(canonical,["init","-b",operation.branch]);return{ok:true,status:await gitStatus(canonical)};}const {root}=await repoContext(cwd);const before=await gitStatus(root!);let args:string[]=[];let timeout=60_000,remoteProbe:{defaultBranch:string|null}|null=null;
  switch(operation.type){
    case"fetch":args=["fetch",...(operation.all?["--all"]:[validName(operation.remote,"remote name")]),...(operation.prune?["--prune"]:[]),...(operation.tags?["--tags"]:[])];timeout=5*60_000;break;
    case"pull":if(before.conflicts)fail("Resolve the current conflict before pulling.",409,"GIT_CONFLICT");if(before.detached)fail("Pull is unavailable in detached HEAD state.",409);if(before.dirty)fail("Commit or stash local changes before pulling.",409,"GIT_DIRTY_WORKTREE");if(!before.upstream&&!operation.remote)fail("Set an upstream branch before pulling.",409,"GIT_NO_UPSTREAM");args=["pull",operation.strategy==="ff-only"?"--ff-only":operation.strategy==="rebase"?"--rebase":"--no-rebase",...(operation.remote?[validName(operation.remote,"remote name"),validRef(operation.branch??before.branch??"")]:[])];timeout=5*60_000;break;
    case"push":{if(operation.force!=="none"&&!operation.confirmDanger)fail("Force push requires explicit destructive-operation confirmation.",409,"GIT_DANGER_CONFIRMATION_REQUIRED");if(operation.setUpstream&&(!operation.remote||!operation.branch))fail("Publishing a branch requires a remote and branch.");if(operation.setUpstream&&!operation.confirmDanger)fail("Changing upstream requires explicit confirmation.",409,"GIT_DANGER_CONFIRMATION_REQUIRED");const remoteName=operation.remote??before.upstream?.split("/")[0]??"origin",branch=operation.branch??before.branch;if(branch&&await githubBranchProtected(root!,before,remoteName,branch)&&!operation.confirmDanger)fail("A protected branch push requires explicit confirmation.",409,"GIT_DANGER_CONFIRMATION_REQUIRED");args=["push",...(operation.force==="force"?["--force"]:operation.force==="force-with-lease"?["--force-with-lease"]:[]),...(operation.setUpstream?["--set-upstream"]:[]),...(operation.remote?[validName(operation.remote,"remote name")]:[]),...(operation.branch?[validRef(operation.branch)]:[])];timeout=5*60_000;break;}
    case"stage":args=["add","--",...operation.paths.map(item=>safePath(root!,item))];break;
    case"unstage":args=["restore","--staged","--",...operation.paths.map(item=>safePath(root!,item))];break;
    case"commit":if(before.conflicts)fail("Conflict files cannot be committed.",409,"GIT_CONFLICT");if(!before.staged)fail("No staged changes to commit.",409,"GIT_EMPTY_COMMIT");args=["commit","-m",operation.message];break;
    case"branch-create":validRef(operation.branch);if(operation.startPoint)validRef(operation.startPoint,"Git start point");args=operation.checkout?["switch","-c",operation.branch,...(operation.startPoint?[operation.startPoint]:[])]:["branch",operation.branch,...(operation.startPoint?[operation.startPoint]:[])];break;
    case"branch-switch":if(before.conflicts)fail("Resolve the current conflict before switching branches.",409,"GIT_CONFLICT");validRef(operation.branch);if(operation.track)validRef(operation.track,"remote branch");args=operation.track?["switch","--track","-c",operation.branch,operation.track]:["switch",operation.branch];break;
    case"branch-delete":if(!operation.confirmDanger)fail("Branch deletion requires explicit destructive-operation confirmation.",409,"GIT_DANGER_CONFIRMATION_REQUIRED");validRef(operation.branch);if(operation.branch===before.branch)fail("The current branch cannot be deleted.",409);args=["branch",operation.force?"-D":"-d",operation.branch];break;
    case"remote-add":{const url=validateGitRemoteUrl(operation.url),probe=await command(root!,["ls-remote","--symref",url,"HEAD"],60_000,128*1024),match=/^ref:\s+refs\/heads\/(\S+)\s+HEAD$/m.exec(probe.stdout);remoteProbe={defaultBranch:match?.[1]??null};args=["remote","add",validName(operation.name,"remote name"),url];break;}
    case"remote-update":{const url=validateGitRemoteUrl(operation.url),probe=await command(root!,["ls-remote","--symref",url,"HEAD"],60_000,128*1024),match=/^ref:\s+refs\/heads\/(\S+)\s+HEAD$/m.exec(probe.stdout);remoteProbe={defaultBranch:match?.[1]??null};args=["remote","set-url",validName(operation.name,"remote name"),url];break;}
    case"remote-remove":if(!operation.confirmDanger)fail("Remote removal requires explicit confirmation.",409,"GIT_DANGER_CONFIRMATION_REQUIRED");args=["remote","remove",validName(operation.name,"remote name")];break;
    case"upstream-set":if(!operation.confirmDanger)fail("Changing upstream requires explicit confirmation.",409,"GIT_DANGER_CONFIRMATION_REQUIRED");args=["branch","--set-upstream-to",validRef(operation.upstream,"upstream")];break;
    case"continue":if(before.operation!==operation.operation)fail(`No ${operation.operation} operation is active.`,409);args=operation.operation==="merge"?["commit","--no-edit"]:["rebase","--continue"];break;
    case"abort":if(!operation.confirmDanger)fail("Aborting the Git operation requires explicit confirmation.",409,"GIT_DANGER_CONFIRMATION_REQUIRED");if(before.operation!==operation.operation)fail(`No ${operation.operation} operation is active.`,409);args=[operation.operation,"--abort"];break;
  }
  const result=await command(root!,args,timeout);return{ok:true,stdout:redact(result.stdout).slice(0,MAX_OUTPUT),stderr:redact(result.stderr).slice(0,MAX_OUTPUT),...(remoteProbe?{remoteProbe}:{}),status:await gitStatus(root!)};
}
export async function gitHostStatus(cwd=process.cwd()){const [git,gh,helper,name,email,ssh]=await Promise.all([optional(cwd,["--version"]),runCommand("gh",["--version"],{cwd,timeoutMs:10_000,outputLimit:64*1024,env:{...process.env,GH_PROMPT_DISABLED:"1"}}).catch(()=>null),optional(cwd,["config","--global","--get","credential.helper"]),optional(cwd,["config","--global","--get","user.name"]),optional(cwd,["config","--global","--get","user.email"]),runCommand("ssh-add",["-l"],{cwd,timeoutMs:10_000,outputLimit:64*1024}).catch(()=>null)]);let github:{connected:boolean;username:string|null;name:string|null}={connected:false,username:null,name:null};if(gh?.exitCode===0){const user=await runCommand("gh",["api","user","--jq","{login: .login, name: .name}"],{cwd,timeoutMs:15_000,outputLimit:64*1024,env:{...process.env,GH_PROMPT_DISABLED:"1"}}).catch(()=>null);if(user?.exitCode===0)try{const parsed=JSON.parse(user.stdout);github={connected:true,username:typeof parsed.login==="string"?parsed.login:null,name:typeof parsed.name==="string"?parsed.name:null};}catch{}}
  return{host:os.hostname(),git:{installed:git?.exitCode===0,version:git?.exitCode===0?git.stdout.trim():null},githubCli:{installed:gh?.exitCode===0,version:gh?.exitCode===0?gh.stdout.split("\n")[0]?.trim()??null:null},github,credentialHelper:helper?.exitCode===0?redact(helper.stdout.trim()):null,ssh:{agentAvailable:Boolean(process.env.SSH_AUTH_SOCK),authenticated:ssh?.exitCode===0,keyCount:ssh?.exitCode===0?ssh.stdout.split("\n").filter(Boolean).length:0},commitIdentity:{name:name?.exitCode===0?name.stdout.trim():null,email:email?.exitCode===0?email.stdout.trim():null}};}
export async function setGitIdentity(cwd:string,input:{name:string;email:string}){if(!input.name.trim()||input.name.length>200||/[\r\n\0]/.test(input.name))fail("Invalid Git user name.");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(input.email)||input.email.length>320)fail("Invalid Git email.");await command(cwd,["config","--global","user.name",input.name.trim()]);await command(cwd,["config","--global","user.email",input.email.trim()]);return gitHostStatus(cwd);}
export async function listGitHubRepositories(cwd:string,input:{limit?:number;visibility?:"all"|"public"|"private";owner?:string;search?:string}={}){const limit=Math.min(Math.max(input.limit??100,1),200),owner=input.owner?.trim(),args=["repo","list",...(owner?[owner]:[]),"--limit",String(limit),"--json","name,nameWithOwner,isPrivate,isArchived,defaultBranchRef,updatedAt,url,sshUrl"];const result=await runCommand("gh",args,{cwd,timeoutMs:30_000,outputLimit:MAX_OUTPUT,env:{...process.env,GH_PROMPT_DISABLED:"1"}}).catch(()=>null);if(!result||result.exitCode!==0)fail("GitHub CLI is not authenticated on this host.",401,"GITHUB_NOT_CONNECTED");let rows:any[];try{rows=JSON.parse(result.stdout);}catch{fail("GitHub repository response was invalid.",502);}const search=input.search?.trim().toLowerCase();return{repositories:rows.filter(item=>!item.isArchived&&(input.visibility==="private"?item.isPrivate:input.visibility==="public"?!item.isPrivate:true)&&(!search||String(item.nameWithOwner).toLowerCase().includes(search))).map(item=>({name:item.name,nameWithOwner:item.nameWithOwner,private:Boolean(item.isPrivate),defaultBranch:item.defaultBranchRef?.name??null,updatedAt:item.updatedAt,httpsUrl:item.url?`${item.url}.git`:null,sshUrl:item.sshUrl}))};}
