import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import {spawnSync} from "node:child_process";
import type {DeckDatabase} from "./db/client.js";
import{sqliteMaintenanceInvocation}from"./db/sqlite-platform.js";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const LOOSE_BACKUP=/(?:\.bak|\.backup)(?:[._-].*)?$/i;
export type SnapshotState="ready"|"trashing"|"trashed"|"untrashing"|"purging"|"purged"|"error";
export type SnapshotRecord={id:string;formatVersion:number;logicalKey:string|null;kind:string;origin:string;state:SnapshotState;relativePath:string;createdAt:string;updatedAt:string;sizeBytes:number;fileCount:number;verification:string;pinned:boolean;protectedReason:string|null;trashedAt:string|null;purgeAfter:string|null;lastError:string|null;manifestDigest:string|null};
export type SnapshotManifest={formatVersion:1;id:string;logicalKey:string|null;kind:"database"|"legacy";origin:string;source?:string;createdAt:string;verification:"verified"|"unverified";database?:string;quickCheck?:"ok";files?:Record<string,string>};

function httpError(message:string,statusCode=409,code="SNAPSHOT_CONFLICT"){return Object.assign(new Error(message),{statusCode,code});}
function inside(root:string,target:string){const relative=path.relative(root,target);return relative===""||(!relative.startsWith(`..${path.sep}`)&&relative!==".."&&!path.isAbsolute(relative));}
function sha256(file:string){return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");}
function syncDirectory(directory:string){try{const fd=fs.openSync(directory,"r");try{fs.fsyncSync(fd);}finally{fs.closeSync(fd);}}catch{/* best effort on filesystems that reject directory fsync */}}
function ensureLayout(snapshotDir:string){fs.mkdirSync(snapshotDir,{recursive:true,mode:0o700});fs.chmodSync(snapshotDir,0o700);for(const name of ["objects","trash",".staging"]){const directory=path.join(snapshotDir,name);fs.mkdirSync(directory,{recursive:true,mode:0o700});fs.chmodSync(directory,0o700);}return fs.realpathSync(snapshotDir);}
function processAlive(pid:unknown){if(!Number.isInteger(pid)||Number(pid)<=0)return false;try{process.kill(Number(pid),0);return true;}catch(error){return (error as NodeJS.ErrnoException).code!=="ESRCH";}}
function acquireLease(snapshotDir:string){ensureLayout(snapshotDir);const lock=path.join(snapshotDir,".lock");for(let attempt=0;attempt<2;attempt++){try{const fd=fs.openSync(lock,"wx",0o600);fs.fchmodSync(fd,0o600);fs.writeFileSync(fd,JSON.stringify({pid:process.pid,createdAt:new Date().toISOString()}));fs.closeSync(fd);return()=>{try{fs.unlinkSync(lock);}catch{}};}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;let owner:any=null;try{owner=JSON.parse(fs.readFileSync(lock,"utf8"));}catch{}if(attempt===0&&!processAlive(owner?.pid)){const item=fs.lstatSync(lock);if(!item.isFile()||item.isSymbolicLink())throw httpError("Snapshot lock is not a regular file.",503,"SNAPSHOT_LOCK_INVALID");fs.unlinkSync(lock);continue;}throw httpError("Another snapshot operation is running.",409,"SNAPSHOT_BUSY");}}throw httpError("Snapshot storage is busy.",409,"SNAPSHOT_BUSY");}
function readManifest(directory:string):SnapshotManifest{const file=path.join(directory,"manifest.json"),value=JSON.parse(fs.readFileSync(file,"utf8"));if(value?.formatVersion!==1||typeof value.id!=="string"||!UUID.test(value.id)||typeof value.createdAt!=="string"||!value.kind||!value.origin)throw new Error("Invalid snapshot manifest.");return value;}
function writeManifest(directory:string,manifest:SnapshotManifest){const file=path.join(directory,"manifest.json");fs.writeFileSync(file,`${JSON.stringify(manifest,null,2)}\n`,{encoding:"utf8",mode:0o600});fs.chmodSync(file,0o600);return sha256(file);}
function treeStats(directory:string,expectedDevice?:number){let sizeBytes=0,fileCount=0;const visit=(target:string)=>{const item=fs.lstatSync(target);if(item.isSymbolicLink())throw httpError("Snapshot contains a symbolic link.",409,"SNAPSHOT_SYMLINK");if(expectedDevice!==undefined&&item.dev!==expectedDevice)throw httpError("Snapshot crosses a filesystem boundary.",409,"SNAPSHOT_MOUNT_BOUNDARY");if(item.isDirectory()){for(const name of fs.readdirSync(target))visit(path.join(target,name));return;}if(item.isFile()){sizeBytes+=item.size;fileCount++;return;}throw httpError("Snapshot contains an unsupported filesystem entry.",409,"SNAPSHOT_ENTRY_UNSUPPORTED");};visit(directory);return{sizeBytes,fileCount};}
function verifiedDirectory(snapshotDir:string,relativePath:string,id:string){if(!UUID.test(id))throw httpError("Invalid snapshot id.",400,"SNAPSHOT_ID_INVALID");if(!/^(objects|trash)\/[0-9a-f-]+$/i.test(relativePath))throw httpError("Invalid snapshot location.",403,"SNAPSHOT_PATH_INVALID");const root=fs.realpathSync(snapshotDir),lexical=path.resolve(root,relativePath);if(!inside(root,lexical)||lexical===root)throw httpError("Snapshot path escaped its storage root.",403,"SNAPSHOT_PATH_ESCAPE");const link=fs.lstatSync(lexical);if(!link.isDirectory()||link.isSymbolicLink())throw httpError("Snapshot is not a verified directory.",403,"SNAPSHOT_PATH_INVALID");const real=fs.realpathSync(lexical),initial=fs.statSync(real);if(real!==lexical||!inside(root,real))throw httpError("Snapshot path escaped its storage root.",403,"SNAPSHOT_PATH_ESCAPE");const manifest=readManifest(real);if(manifest.id!==id)throw httpError("Snapshot identity does not match its manifest.",409,"SNAPSHOT_IDENTITY_CHANGED");treeStats(real,initial.dev);const finalLink=fs.lstatSync(lexical),finalReal=fs.realpathSync(lexical),final=fs.statSync(finalReal);if(finalLink.isSymbolicLink()||finalReal!==real||final.dev!==initial.dev||final.ino!==initial.ino)throw httpError("Snapshot identity changed during verification.",409,"SNAPSHOT_IDENTITY_CHANGED");return{directory:real,manifest,stats:treeStats(real,initial.dev)};}
function dayKey(date:Date){return`daily-${date.toISOString().slice(0,10).replaceAll("-","")}`;}
function weekKey(value:string){const date=new Date(value),d=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const start=new Date(Date.UTC(d.getUTCFullYear(),0,1)),week=Math.ceil((((d.getTime()-start.getTime())/86400000)+1)/7);return`${d.getUTCFullYear()}-${String(week).padStart(2,"0")}`;}

export function createAutomaticDatabaseSnapshot(root:string,dbPath:string,date=new Date(),options:{platform?:NodeJS.Platform;appRoot?:string;nodeBinary?:string;pythonBinary?:string}={}){
  if(!fs.existsSync(dbPath))return null;
  const snapshotDir=path.join(root,"snapshots"),release=acquireLease(snapshotDir);
  try{
    const objects=path.join(snapshotDir,"objects"),logicalKey=dayKey(date);
    for(const name of fs.readdirSync(objects)){if(!UUID.test(name))continue;try{const manifest=readManifest(path.join(objects,name));if(manifest.logicalKey===logicalKey&&manifest.kind==="database"&&fs.existsSync(path.join(objects,name,"COMPLETE")))return{directory:path.join(objects,name),database:path.join(objects,name,manifest.database??"claudex-workhouse.sqlite"),reused:true,id:manifest.id};}catch{/* invalid entries are reconciled after DB startup */}}
    const id=crypto.randomUUID(),staging=path.join(snapshotDir,".staging",id),final=path.join(objects,id),database=path.join(staging,"claudex-workhouse.sqlite");fs.mkdirSync(staging,{mode:0o700});fs.chmodSync(staging,0o700);
    try{
      const launch=sqliteMaintenanceInvocation({operation:"backup",source:dbPath,destination:database,...options});
      const result=spawnSync(launch.command,launch.args,{encoding:"utf8",shell:false,windowsHide:true,timeout:120_000,maxBuffer:1024*1024});if(result.status!==0)throw new Error(`Automatic database snapshot failed: ${(result.stderr||result.stdout||`exit ${result.status}`).trim().slice(0,300)}`);fs.chmodSync(database,0o600);
      const files=[database];for(const relative of ["config/claudex-workhouse.json","config/projects.json"]){const source=path.join(root,relative);if(fs.existsSync(source)){const destination=path.join(staging,path.basename(source));fs.copyFileSync(source,destination);fs.chmodSync(destination,0o600);files.push(destination);}}
      const manifest:SnapshotManifest={formatVersion:1,id,logicalKey,kind:"database",origin:"daily-first-start",source:"daily-first-start",createdAt:date.toISOString(),verification:"verified",database:path.basename(database),quickCheck:"ok",files:Object.fromEntries(files.map(file=>[path.basename(file),sha256(file)]))};writeManifest(staging,manifest);const complete=path.join(staging,"COMPLETE");fs.writeFileSync(complete,`${manifest.createdAt}\n`,{mode:0o600});fs.chmodSync(complete,0o600);syncDirectory(staging);fs.renameSync(staging,final);syncDirectory(objects);return{directory:final,database:path.join(final,path.basename(database)),reused:false,id};
    }catch(error){try{fs.rmSync(staging,{recursive:true,force:true});}catch{}throw error;}
  }finally{release();}
}

export class SnapshotStore{
  readonly root:string;
  constructor(snapshotDir:string,private db:DeckDatabase,private dataRoot=path.dirname(snapshotDir)){this.root=snapshotDir;ensureLayout(this.root);}
  private async locked<T>(operation:()=>Promise<T>){const release=acquireLease(this.root);try{return await operation();}finally{release();}}
  private record(directory:string,manifest:SnapshotManifest,state:SnapshotState,previous:Partial<SnapshotRecord>={}):SnapshotRecord{const stats=treeStats(directory),relativePath=path.relative(this.root,directory),now=new Date().toISOString();return{id:manifest.id,formatVersion:manifest.formatVersion,logicalKey:manifest.logicalKey??null,kind:manifest.kind,origin:manifest.origin,state,relativePath,createdAt:manifest.createdAt,updatedAt:now,sizeBytes:stats.sizeBytes,fileCount:stats.fileCount,verification:manifest.verification,pinned:previous.pinned??false,protectedReason:previous.protectedReason??null,trashedAt:previous.trashedAt??null,purgeAfter:previous.purgeAfter??null,lastError:null,manifestDigest:sha256(path.join(directory,"manifest.json"))};}
  async reconcile(){return this.locked(async()=>{let errors=this.recoverStaging(),discovered=0;const known=new Map((await this.db.listSnapshots()).map(item=>[item.id,item]));for(const [bucket,state] of [["objects","ready"],["trash","trashed"]] as const){const parent=path.join(this.root,bucket);for(const name of fs.readdirSync(parent)){if(!UUID.test(name))continue;const directory=path.join(parent,name),previous=known.get(name)??{};try{const link=fs.lstatSync(directory),complete=path.join(directory,"COMPLETE"),manifestFile=path.join(directory,"manifest.json");if(link.isSymbolicLink()||!link.isDirectory()||!fs.existsSync(complete))throw new Error("Snapshot is incomplete or unsafe.");fs.chmodSync(directory,0o700);fs.chmodSync(manifestFile,0o600);fs.chmodSync(complete,0o600);const manifest=readManifest(directory);if(manifest.id!==name)throw new Error("Snapshot id does not match directory.");await this.db.upsertSnapshot(this.record(directory,manifest,state,previous));known.delete(name);discovered++;}catch(error){errors++;await this.db.upsertSnapshot({id:name,formatVersion:1,logicalKey:null,kind:"unknown",origin:"reconcile",state:"error",relativePath:path.relative(this.root,directory),createdAt:previous.createdAt??new Date().toISOString(),updatedAt:new Date().toISOString(),sizeBytes:0,fileCount:0,verification:"failed",pinned:previous.pinned??false,protectedReason:"invalid-or-incomplete",trashedAt:null,purgeAfter:null,lastError:error instanceof Error?error.message:String(error),manifestDigest:null});known.delete(name);}}}for(const item of known.values()){if(item.state==="purged")continue;if(item.state==="purging"){await this.db.upsertSnapshot({...item,state:"purged",relativePath:`purged/${item.id}`,updatedAt:new Date().toISOString(),sizeBytes:0,fileCount:0,purgeAfter:null,lastError:null});continue;}await this.db.upsertSnapshot({...item,state:"error",updatedAt:new Date().toISOString(),protectedReason:"missing-on-disk",lastError:"Snapshot directory is missing."});errors++;}return{discovered,errors};});}
  list(){return this.db.listSnapshots() as Promise<SnapshotRecord[]>;}
  async summary(){const items=await this.list(),active=items.filter(item=>item.state!=="purged");return{count:active.length,activeCount:active.filter(item=>item.state==="ready").length,trashCount:active.filter(item=>item.state==="trashed").length,totalBytes:active.reduce((sum,item)=>sum+Number(item.sizeBytes||0),0),lastAutomaticAt:active.filter(item=>item.kind==="database"&&item.state==="ready"&&item.verification==="verified").sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]?.createdAt??null,errors:active.filter(item=>item.state==="error").length};}
  async setPinned(id:string,pinned:boolean){return this.locked(async()=>{const item=await this.required(id);if(!["ready","trashed"].includes(item.state))throw httpError("Only stable snapshots can be pinned.");return this.db.upsertSnapshot({...item,pinned,updatedAt:new Date().toISOString()});});}
  async trash(id:string){return this.locked(async()=>{let item=await this.required(id);if(item.state==="trashed")return item;if(item.state!=="ready")throw httpError("Snapshot is not ready to move to trash.");if(item.pinned||item.protectedReason)throw httpError("Protected snapshots cannot be moved to trash.",409,"SNAPSHOT_PROTECTED");const source=verifiedDirectory(this.root,item.relativePath,id),destination=path.join(this.root,"trash",id);item=await this.db.upsertSnapshot({...item,state:"trashing",updatedAt:new Date().toISOString()});fs.renameSync(source.directory,destination);syncDirectory(path.dirname(destination));const trashedAt=new Date().toISOString(),purgeAfter=new Date(Date.now()+30*86400000).toISOString();return this.db.upsertSnapshot({...item,state:"trashed",relativePath:path.relative(this.root,destination),updatedAt:trashedAt,trashedAt,purgeAfter});});}
  async untrash(id:string){return this.locked(async()=>{let item=await this.required(id);if(item.state==="ready")return item;if(item.state!=="trashed")throw httpError("Snapshot is not in trash.");const source=verifiedDirectory(this.root,item.relativePath,id),destination=path.join(this.root,"objects",id);if(fs.existsSync(destination))throw httpError("Snapshot destination already exists.");item=await this.db.upsertSnapshot({...item,state:"untrashing",updatedAt:new Date().toISOString()});fs.renameSync(source.directory,destination);syncDirectory(path.dirname(destination));return this.db.upsertSnapshot({...item,state:"ready",relativePath:path.relative(this.root,destination),updatedAt:new Date().toISOString(),trashedAt:null,purgeAfter:null});});}
  async purge(id:string){return this.locked(async()=>{let item=await this.required(id);if(item.state==="purged")return item;if(item.state!=="trashed")throw httpError("Only trashed snapshots can be permanently deleted.");if(item.pinned||item.protectedReason)throw httpError("Protected snapshots cannot be deleted.",409,"SNAPSHOT_PROTECTED");const target=verifiedDirectory(this.root,item.relativePath,id);item=await this.db.upsertSnapshot({...item,state:"purging",updatedAt:new Date().toISOString()});fs.rmSync(target.directory,{recursive:true,force:false,maxRetries:2});syncDirectory(path.dirname(target.directory));return this.db.upsertSnapshot({...item,state:"purged",relativePath:`purged/${id}`,updatedAt:new Date().toISOString(),sizeBytes:0,fileCount:0,trashedAt:item.trashedAt??new Date().toISOString(),purgeAfter:null});});}
  async applyAutomaticRetention(daily=7,weekly=4){const reconciliation=await this.reconcile();const items=(await this.list()).filter(item=>item.kind==="database"&&item.origin==="daily-first-start"&&item.state==="ready"&&item.verification==="verified").sort((a,b)=>b.createdAt.localeCompare(a.createdAt));if(!items.length)return{kept:0,trashed:0,errors:reconciliation.errors};const keep=new Set(items.filter(item=>item.pinned).map(item=>item.id));for(const item of items.slice(0,Math.max(1,daily)))keep.add(item.id);const weeks=new Set<string>();for(const item of items){const key=weekKey(item.createdAt);if(weeks.has(key))continue;if(weeks.size>=weekly)break;weeks.add(key);keep.add(item.id);}for(const item of items){await this.db.upsertSnapshot({...item,protectedReason:item.id===items[0].id?"latest-verified":null,updatedAt:new Date().toISOString()});}let trashed=0;for(const item of items){if(keep.has(item.id))continue;await this.trash(item.id);trashed++;}return{kept:keep.size,trashed,errors:reconciliation.errors};}
  async purgeExpired(now=new Date()){const items=await this.list();let purged=0;for(const item of items){if(item.state==="trashed"&&!item.pinned&&!item.protectedReason&&item.purgeAfter&&item.purgeAfter<=now.toISOString()){await this.purge(item.id);purged++;}}return{purged};}
  legacyInventory(){const items=this.legacyCandidates().map(item=>({id:item.id,source:item.source,name:item.name,kind:item.kind,sizeBytes:item.sizeBytes,fileCount:item.fileCount,managed:false}));return{items,totalBytes:items.reduce((sum,item)=>sum+item.sizeBytes,0)};}
  async importLegacy(legacyId:string){return this.locked(async()=>{const candidate=this.legacyCandidates().find(item=>item.id===legacyId);if(!candidate)throw httpError("Legacy backup not found.",404,"SNAPSHOT_LEGACY_NOT_FOUND");const sourceRoot=fs.realpathSync(candidate.sourceRoot),sourceReal=fs.realpathSync(candidate.target),sourceLink=fs.lstatSync(candidate.target),sourceStat=fs.statSync(sourceReal),snapshotStat=fs.statSync(this.root);if(sourceLink.isSymbolicLink()||!inside(sourceRoot,sourceReal)||sourceReal===sourceRoot)throw httpError("Legacy backup path is unsafe.",403,"SNAPSHOT_PATH_INVALID");treeStats(sourceReal,sourceStat.dev);if(sourceStat.dev!==snapshotStat.dev)throw httpError("Cross-filesystem legacy import requires a verified copy job and is not enabled.",409,"SNAPSHOT_CROSS_DEVICE");const id=crypto.randomUUID(),staging=path.join(this.root,".staging",id),payload=path.join(staging,"payload"),operation=path.join(staging,"operation.json"),final=path.join(this.root,"objects",id),createdAt=new Date().toISOString();fs.mkdirSync(staging,{mode:0o700});fs.chmodSync(staging,0o700);fs.writeFileSync(operation,`${JSON.stringify({formatVersion:1,type:"legacy-import",source:candidate.source,name:candidate.name,sourcePath:path.relative(this.dataRoot,candidate.target)})}\n`,{mode:0o600});fs.chmodSync(operation,0o600);try{fs.renameSync(candidate.target,payload);const manifest:SnapshotManifest={formatVersion:1,id,logicalKey:null,kind:"legacy",origin:`legacy:${candidate.source}`,source:`legacy:${candidate.source}`,createdAt,verification:"unverified"};writeManifest(staging,manifest);const complete=path.join(staging,"COMPLETE");fs.writeFileSync(complete,`${createdAt}\n`,{mode:0o600});fs.chmodSync(complete,0o600);syncDirectory(staging);fs.unlinkSync(operation);fs.renameSync(staging,final);syncDirectory(path.dirname(final));return this.db.upsertSnapshot(this.record(final,manifest,"ready"));}catch(error){try{if(fs.existsSync(payload)&&!fs.existsSync(candidate.target))fs.renameSync(payload,candidate.target);if(fs.existsSync(staging))fs.rmSync(staging,{recursive:true,force:true});}catch{/* reconcile will retry recovery from the staging operation */}throw error;}});}
  private legacyCandidates(){const sources:Array<{key:string;directory:string;filter?:(name:string)=>boolean}>=[{key:"backups",directory:path.join(this.dataRoot,"backups")},{key:"data-backups",directory:path.join(this.dataRoot,"data","backups")},{key:"config-backup",directory:path.join(this.dataRoot,"config"),filter:name=>LOOSE_BACKUP.test(name)}],items:Array<{id:string;source:string;sourceRoot:string;name:string;target:string;kind:string;sizeBytes:number;fileCount:number}>=[];for(const source of sources){if(!fs.existsSync(source.directory))continue;const add=(target:string,name:string)=>{try{const link=fs.lstatSync(target);if(link.isSymbolicLink())return;const rootStat=fs.statSync(source.directory),stats=treeStats(target,rootStat.dev),ext=path.extname(name).toLowerCase();items.push({id:crypto.createHash("sha256").update(`${source.key}:${name}`).digest("hex").slice(0,24),source:source.key,sourceRoot:source.directory,name,target,kind:link.isDirectory()?"directory":ext===".sqlite"?"sqlite":ext===".tgz"||ext===".gz"?"archive":"file",...stats});}catch{/* unsafe or inaccessible legacy entries never receive a mutation id */}};for(const entry of fs.readdirSync(source.directory,{withFileTypes:true})){if(source.filter&&!source.filter(entry.name))continue;if(source.key==="backups"&&entry.name==="claude-runtime")continue;if(source.key==="backups"&&entry.name==="automatic"&&entry.isDirectory()){for(const child of fs.readdirSync(path.join(source.directory,entry.name)))add(path.join(source.directory,entry.name,child),`automatic/${child}`);continue;}add(path.join(source.directory,entry.name),entry.name);}}return items;}
  private recoverStaging(){let errors=0;const parent=path.join(this.root,".staging"),objects=path.join(this.root,"objects"),legacyRoots=[path.join(this.dataRoot,"backups"),path.join(this.dataRoot,"data","backups")],configRoot=path.join(this.dataRoot,"config");for(const id of fs.readdirSync(parent)){if(!UUID.test(id))continue;const staging=path.join(parent,id),complete=path.join(staging,"COMPLETE"),operation=path.join(staging,"operation.json"),payload=path.join(staging,"payload");try{if(fs.existsSync(complete)){const manifest=readManifest(staging);if(manifest.id!==id)throw new Error("Staging manifest identity mismatch.");if(fs.existsSync(operation))fs.unlinkSync(operation);const final=path.join(objects,id);if(fs.existsSync(final))throw new Error("Staging destination already exists.");fs.renameSync(staging,final);continue;}if(fs.existsSync(operation)&&fs.existsSync(payload)){const value=JSON.parse(fs.readFileSync(operation,"utf8"));if(value.type!=="legacy-import"||typeof value.sourcePath!=="string")throw new Error("Invalid staging recovery operation.");const target=path.resolve(this.dataRoot,value.sourcePath),allowed=legacyRoots.some(root=>inside(root,target)&&root!==target)||(inside(configRoot,target)&&configRoot!==target&&LOOSE_BACKUP.test(path.basename(target))),runtimeRoot=path.join(this.dataRoot,"backups","claude-runtime");if(!allowed||inside(runtimeRoot,target)||fs.existsSync(target))throw new Error("Legacy import cannot be rolled back safely.");fs.mkdirSync(path.dirname(target),{recursive:true});fs.renameSync(payload,target);fs.rmSync(staging,{recursive:true,force:true});continue;}errors++;}catch{errors++;}}return errors;}
  private async required(id:string){if(!UUID.test(id))throw httpError("Invalid snapshot id.",400,"SNAPSHOT_ID_INVALID");const item=await this.db.getSnapshot(id);if(!item)throw httpError("Snapshot not found.",404,"SNAPSHOT_NOT_FOUND");return item as SnapshotRecord;}
}
