import{expect,test}from"@playwright/test";

test("completed artifact review keeps user follow-up and Markdown controls",async({page})=>{
  await page.addInitScript(()=>{localStorage.setItem("claudex-ui-locale","ko");class SilentEventSource{constructor(public url:string){}addEventListener(){}close(){}}Object.defineProperty(globalThis,"EventSource",{value:SilentEventSource,configurable:true});});
  const now=new Date().toISOString(),id="edededed-eded-4ded-8ded-edededededed",session={id,projectId:"project",title:"완료된 산출물 리뷰",mode:"debate",status:"completed",outcome:"turn-limit",primaryParticipantId:null,maxCalls:2,currentCallCount:2,currentStep:"done",timeoutAt:now,controllerGeneration:1,createdAt:now,updatedAt:now,completedAt:now,maxTurnsPerParticipant:1,metadata:{topLevel:true,conversationFlow:"automatic",conversationKind:"artifact-review",currentRound:1,waitingForUser:false,enabledProviders:["codex","claude"],participantOrder:["codex","claude"]}},participants=["codex","claude"].map((provider,index)=>({id:`p-${provider}`,collaborationSessionId:id,provider,role:index?"reviewer":"primary",executionHostId:"local",workspaceId:"workspace",providerSessionId:`${provider}-session`,permissionMode:"read",status:"completed",sessionGeneration:1,capabilitySnapshot:{newSession:true},createdAt:now,updatedAt:now,archivedAt:null})),runs=participants.map((person,index)=>({id:`run-${person.provider}`,collaborationSessionId:id,participantId:person.id,round:1,sequence:index+1,attempt:1,purpose:"debate-turn",providerTaskId:`task-${person.provider}`,status:"completed",generation:1,errorCategory:null,completedAt:now})),runOutputs=Object.fromEntries(runs.map(run=>[run.id,`${run.id} 검토 결과`]));
  const detail={session,participants,runs,messages:[{id:"user",messageType:"user-input",contentRef:"이 산출물을 검토해 줘.",round:1,createdAt:now}],avatarStates:[],runOutputs,runEvents:{},tasks:{},continuation:{available:true,canAddRounds:true,canAutoContinue:false,canSubmitUserInput:true,canRetryFailedTurn:false,reason:"review-complete"}};
  await page.route("**/api/**",route=>{const pathname=new URL(route.request().url()).pathname,json=(value:unknown)=>route.fulfill({status:200,contentType:"application/json",body:JSON.stringify(value)});if(pathname==="/api/collaborations")return json({collaborations:[session]});if(pathname===`/api/collaborations/${id}`)return json(detail);if(pathname==="/api/tasks")return json({tasks:[],partial:false,warnings:[]});if(pathname==="/api/projects")return json({projects:[{id:"project",name:"Project",enabled:true,error:null}]});if(pathname==="/api/hosts")return json({hosts:[{id:"local",displayName:"Local",status:"online"}]});if(pathname==="/api/workspaces")return json({workspaces:[{id:"workspace",projectId:"project",hostId:"local",displayName:"Workspace",canonicalPath:"/workspace"}]});if(pathname==="/api/emotion")return json({state:{outfit:"normal"},codexState:{outfit:"Gpt-Codex"},outfits:[],assets:{},mode:"catch"});if(pathname==="/api/quota")return json({claude:{},codex:{},fetchedAt:now});return json({});});
  await page.goto("/");await page.getByRole("navigation",{name:"주요 화면"}).getByRole("button",{name:"대화",exact:true}).click();await page.getByRole("button",{name:/완료된 산출물 리뷰/}).click();
  const timeline=page.locator(".collaboration-view");await expect(timeline.locator("textarea#conversation-next")).toBeVisible();await expect(timeline.getByRole("button",{name:"5턴 추가"})).toBeVisible();await expect(timeline.getByRole("button",{name:"직접 개입"})).toHaveCount(0);await expect(timeline.getByRole("button",{name:"Markdown 생성"})).toBeVisible();
});
