import crypto from"node:crypto";
import{EventEmitter}from"node:events";
import path from"node:path";
import type{AppConfig}from"../config.js";
import type{DeckDatabase}from"../db/client.js";
import{detectDeployment}from"./detectors/deployment.js";
import{detectTailscale,tailscaleServeArgs}from"./detectors/tailscale.js";
import{detectCloudflare}from"./detectors/cloudflare.js";
import{boundedCommand,defaultExternalCommandRunner,findExecutable,type ExternalCommandRunner}from"./process.js";
import{redactExternalAccessText,redactExternalAccessValue}from"./redaction.js";
import{removeManagedCloudflareFiles,restorePrimaryConfig,storeCloudflareToken,updatePrimaryConfig,writeManagedCloudflareFiles}from"./config-store.js";
import{runConnectionTests}from"./tests/connection-tests.js";
import type{ExternalAccessAction,ExternalAccessCheck,ExternalAccessDetection,ExternalAccessOperation,ExternalAccessPlan,ExternalAccessProvider}from"./types.js";
import{externalAccessStateMetadata}from"./status.js";

type InternalPlan={plan:ExternalAccessPlan;secret?:string};
const canonical=(value:unknown)=>JSON.stringify(value,(_key,item)=>item&&typeof item==="object"&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item);
const digest=(value:unknown)=>crypto.createHash("sha256").update(canonical(value)).digest("hex");
const detectionRevision=(value:ExternalAccessDetection)=>digest({...value,checkedAt:undefined});
const servePreview=(action:ExternalAccessAction,target:string)=>action==="tailscale_serve_remove"?["tailscale","serve","reset"]:["tailscale","serve","--bg",target];
export class ExternalAccessCoordinator{
 private plans=new Map<string,InternalPlan>();private operationPlans=new Map<string,InternalPlan>();private cancelled=new Set<string>();private events=new EventEmitter();private runner:ExternalCommandRunner;
 constructor(private config:AppConfig,private db:DeckDatabase,options:{runner?:ExternalCommandRunner}={}){this.runner=options.runner??defaultExternalCommandRunner;this.events.setMaxListeners(100);}
 async reconcile(){return this.db.reconcileExternalAccessOperations(new Date().toISOString());}
 methods(){const deployment=detectDeployment();return{schemaVersion:1,deployment,states:externalAccessStateMetadata,methods:[{provider:"local",management:"managed",publicExposure:"none",capabilities:["test_local_health","show_url"]},{provider:"tailscale",management:deployment.container?"guided":"managed",publicExposure:"tailnet",capabilities:["detect_installation","detect_service","detect_authentication","detect_configuration","create_plan","apply_configuration","remove_configuration","test_local_health","test_dns","test_tls","test_auth_boundary","show_url","show_qr"]},{provider:"cloudflare",management:deployment.container?"guided":"guided",publicExposure:"internet",capabilities:["detect_installation","detect_service","detect_configuration","validate_configuration","create_plan","apply_configuration","remove_configuration","test_local_health","test_dns","test_tls","test_auth_boundary","show_url","show_qr"]}]};}
 async detect(provider?:ExternalAccessProvider){const local:ExternalAccessDetection={provider:"local",state:"healthy",management:"managed",checkedAt:new Date().toISOString(),installed:true,serviceRunning:true,authenticated:true,connected:true,configured:this.config.authMode==="local",permission:"sufficient",version:null,externalUrl:this.config.authMode==="local"?this.config.externalOrigin:null,details:{listener:`${this.config.host}:${this.config.port}`},warnings:[]};if(provider==="local")return[local];if(provider==="tailscale")return[await detectTailscale({runner:this.runner})];if(provider==="cloudflare")return[await detectCloudflare({runner:this.runner})];return[local,await detectTailscale({runner:this.runner}),await detectCloudflare({runner:this.runner})];}
 async configuration(){const profiles=await this.db.listExternalAccessProfiles();return{authMode:this.config.authMode,externalOrigin:this.config.externalOrigin,environmentManaged:{authMode:Boolean(process.env.CLAUDEX_WORKHOUSE_AUTH_MODE),externalOrigin:Boolean(process.env.CLAUDEX_WORKHOUSE_EXTERNAL_ORIGIN)},profiles:profiles.map((profile:any)=>({id:profile.id,provider:profile.provider,desiredMode:profile.desiredMode,configurationSource:profile.configurationSource,revision:profile.revision,createdAt:profile.createdAt,updatedAt:profile.updatedAt,configuration:{hostname:profile.configuration?.hostname??null,allowedEmail:profile.configuration?.allowedEmail??null,teamDomain:profile.configuration?.teamDomain??null,audienceConfigured:Boolean(profile.configuration?.audienceConfigured),localTarget:profile.configuration?.localTarget??null,runMode:profile.configuration?.runMode??null,managedServe:Boolean(profile.configuration?.managedServe),managedFiles:Boolean(profile.configuration?.managedFiles),tokenStored:Boolean(profile.configuration?.tokenStored)}}))};}
 async createPlan(input:any){const provider=input.provider as ExternalAccessProvider,action=input.action as ExternalAccessAction,detections=await this.detect(provider),detected=detections[0],profile=(await this.db.listExternalAccessProfiles()).find((item:any)=>item.provider===provider),configurationRevision=Number(profile?.revision??0),createdAt=new Date(),id=crypto.randomUUID(),configurationWritable=!process.env.CLAUDEX_WORKHOUSE_AUTH_MODE&&!process.env.CLAUDEX_WORKHOUSE_EXTERNAL_ORIGIN,safeInput={...input,token:undefined,tokenConfigured:Boolean(input.token),configurationWritable},base:Omit<ExternalAccessPlan,"planDigest">={id,provider,action,createdAt:createdAt.toISOString(),expiresAt:new Date(createdAt.getTime()+10*60_000).toISOString(),configurationRevision,detectedStateRevision:detectionRevision(detected),steps:[],commands:[],files:[],services:[],publicExposure:provider==="cloudflare"?"internet":provider==="tailscale"?"tailnet":"none",authenticationBoundary:provider==="cloudflare"?"Cloudflare Access JWT and exact email":provider==="tailscale"?"Tailscale Serve identity and exact email":"local owner authentication",adminRequired:detected.permission==="required",externalActions:[],rollbackSteps:[],input:safeInput};
 if(input.provider==="local"){base.steps=[{id:"local-config",label:"Restore loopback-only local authentication",action:"local_configuration_apply",reversible:true}];base.files=[{pathLabel:"<data>/config/claudex-workhouse.json",operation:"update"}];base.services=[{name:"claudex-workhouse",operation:"none"}];base.externalActions=["Restart Workhouse after applying the authentication configuration."];base.rollbackSteps=["Restore the previous Workhouse authentication configuration."];}
 if(input.provider==="tailscale"){if(input.action==="tailscale_serve_apply"&&detected.configured&&!profile?.configuration?.managedServe)throw Object.assign(new Error("An existing Tailscale Serve configuration is not owned by Workhouse and will not be overwritten."),{statusCode:409,code:"EXTERNAL_RESOURCE_CONFLICT"});base.steps=[{id:"serve",label:input.action.endsWith("remove")?"Remove the Workhouse Serve mapping":"Apply a loopback Serve mapping",action:input.action,reversible:true}];base.commands=[{label:"Tailscale Serve",argv:servePreview(input.action,String(input.localTarget??`http://127.0.0.1:${this.config.port}`)),execution:"automatic"}];base.services=[{name:"tailscaled",operation:"none"},{name:"claudex-workhouse",operation:"none"}];base.rollbackSteps=["Restore the previous Tailscale Serve configuration.","Restore the previous Workhouse authentication configuration."];base.externalActions.push("Restart Workhouse after applying the authentication configuration.");if(detected.permission!=="sufficient")base.externalActions.push("The operating system may request Tailscale operator or administrator approval.");}
 if(input.provider==="cloudflare"){base.steps=[{id:"managed-files",label:input.action.includes("remove")?"Remove only Workhouse-managed files":"Create Workhouse-managed cloudflared files",action:input.action,reversible:true},{id:"dashboard",label:"Verify the hostname and Access policy in Cloudflare Zero Trust",action:"cloudflare_validate",reversible:false}];base.files=[{pathLabel:"<data>/config/external-access/cloudflared.yml",operation:input.action.includes("remove")?"remove":"create"},{pathLabel:"<data>/config/external-access/cloudflared.token",operation:input.action.includes("remove")?"remove":"create"}];if(input.action==="cloudflare_managed_config_apply")base.commands=[input.runMode==="sidecar"?{label:"Start the managed sidecar",argv:["docker","compose","-f","<data>/config/external-access/compose.cloudflared.yaml","up","-d","cloudflared"],execution:"operator"}:{label:"Start the managed host tunnel",argv:["cloudflared","tunnel","run","--token-file","<data>/config/external-access/cloudflared.token"],execution:"operator"}];base.services=[{name:"cloudflared",operation:"none"},{name:"claudex-workhouse",operation:"none"}];base.externalActions=["Create or select the tunnel hostname in Cloudflare Zero Trust.","Apply an Access policy that allows the configured exact email.",...(input.action==="cloudflare_managed_config_apply"?["Start or restart cloudflared with the reviewed operator command."]:[]),"Restart Workhouse after applying the authentication configuration."];base.rollbackSteps=["Remove only files recorded as Workhouse-managed.","Restore the previous Workhouse authentication configuration."];}
 if(!configurationWritable)base.externalActions.unshift("Authentication mode or external origin is managed by environment variables. Update the deployment environment and restart Workhouse; the wizard will not overwrite it.");
 const planDigest=digest({...base,input:{...safeInput,tokenHash:input.token?digest(input.token):null}}),plan:ExternalAccessPlan={...base,planDigest},record={plan,secret:input.token};this.plans.set(id,record);const expiry=setTimeout(()=>{if(this.plans.get(id)===record)this.plans.delete(id);},Math.max(1,Date.parse(plan.expiresAt)-Date.now()));expiry.unref?.();return plan;}
 getPlan(id:string){const item=this.plans.get(id);if(!item)throw Object.assign(new Error("External access plan was not found or expired."),{statusCode:404,code:"EXTERNAL_ACCESS_PLAN_NOT_FOUND"});return item.plan;}
 private emit(operation:ExternalAccessOperation){this.events.emit(operation.id,operation);}
 async getOperation(id:string){const row=await this.db.getExternalAccessOperation(id);if(!row)throw Object.assign(new Error("External access operation was not found."),{statusCode:404,code:"EXTERNAL_ACCESS_OPERATION_NOT_FOUND"});const checks=(await this.db.listExternalAccessChecks(id)).map(item=>({code:item.checkCode,status:item.status,detail:item.safeDetail,checkedAt:item.checkedAt}));return{...row,checks};}
 subscribe(id:string,listener:(value:unknown)=>void){this.events.on(id,listener);return()=>this.events.off(id,listener);}
 async apply(planId:string,input:{planDigest:string;configurationRevision:number}){const internal=this.plans.get(planId);if(!internal)throw Object.assign(new Error("External access plan was not found or expired."),{statusCode:404});const plan=internal.plan;if(Date.parse(plan.expiresAt)<=Date.now())throw Object.assign(new Error("External access plan expired; detect current state and create a new plan."),{statusCode:409,code:"EXTERNAL_ACCESS_PLAN_EXPIRED"});if(input.planDigest!==plan.planDigest||input.configurationRevision!==plan.configurationRevision)throw Object.assign(new Error("External access plan approval does not match the immutable plan."),{statusCode:409,code:"EXTERNAL_ACCESS_PLAN_MISMATCH"});const profiles=await this.db.listExternalAccessProfiles(),revision=Number(profiles.find((x:any)=>x.provider===plan.provider)?.revision??0);if(revision!==plan.configurationRevision)throw Object.assign(new Error("External access configuration changed after this plan was created."),{statusCode:409,code:"EXTERNAL_ACCESS_REVISION_CONFLICT"});const current=(await this.detect(plan.provider))[0];if(detectionRevision(current)!==plan.detectedStateRevision)throw Object.assign(new Error("External access state changed after this plan was created; detect again before applying."),{statusCode:409,code:"EXTERNAL_ACCESS_STATE_CHANGED"});
 const now=new Date().toISOString(),environmentBlocked=plan.input.configurationWritable===false,operation:ExternalAccessOperation={id:crypto.randomUUID(),profileId:null,provider:plan.provider,action:plan.action,planDigest:plan.planDigest,status:environmentBlocked?"waiting_external_action":"pending",stage:environmentBlocked?"environment_configuration_required":"queued",safeErrorCode:environmentBlocked?"ENVIRONMENT_MANAGED_CONFIGURATION":null,startedAt:null,updatedAt:now,finishedAt:environmentBlocked?now:null,rollbackStatus:null,interrupted:false,checks:[]};await this.db.createExternalAccessOperation(operation);if(environmentBlocked){await this.db.appendAudit({createdAt:now,actor:"system",action:"external-access-operation",provider:plan.provider,taskId:null,projectId:null,outcome:"waiting_external_action",detail:`action=${plan.action};code=ENVIRONMENT_MANAGED_CONFIGURATION`});return operation;}this.operationPlans.set(operation.id,internal);queueMicrotask(()=>void this.execute(internal,operation));return operation;}
 private async persist(operation:ExternalAccessOperation){operation.updatedAt=new Date().toISOString();await this.db.updateExternalAccessOperation(operation);this.emit(operation);}
 private async execute(internal:InternalPlan,operation:ExternalAccessOperation){const plan=internal.plan;operation.status="running";operation.stage="applying";operation.startedAt=new Date().toISOString();await this.persist(operation);try{if(this.cancelled.has(operation.id))throw Object.assign(new Error("External access operation was cancelled before changes began."),{code:"EXTERNAL_ACCESS_CANCELLED"});let externalOrigin:string|null=null,configuration:Record<string,unknown>={};
   if(plan.provider==="tailscale"){const binary=findExecutable("tailscale");if(!binary)throw Object.assign(new Error("Tailscale is not installed."),{code:"TAILSCALE_NOT_DETECTED"});const action=plan.action==="tailscale_serve_remove"?"remove":"apply",target=String(plan.input.localTarget??`http://127.0.0.1:${this.config.port}`),result=await boundedCommand(this.runner,binary,tailscaleServeArgs(action,target),this.config.dataRoot,30_000);if(result.exitCode!==0)throw Object.assign(new Error(redactExternalAccessText(result.stderr||"Tailscale Serve command failed.")),{code:"TAILSCALE_PERMISSION_OR_COMMAND_FAILED"});const detected=await detectTailscale({runner:this.runner,binary});externalOrigin=action==="apply"?(detected.externalUrl??(typeof detected.details.dnsName==="string"?`https://${detected.details.dnsName}`:null)):null;if(action==="apply"&&!externalOrigin)throw Object.assign(new Error("Tailscale Serve did not report a MagicDNS URL."),{code:"TAILSCALE_SERVE_URL_MISSING"});configuration=action==="apply"?{hostname:new URL(externalOrigin!).hostname,allowedEmail:plan.input.allowedEmail,localTarget:target,managedServe:true}:{managedServe:false};if(action==="apply")updatePrimaryConfig(this.config,{provider:"tailscale",externalOrigin:externalOrigin!,allowedEmail:String(plan.input.allowedEmail)});else restorePrimaryConfig(this.config);
   }else if(plan.provider==="cloudflare"){const input=plan.input as any;externalOrigin=`https://${input.hostname}`;if(plan.action==="cloudflare_managed_config_apply"){if(!internal.secret)throw Object.assign(new Error("Cloudflare tunnel token must be supplied again."),{code:"CLOUDFLARE_TOKEN_REQUIRED"});storeCloudflareToken(this.config.dataRoot,internal.secret);writeManagedCloudflareFiles(this.config.dataRoot,{hostname:input.hostname,localTarget:input.localTarget,runMode:input.runMode==="sidecar"?"sidecar":"host"});updatePrimaryConfig(this.config,{provider:"cloudflare",externalOrigin,allowedEmail:input.allowedEmail,teamDomain:input.teamDomain,audience:input.audience});configuration={hostname:input.hostname,allowedEmail:input.allowedEmail,teamDomain:input.teamDomain,audienceConfigured:Boolean(input.audience),localTarget:input.localTarget,runMode:input.runMode,managedFiles:true,tokenStored:true};}else if(plan.action==="cloudflare_managed_config_remove"){removeManagedCloudflareFiles(this.config.dataRoot);restorePrimaryConfig(this.config);externalOrigin=null;configuration={managedFiles:false};}else configuration={hostname:input.hostname,localTarget:input.localTarget,runMode:input.runMode};
   }else{externalOrigin=`http://127.0.0.1:${this.config.port}`;configuration={loopbackOnly:true};if(plan.action==="local_configuration_apply")updatePrimaryConfig(this.config,{provider:"local",externalOrigin});}
   const profileResult=await this.db.upsertExternalAccessProfile({id:crypto.randomUUID(),provider:plan.provider,desiredMode:plan.action.includes("remove")?"disabled":"enabled",configuration,configurationSource:"workhouse",managedResources:plan.files.map(x=>x.pathLabel),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()},plan.configurationRevision||undefined);if(!profileResult.updated)throw Object.assign(new Error("External access profile revision changed during apply."),{code:"EXTERNAL_ACCESS_REVISION_CONFLICT"});operation.profileId=profileResult.current.id;operation.status="verifying";operation.stage="testing";await this.persist(operation);const checks=await runConnectionTests({localOrigin:`http://127.0.0.1:${this.config.port}`,externalOrigin,configuredOrigin:this.config.externalOrigin,provider:plan.provider});for(const check of checks){operation.checks.push(check);await this.db.appendExternalAccessCheck({...check,operationId:operation.id,profileId:operation.profileId});}const failed=checks.some(x=>x.status==="failed"),warning=checks.some(x=>x.status==="warning");operation.status=failed?"failed":warning||plan.externalActions.length?"degraded":"succeeded";operation.stage=plan.externalActions.length?"external_action_required":"complete";operation.safeErrorCode=failed?"CONNECTION_TEST_FAILED":null;operation.finishedAt=new Date().toISOString();await this.persist(operation);await this.db.appendAudit({createdAt:operation.finishedAt,actor:"system",action:"external-access-operation",provider:plan.provider,taskId:null,projectId:null,outcome:operation.status,detail:`action=${plan.action};stage=${operation.stage}`});
 }catch(error){const cancelled=(error as any)?.code==="EXTERNAL_ACCESS_CANCELLED";operation.status=cancelled?"interrupted":"failed";operation.interrupted=cancelled;operation.stage=cancelled?"interrupted":"failed";operation.safeErrorCode=typeof(error as any)?.code==="string"?(error as any).code:"EXTERNAL_ACCESS_APPLY_FAILED";operation.finishedAt=new Date().toISOString();await this.persist(operation);await this.db.appendAudit({createdAt:operation.finishedAt,actor:"system",action:"external-access-operation",provider:plan.provider,taskId:null,projectId:null,outcome:operation.status,detail:`action=${plan.action};code=${operation.safeErrorCode}`}).catch(()=>{});}finally{this.operationPlans.delete(operation.id);this.cancelled.delete(operation.id);}}
 async test(provider:ExternalAccessProvider,profileId?:string){let origin:string|null=provider==="local"?this.config.externalOrigin:null;if(profileId){const profile=await this.db.getExternalAccessProfile(profileId);if(!profile||profile.provider!==provider)throw Object.assign(new Error("External access profile was not found."),{statusCode:404});if(typeof profile.configuration?.hostname==="string")origin=`https://${profile.configuration.hostname}`;}return runConnectionTests({localOrigin:`http://127.0.0.1:${this.config.port}`,externalOrigin:origin,configuredOrigin:this.config.externalOrigin,provider});}
 async remove(profileId:string){const profile=await this.db.getExternalAccessProfile(profileId);if(!profile)throw Object.assign(new Error("External access profile was not found."),{statusCode:404});return this.createPlan({provider:profile.provider,action:profile.provider==="tailscale"?"tailscale_serve_remove":profile.provider==="cloudflare"?"cloudflare_managed_config_remove":"external_access_test",hostname:profile.configuration?.hostname??"localhost",localTarget:profile.configuration?.localTarget??`http://127.0.0.1:${this.config.port}`,runMode:profile.configuration?.runMode??"existing"});}
 async cancel(id:string){const operation=await this.getOperation(id);if(operation.status!=="pending")throw Object.assign(new Error("This operation can no longer be cancelled safely after mutation work has started."),{statusCode:409,code:"EXTERNAL_ACCESS_NOT_CANCELLABLE"});this.cancelled.add(id);return{accepted:true,id};}
 async rollback(id:string){const operation=await this.getOperation(id),profile=operation.profileId?await this.db.getExternalAccessProfile(operation.profileId):null;if(!profile)throw Object.assign(new Error("No managed profile is available for rollback."),{statusCode:409,code:"EXTERNAL_ACCESS_ROLLBACK_UNAVAILABLE"});const plan=await this.remove(profile.id);return{plan,sourceOperationId:id};}
 support(){return this.detect().then(detections=>({schemaVersion:1,generatedAt:new Date().toISOString(),deployment:detectDeployment(),authMode:this.config.authMode,externalOrigin:redactExternalAccessText(this.config.externalOrigin),detections:detections.map(item=>redactExternalAccessValue({...item,externalUrl:item.externalUrl?redactExternalAccessText(item.externalUrl):null,details:redactExternalAccessValue(item.details)}))}));}
}
