import fs from "node:fs";
import path from "node:path";
import {afterEach,describe,expect,it} from "vitest";
import {antigravityBinary,antigravityEnvironment,antigravityHome,antigravityTaskEnvironment} from "../../src/server/antigravity-environment.js";

const roots:string[]=[];
afterEach(()=>{delete process.env.CLAUDEX_WORKHOUSE_ANTIGRAVITY_BINARY;for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});

describe("Antigravity isolated runtime environment",()=>{
  it("prefers the managed agy binary and isolates the official CLI home",()=>{
    const root=fs.mkdtempSync(path.join(process.cwd(),".claudex-agy-env-"));roots.push(root);const binary=path.join(root,"runtime","bin","agy");fs.mkdirSync(path.dirname(binary),{recursive:true});fs.writeFileSync(binary,"#!/bin/sh\n",{mode:0o700});
    const config={root,dataRoot:root,dataDir:path.join(root,"data")} as any;
    expect(antigravityBinary(config)).toBe(binary);
    const home=antigravityHome(config),env=antigravityEnvironment(config);
    expect(home).toBe(path.join(root,"data","provider-auth","antigravity-home"));expect(fs.statSync(home).mode&0o777).toBe(0o700);expect(env.HOME).toBe(home);expect(env.AGY_CLI_DISABLE_AUTO_UPDATE).toBe("true");
  });
  it("creates a task-scoped MCP config while preserving the shared OAuth home and servers",()=>{
    const root=fs.mkdtempSync(path.join(process.cwd(),".claudex-agy-task-env-"));roots.push(root);const config={root,dataRoot:root,dataDir:path.join(root,"data")} as any,shared=antigravityHome(config),runtime=path.join(shared,".gemini","antigravity-cli"),settings=path.join(shared,".gemini","config");
    fs.mkdirSync(runtime,{recursive:true});fs.writeFileSync(path.join(runtime,"antigravity-oauth-token"),"token");fs.mkdirSync(settings,{recursive:true});fs.writeFileSync(path.join(settings,"config.json"),"{}");fs.writeFileSync(path.join(settings,"mcp_config.json"),JSON.stringify({mcpServers:{existing:{url:"http://127.0.0.1:9/mcp"}}}));
    const env=antigravityTaskEnvironment(config,path.join(root,"task"),3410,"antigravity:task-1",undefined,"managed-secret"),home=String(env.HOME),mcp=JSON.parse(fs.readFileSync(path.join(home,".gemini","config","mcp_config.json"),"utf8"));
    expect(fs.realpathSync(path.join(home,".gemini","antigravity-cli"))).toBe(fs.realpathSync(runtime));
    expect(mcp.mcpServers.existing).toBeTruthy();expect(mcp.mcpServers.claudex_workhouse_emotion).toEqual({url:"http://127.0.0.1:3410/mcp/antigravity",headers:{"X-Claudex-Workhouse-Task-Id":"antigravity:task-1","X-Claudex-Workhouse-Runtime-Profile":"default"}});expect(mcp.mcpServers["claudex-workhouse"]).toEqual({url:"http://127.0.0.1:3410/mcp/claudex-workhouse",headers:{Authorization:"Bearer ${CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN}","X-Claudex-Workhouse-Task-Id":"${CLAUDEX_WORKHOUSE_CURRENT_TASK_ID}"}});expect(JSON.stringify(mcp)).not.toContain("managed-secret");expect(env.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN).toBe("managed-secret");
  });
  it("adds external servers from a scoped bundle while keeping header secrets out of config",()=>{const root=fs.mkdtempSync(path.join(process.cwd(),".claudex-agy-external-mcp-"));roots.push(root);const config={root,dataRoot:root,dataDir:path.join(root,"data")} as any,file=path.join(root,"bundle.json");fs.writeFileSync(file,JSON.stringify({version:1,taskId:"antigravity:task",servers:[{id:"jina",url:"https://mcp.jina.ai/mcp",headers:{Authorization:"secret"}}]}),{mode:0o600});fs.chmodSync(file,0o600);const env=antigravityTaskEnvironment(config,path.join(root,"task"),3410,"antigravity:task",undefined,undefined,file),mcp=JSON.parse(fs.readFileSync(path.join(String(env.HOME),".gemini","config","mcp_config.json"),"utf8"));expect(mcp.mcpServers.jina.headers.Authorization).toBe("${CLAUDEX_WORKHOUSE_EXTERNAL_MCP_0_HEADER_0}");expect(JSON.stringify(mcp)).not.toContain("secret");expect(env.CLAUDEX_WORKHOUSE_EXTERNAL_MCP_0_HEADER_0).toBe("secret");});
  it("keeps conversation emotion-only and browser MCP-free",()=>{const root=fs.mkdtempSync(path.join(process.cwd(),".claudex-agy-profile-mcp-"));roots.push(root);const config={root,dataRoot:root,dataDir:path.join(root,"data")} as any,shared=antigravityHome(config),settings=path.join(shared,".gemini","config");fs.mkdirSync(settings,{recursive:true});fs.writeFileSync(path.join(settings,"mcp_config.json"),JSON.stringify({oauth:{preserved:true},mcpServers:{existing:{url:"https://example.test/mcp"}}}));const conversation=antigravityTaskEnvironment(config,path.join(root,"conversation"),3410,"antigravity:conversation",undefined,"secret",undefined,"conversation"),conversationConfig=JSON.parse(fs.readFileSync(path.join(String(conversation.HOME),".gemini","config","mcp_config.json"),"utf8")),browser=antigravityTaskEnvironment(config,path.join(root,"browser"),3410,"antigravity:browser",undefined,"secret",undefined,"browser"),browserConfig=JSON.parse(fs.readFileSync(path.join(String(browser.HOME),".gemini","config","mcp_config.json"),"utf8"));expect(conversationConfig.oauth).toEqual({preserved:true});expect(Object.keys(conversationConfig.mcpServers)).toEqual(["claudex_workhouse_emotion"]);expect(conversation.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN).toBeUndefined();expect(browserConfig.oauth).toEqual({preserved:true});expect(browserConfig.mcpServers).toEqual({});expect(browser.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN).toBeUndefined();});
  it("does not inherit a parent task's managed-provider identity",()=>{
    const root=fs.mkdtempSync(path.join(process.cwd(),".claudex-agy-parent-env-"));roots.push(root);const config={root,dataRoot:root,dataDir:path.join(root,"data")} as any,previous={task:process.env.CLAUDEX_WORKHOUSE_CURRENT_TASK_ID,url:process.env.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_MCP_URL,token:process.env.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN};
    try{process.env.CLAUDEX_WORKHOUSE_CURRENT_TASK_ID="codex:parent";process.env.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_MCP_URL="http://127.0.0.1:3410/mcp/claudex-workhouse";process.env.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN="parent-secret";const env=antigravityTaskEnvironment(config,path.join(root,"task"),3410,"antigravity:child");expect(env.CLAUDEX_WORKHOUSE_CURRENT_TASK_ID).toBeUndefined();expect(env.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_MCP_URL).toBeUndefined();expect(env.CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN).toBeUndefined();}
    finally{const restore=(name:string,value:string|undefined)=>{if(value===undefined)delete process.env[name];else process.env[name]=value;};restore("CLAUDEX_WORKHOUSE_CURRENT_TASK_ID",previous.task);restore("CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_MCP_URL",previous.url);restore("CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN",previous.token);}
  });
  it("isolates Vertex state and injects the selected Google Cloud execution profile",()=>{
    const root=fs.mkdtempSync(path.join(process.cwd(),".claudex-agy-vertex-env-"));roots.push(root);const config={root,dataRoot:root,dataDir:path.join(root,"data")} as any,credentials=path.join(root,"adc.json"),settings={version:1,backend:"vertex",vertex:{projectId:"sample-project-123",location:"us-central1",credentialsPath:credentials,creditsUrl:""}} as const;
    const env=antigravityTaskEnvironment(config,path.join(root,"task"),3410,"antigravity:vertex-task",settings);
    expect(antigravityHome(config,"vertex")).toBe(path.join(root,"data","provider-auth","antigravity-vertex-home"));
    expect(env.HOME).toBe(path.join(root,"task","antigravity-vertex-home"));expect(env.GOOGLE_CLOUD_PROJECT).toBe("sample-project-123");expect(env.GOOGLE_CLOUD_LOCATION).toBe("us-central1");expect(env.GOOGLE_GENAI_USE_VERTEXAI).toBe("true");expect(env.GOOGLE_APPLICATION_CREDENTIALS).toBe(credentials);
  });
});
