import fs from"node:fs";
import os from"node:os";
import path from"node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { CodexAppServerClient, codexAppServerArgs, codexRuntimeSelection, connectCodexAppServerWithRetry } from "../../src/server/codex/app-server";

afterEach(()=>vi.restoreAllMocks());

describe("Codex app-server initialization retry",()=>{
  it("does not bypass provider hook trust or inject user-home configuration",()=>{expect(codexAppServerArgs({})).toEqual(["app-server","--stdio"]);const joined=codexAppServerArgs({CLAUDEX_WORKHOUSE_ROOT:"/srv/claudex-workhouse"}).join(" ");expect(joined).not.toContain("hook");expect(joined).not.toContain("CODEX_HOME");expect(joined).not.toContain("/volume1/");});
  it("coexists with managed-provider tools in default tasks",()=>{expect(codexAppServerArgs({CLAUDEX_WORKHOUSE_ROOT:"/srv/claudex-workhouse"}).join(" ")).not.toContain("mcp_servers.claudex_workhouse");const args=codexAppServerArgs({CLAUDEX_WORKHOUSE_ROOT:"/srv/claudex-workhouse",CLAUDEX_WORKHOUSE_RUNTIME_PROFILE:"default",CLAUDEX_WORKHOUSE_CURRENT_TASK_ID:"codex:deck:test",CLAUDEX_WORKHOUSE_EMOTION_MCP_URL:"http://127.0.0.1:3999/mcp/codex",CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN:"secret",CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_MCP_URL:"http://127.0.0.1:3999/mcp/claudex-workhouse"}),joined=args.join(" ");expect(joined).toContain("mcp_servers.claudex_workhouse.url");expect(joined).toContain("mcp_servers.claudex_workhouse_emotion.url");expect(joined).toContain("127.0.0.1:3999/mcp/codex");expect(joined).toContain("bearer_token_env_var");expect(joined).toContain("env_http_headers");expect(joined).toContain("tool_timeout_sec=130");expect(joined).not.toContain("secret");});
  it("keeps conversation workers emotion-only and free of project instructions",()=>{const joined=codexAppServerArgs({CLAUDEX_WORKHOUSE_RUNTIME_PROFILE:"conversation",CLAUDEX_WORKHOUSE_CURRENT_TASK_ID:"codex:deck:test",CLAUDEX_WORKHOUSE_EMOTION_MCP_URL:"http://127.0.0.1:3410/mcp/codex",CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN:"secret"}).join(" ");expect(joined).toContain("project_doc_max_bytes=0");expect(joined).toContain("mcp_servers={}");expect(joined).toContain("mcp_servers.claudex_workhouse_emotion.url");expect(joined).not.toContain("mcp_servers.claudex_workhouse.url");});
  it("keeps browser composition workers free of every MCP server",()=>{const joined=codexAppServerArgs({CLAUDEX_WORKHOUSE_RUNTIME_PROFILE:"browser",CLAUDEX_WORKHOUSE_CURRENT_TASK_ID:"codex:deck:test",CLAUDEX_WORKHOUSE_EMOTION_MCP_URL:"http://127.0.0.1:3410/mcp/codex"}).join(" ");expect(joined).toContain("project_doc_max_bytes=0");expect(joined).toContain("mcp_servers={}");expect(joined).not.toContain("mcp_servers.claudex_workhouse_emotion");expect(joined).not.toContain("mcp_servers.claudex_workhouse.url");});
  it("rejects non-loopback, mismatched, and unscoped emotion injection",()=>{for(const env of[{CLAUDEX_WORKHOUSE_CURRENT_TASK_ID:"codex:deck:test",CLAUDEX_WORKHOUSE_EMOTION_MCP_URL:"https://127.0.0.1:3410/mcp/codex"},{CLAUDEX_WORKHOUSE_CURRENT_TASK_ID:"codex:deck:test",CLAUDEX_WORKHOUSE_EMOTION_MCP_URL:"http://127.0.0.1:3410/mcp/grok"},{CLAUDEX_WORKHOUSE_EMOTION_MCP_URL:"http://127.0.0.1:3410/mcp/codex"}])expect(codexAppServerArgs(env).join(" ")).not.toContain("claudex_workhouse_emotion");});
  it("requires the server-provided managed endpoint",()=>{expect(()=>codexAppServerArgs({CLAUDEX_WORKHOUSE_CURRENT_TASK_ID:"codex:deck:test",CLAUDEX_WORKHOUSE_MANAGED_PROVIDER_TOKEN:"secret"})).toThrow("MANAGED_PROVIDER_MCP_URL");});
  it("injects external MCP config from a scoped bundle without exposing header values in argv",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"codex-mcp-")),file=path.join(root,"bundle.json"),env:NodeJS.ProcessEnv={CLAUDEX_WORKHOUSE_CURRENT_TASK_ID:"codex:deck:test",CLAUDEX_WORKHOUSE_EXTERNAL_MCP_BUNDLE_FILE:file};try{fs.writeFileSync(file,JSON.stringify({version:1,taskId:"codex:deck:test",servers:[{id:"exa",url:"https://mcp.exa.ai/mcp",headers:{"X-API-Key":"private-key"}}]}),{mode:0o600});fs.chmodSync(file,0o600);const joined=codexAppServerArgs(env).join(" ");expect(joined).toContain("mcp_servers.exa.url");expect(joined).toContain("env_http_headers");expect(joined).not.toContain("private-key");expect(env.CLAUDEX_WORKHOUSE_EXTERNAL_MCP_0_HEADER_0).toBe("private-key");}finally{fs.rmSync(root,{recursive:true,force:true});}});
  it("selects a managed Codex binary from the mutable data root",()=>{
    const appRoot=fs.mkdtempSync(path.join(os.tmpdir(),"codex-app-root-")),dataRoot=fs.mkdtempSync(path.join(os.tmpdir(),"codex-data-root-")),binary=path.join(dataRoot,"runtime","codex-bin","codex");
    try{fs.mkdirSync(path.dirname(binary),{recursive:true});fs.writeFileSync(binary,"fixture");expect(codexRuntimeSelection(appRoot,{CLAUDEX_WORKHOUSE_DATA_ROOT:dataRoot})).toEqual({binary,source:"managed"});}
    finally{fs.rmSync(appRoot,{recursive:true,force:true});fs.rmSync(dataRoot,{recursive:true,force:true});}
  });
  it("selects the managed Windows executable from the mutable data root",()=>{
    const appRoot="D:\\Workhouse Runtime",dataRoot="C:\\Users\\Alice\\AppData\\Local\\Claudex Workhouse",binary=path.win32.join(dataRoot,"runtime","codex-bin","codex.exe");
    vi.spyOn(fs,"existsSync").mockImplementation(value=>String(value)===binary);
    expect(codexRuntimeSelection(appRoot,{CLAUDEX_WORKHOUSE_DATA_ROOT:dataRoot},"win32")).toEqual({binary,source:"managed"});
  });
  it("fails closed instead of searching PATH when a Windows runtime is absent",()=>{
    const dataRoot="C:\\Users\\Alice\\AppData\\Local\\Claudex Workhouse";
    const selection=codexRuntimeSelection("D:\\Workhouse Runtime",{CLAUDEX_WORKHOUSE_DATA_ROOT:dataRoot},"win32");
    expect(selection).toEqual({binary:null,source:"unavailable"});
  });
  it("retries one clean client after an initialize timeout",async()=>{const timeout=Object.assign(new Error("Codex app-server initialize timed out."),{code:"APP_SERVER_TIMEOUT"}),client={alive:true},retries:number[]=[];const connect=vi.spyOn(CodexAppServerClient,"connect").mockRejectedValueOnce(timeout).mockResolvedValueOnce(client as any);expect(await connectCodexAppServerWithRetry("/tmp",{timeoutMs:10,secondTimeoutMs:20,retryDelayMs:0,onRetry:(_error,attempt)=>retries.push(attempt)})).toBe(client);expect(connect).toHaveBeenNthCalledWith(1,"/tmp",10);expect(connect).toHaveBeenNthCalledWith(2,"/tmp",20);expect(retries).toEqual([1]);});
  it("does not retry unrelated request failures",async()=>{const failure=Object.assign(new Error("Codex app-server thread/resume timed out."),{code:"APP_SERVER_TIMEOUT"}),connect=vi.spyOn(CodexAppServerClient,"connect").mockRejectedValue(failure);await expect(connectCodexAppServerWithRetry("/tmp",{retryDelayMs:0})).rejects.toBe(failure);expect(connect).toHaveBeenCalledTimes(1);});
  it("retries the sqlite state runtime lock contention that kills concurrent cold starts",async()=>{const contention=new Error("Codex app-server exited (1). Error: failed to initialize sqlite state runtime under /home/u/.codex: failed to initialize state runtime at /home/u/.codex"),client={alive:true},retries:number[]=[];const connect=vi.spyOn(CodexAppServerClient,"connect").mockRejectedValueOnce(contention).mockRejectedValueOnce(contention).mockResolvedValueOnce(client as any);expect(await connectCodexAppServerWithRetry("/tmp",{timeoutMs:10,secondTimeoutMs:20,retryDelayMs:0,onRetry:(_error,attempt)=>retries.push(attempt)})).toBe(client);expect(connect).toHaveBeenCalledTimes(3);expect(retries).toEqual([1,2]);});
  it("surfaces a state runtime failure that outlives every attempt",async()=>{const contention=new Error("Codex app-server exited (1). Error: failed to initialize state runtime at /home/u/.codex"),connect=vi.spyOn(CodexAppServerClient,"connect").mockRejectedValue(contention);await expect(connectCodexAppServerWithRetry("/tmp",{retryDelayMs:0})).rejects.toBe(contention);expect(connect).toHaveBeenCalledTimes(3);});
  it("notifies a turn waiter when the app-server exits after a request started",()=>{const client:any=Object.create(CodexAppServerClient.prototype),closed=vi.fn();client.pending=new Map();client.onClose=closed;(client as any).failAll(new Error("app-server exited"));expect(closed).toHaveBeenCalledWith(expect.objectContaining({message:"app-server exited"}));});
});
