import { describe,expect,it } from "vitest";
import { CollaborationStore } from "../../src/web/collaboration-store.js";

describe("CollaborationStore",()=>{
  it("merges stale snapshots without regressing state and inserts a follow-up run directly from run/started",()=>{
    const store=new CollaborationStore();let state:any;const unsubscribe=store.subscribe(value=>state=value);
    store.snapshot({revision:5,session:{id:"c",revision:5,status:"running",metadata:{}},runs:[],participants:[]});
    expect(store.snapshot({revision:4,session:{id:"c",revision:4,status:"completed"},runs:[]})).toBe(true);expect(state.detail.session.status).toBe("running");
    const result=store.event({type:"run/started",revision:6,sequence:2,runId:"r",collaborationSessionId:"c",participantId:"p",generation:1,timestamp:"now",metadata:{providerTaskId:"task",sequence:3,round:2,purpose:"debate-turn"}});
    expect(result).toEqual({applied:true,gap:false});expect(state.detail.runs[0]).toMatchObject({id:"r",providerTaskId:"task",status:"running",sequence:3,round:2});expect(state.revision).toBe(6);unsubscribe();
  });
  it("uses event sequence rather than aggregate DB revision to detect a replay gap",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:2,session:{id:"c",revision:2,status:"running",metadata:{}},runs:[]});expect(store.event({type:"collaboration/status",revision:5,sequence:1,metadata:{status:"running"}}).gap).toBe(false);expect(store.event({type:"collaboration/status",revision:9,sequence:2,metadata:{status:"running"}}).gap).toBe(false);expect(state.gap).toBe(false);expect(store.event({type:"collaboration/status",revision:10,sequence:4,metadata:{status:"running"}}).gap).toBe(true);});

  it("applies an ordered terminal event even when its DB revision trails the latest snapshot",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:20,session:{id:"c",revision:20,status:"running",metadata:{}},runs:[{id:"r",status:"running",generation:1,providerTaskId:"codex:task"}]});const result=store.event({type:"run/completed",revision:12,sequence:1,runId:"r",generation:1,metadata:{status:"completed"}});expect(result).toEqual({applied:true,gap:false});expect(state.detail.runs[0].status).toBe("completed");expect(state.revision).toBe(20);});

  it("does not let a same-revision incomplete snapshot erase newer output or continuation",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:8,session:{id:"c",revision:8,status:"completed",outcome:"turn-limit",maxTurnsPerParticipant:5,metadata:{conversationFlow:"automatic",automaticContinuation:true,waitingForUser:true}},runs:[{id:"r",status:"completed",generation:1,providerTaskId:"task"}],messages:[{id:"m"}],runOutputs:{r:"완성 출력"},continuation:{available:true,canAddRounds:true,canSubmitUserInput:true}});store.snapshot({revision:8,session:{id:"c",revision:8,status:"running",metadata:{}},runs:[],messages:[],runOutputs:{}});expect(state.detail.session.status).toBe("completed");expect(state.detail.runs).toHaveLength(1);expect(state.detail.runOutputs.r).toBe("완성 출력");expect(state.detail.continuation).toMatchObject({available:true,canAddRounds:true,canSubmitUserInput:true});});

  it("uses a stale consistent snapshot to fill missing committed output without replacing newer live state",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:30,session:{id:"c",revision:30,status:"running",currentStep:"turn-3",metadata:{currentRound:2}},runs:[{id:"r1",status:"running",generation:1,providerTaskId:"task-1"},{id:"r2",status:"running",generation:2,providerTaskId:"task-2"}],runOutputs:{}});store.snapshot({revision:20,session:{id:"c",revision:20,status:"running",currentStep:"turn-2",metadata:{currentRound:1}},runs:[{id:"r1",status:"completed",generation:1,providerTaskId:"task-1"}],runOutputs:{r1:"확정 출력"}});expect(state.revision).toBe(30);expect(state.detail.session.currentStep).toBe("turn-3");expect(state.detail.runs.find((run:any)=>run.id==="r1").status).toBe("completed");expect(state.detail.runs.find((run:any)=>run.id==="r2").status).toBe("running");expect(state.detail.runOutputs.r1).toBe("확정 출력");});

  it("derives the continuation transition directly from terminal collaboration events",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:20,session:{id:"c",revision:20,status:"running",outcome:null,maxTurnsPerParticipant:5,metadata:{conversationFlow:"automatic",automaticContinuation:false,waitingForUser:false}},runs:[]});store.event({type:"collaboration/completed",revision:25,sequence:1,metadata:{status:"completed",outcome:"turn-limit",currentStep:"continuation-choice",maxTurnsPerParticipant:5,sessionMetadata:{automaticContinuation:true,waitingForUser:true}}});expect(state.detail.continuation).toMatchObject({available:true,canAddRounds:true,canSubmitUserInput:true,reason:"turn-limit"});});

  it("merges an optimistic message into its server message by source id",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:1,session:{id:"c",revision:1,status:"running",metadata:{}},runs:[],messages:[{id:"temporary",clientId:"request-1",status:"sending",contentRef:"hello"}]});store.snapshot({revision:2,session:{id:"c",revision:2,status:"running",metadata:{}},runs:[],messages:[{id:"server",sourceMessageId:"request-1",status:"sent",contentRef:"hello"}]});expect(state.detail.messages).toEqual([{id:"server",clientId:"request-1",sourceMessageId:"request-1",status:"sent",contentRef:"hello"}]);});

  it("discards a previous run generation while advancing the SSE cursor",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:5,session:{id:"c",revision:5,status:"running",metadata:{}},runs:[{id:"r",status:"running",generation:2}]});expect(store.event({type:"run/failed",revision:6,sequence:1,runId:"r",generation:1,metadata:{status:"failed"}})).toEqual({applied:false,gap:false});expect(state.sequence).toBe(1);expect(state.detail.runs[0].status).toBe("running");});

  it("drops a previous controller generation after recovery",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:5,session:{id:"c",revision:5,status:"running",controllerGeneration:3,metadata:{}},runs:[]});expect(store.event({type:"collaboration/status",revision:6,sequence:1,generation:2,metadata:{status:"failed"}}).applied).toBe(false);expect(state.detail.session.status).toBe("running");expect(state.sequence).toBe(1);});

  it("deduplicates repeated runs, participants, messages, and avatar states in a snapshot",()=>{const store=new CollaborationStore();let state:any;store.subscribe(value=>state=value);store.snapshot({revision:1,session:{id:"c",revision:1,status:"running",metadata:{}},runs:[{id:"r",status:"queued",generation:1},{id:"r",status:"running",generation:1}],participants:[{id:"p",status:"queued"},{id:"p",status:"running"}],messages:[{id:"m",status:"sending"},{id:"m",status:"sent"}],avatarStates:[{participantId:"p",version:1},{participantId:"p",version:2}]});expect(state.detail.runs).toEqual([{id:"r",status:"running",generation:1}]);expect(state.detail.participants).toEqual([{id:"p",status:"running"}]);expect(state.detail.messages).toEqual([{id:"m",status:"sent"}]);expect(state.detail.avatarStates).toEqual([{participantId:"p",version:2}]);});
});
