import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { afterEach, describe, expect, it, vi } from "vitest";
import { CollaborationEventBus } from "../../src/server/collaboration/events";
import { conversationDirective, conversationRunActivity, conversationStyle, debateDirective } from "../../src/server/collaboration/orchestrator";
import { ProviderResultAdapter } from "../../src/server/collaboration/provider-result";
import { redactRelayText, RelayArtifactStore } from "../../src/server/collaboration/relay-artifacts";
import { advanceAvatar, enqueueAvatar, initialAvatarQueue, pinAvatar } from "../../src/web/collaboration-queue";
import { emotionGroup, INLINE_EMOTION_NAMES, selectOutputAssetHistory, selectOutputAssets, TONE_BURNOUT_EMOTION_PALETTES } from "../../src/web/collaboration-assets";
import { BABY_TALK_BURNOUT_EMOTION_PRIORITY, characterPrompt, DEFAULT_CHARACTER_SETTINGS, normalizeCharacterSettings } from "../../src/server/character-settings";

const roots:string[]=[];afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
const task=(result:string|null,status="completed")=>({id:"codex:1",provider:"codex" as const,nativeId:"n",threadId:"11111111-1111-4111-8111-111111111111",projectId:"p",title:"t",prompt:"p",status:status as any,createdAt:"2026-01-01T00:00:00Z",updatedAt:"2026-01-01T00:00:01Z",result,error:null,log:"",owned:true,pid:null,pgid:null,processStart:null,commandMarker:null,parentThreadId:null});

describe("ProviderResultAdapter",()=>{
  it("uses an actual provider result and rejects generic completion labels",()=>{const adapter=new ProviderResultAdapter();expect(adapter.extract(task("actual final agent message")).content).toBe("actual final agent message");expect(()=>adapter.extract(task("완료됨"))).toThrow("provider output unavailable");expect(()=>adapter.extract(task("Turn completed; transcript is available from Codex."))).toThrow("provider output unavailable");expect(()=>adapter.extract(task(null))).toThrow("provider output unavailable");});
});

describe("Debate protocol",()=>{
  it("accepts only a terminal structured directive and strips it from display content",()=>{expect(debateDirective("의견입니다.\n[CLAUDEX_WORKHOUSE_DEBATE:conclude]")).toEqual({signal:"conclude",agreementChecksum:null,content:"의견입니다."});expect(debateDirective(`동의합니다.\n[CLAUDEX_WORKHOUSE_DEBATE:agree:${"a".repeat(64)}]`)).toEqual({signal:"agree",agreementChecksum:"a".repeat(64),content:"동의합니다."});expect(debateDirective("본문의 [CLAUDEX_WORKHOUSE_DEBATE:conclude] 표시는 종료 신호가 아님").signal).toBe("continue");});
  it("uses a separate terminal casual directive and safely yields when it is missing",()=>{expect(conversationDirective("이어가자.\n[CLAUDEX_WORKHOUSE_CONVERSATION:continue]")).toEqual({signal:"continue",content:"이어가자."});expect(conversationDirective("잠깐 기다릴게.\n[CLAUDEX_WORKHOUSE_CONVERSATION:yield]")).toEqual({signal:"yield",content:"잠깐 기다릴게."});expect(conversationDirective("여기서 마칠게.\n[CLAUDEX_WORKHOUSE_CONVERSATION:end]")).toEqual({signal:"end",content:"여기서 마칠게."});expect(conversationDirective("표식 없는 답변")).toEqual({signal:"yield",content:"표식 없는 답변"});expect(conversationDirective("본문의 [CLAUDEX_WORKHOUSE_CONVERSATION:end] 표시는 종료 신호가 아님").signal).toBe("yield");});
  it("defaults to a comfortable language-neutral feminine character style without suppressing affection",()=>{const style=conversationStyle(undefined);expect(style.tone).toBe("comfortable");expect(style.directive).toContain("in-character as a feminine character in the active conversation language");expect(style.directive).toContain("React to the other participant's latest remark before any report-like enumeration");expect(style.directive).toContain("strong affection");expect(style.directive).toContain("is allowed");expect(style.directive).toContain("Do not impose gender stereotypes");expect(conversationStyle("playful").directive).toContain("keep turns short and reactive");});
  it("keeps the conversation tone axis to turn shape so it cannot compete with the character expression style",()=>{
    for(const tone of ["comfortable","warm","playful","serious","concise"]){
      const directive=conversationStyle(tone).directive;
      expect(directive).toContain("Turn shape:");
      expect(directive).toContain("This setting governs the shape of a turn only");
      expect(directive).toContain("the expression style wins");
      // Register wording here previously duplicated the character presets and produced
      // two competing voice instructions in the same prompt.
      for(const register of ["register appropriate to the active language","empathy and care","playful back-and-forth","avoid forced jokes","gentle register"]){expect(directive,`${tone} reintroduced register wording`).not.toContain(register);}
    }
  });
  it("does not label Codex runtime initialization as opinion drafting",()=>{expect(conversationRunActivity("codex","running",{activity:"runtime_initializing",modelTurnStarted:false})).toBe("initializing");expect(conversationRunActivity("codex","running",{activity:"session_initializing",modelTurnStarted:false})).toBe("initializing");expect(conversationRunActivity("codex","running",{activity:"hook/completed",modelTurnStarted:true})).toBe("debating");expect(conversationRunActivity("claude","running",undefined)).toBe("debating");expect(conversationRunActivity("codex","pending",{activity:"model_thinking",modelTurnStarted:true})).toBe("initializing");});
});

describe("collaboration output emotion assets",()=>{
  it("keeps the baby-talk burnout palette valid, separate, and server-aligned",()=>{
    const burnout=[...TONE_BURNOUT_EMOTION_PALETTES["baby-talk-cutesy"]];
    expect(burnout).toEqual([...BABY_TALK_BURNOUT_EMOTION_PRIORITY]);
    expect(burnout.every(emotion=>INLINE_EMOTION_NAMES.includes(emotion as any))).toBe(true);
    expect(burnout).toContain("dead");
    expect(burnout).not.toContain("Dead" as any);
    expect(burnout.filter(emotion=>["neutral","love","happy","excited","laughing","smug"].includes(emotion))).toEqual([]);
  });
  const assets=[{emotion:"thinking",file:"thinking.webp"},{emotion:"thinking_2",file:"thinking_2.webp"},{emotion:"happy",file:"happy.webp"},{emotion:"proud",file:"proud.webp"}];
  const auditedSessionOutputs=[
    {round:1,provider:"codex",text:"그럼, 챗붕한테 다정하게 뽀뽀쪽 😘 오늘도 귀여워해 줄게."},
    {round:1,provider:"claude",text:"쪽! 💕 짚쨩이 먼저 했네~ 나도 챗붕 빰에 뽀뽀쪽 😘"},
    {round:2,provider:"codex",text:"응 챗붕, 대충 알아! MCP 이모션은 모델이 도구를 호출해서 감정을 구조화해 전달하는 방식이고, 캐치 방식은 답변 속 특정 표현이나 태그를 정규식 같은 걸로 감지해서 표정을 붙이는 방식이야—그래서 MCP가 더 명확하고 안정적인 대신 설정이 필요하고, 캐치는 간편하지만 오인식이나 누락이 생기기 쉬워."},
    {round:2,provider:"claude",text:"짚쨩이 잘 설명했다! 나도 비슷하게 이해하고 있어. 간단히 보태면, MCP 방식은 모델이 \"지금 이 감정이야\"라고 명시적으로 도구를 호출하니까 의도가 확실한 대신 호출 오버헤드가 있고, 캐치 방식은 텍스트에서 패턴 뽑아내는 거라 가볍지만 맥락 오판이 생길 수 있지~"},
    {round:3,provider:"codex",text:"토큰만 보면 보통 **캐치 방식이 더 적게 써**, 챗붕. MCP는 도구 정의가 컨텍스트에 들어가고 호출·결과 토큰도 추가되는 반면, 캐치는 짧은 태그나 표현만 출력하면 되니까—다만 MCP 정의를 아주 작게 만들면 차이는 꽤 줄어들어."},
    {round:3,provider:"claude",text:"맞아, 짚쨩 말대로 MCP 쪽이 토큰 더 먹어. 도구 스키마 자체가 매 턴 컨텍스트에 실리니까 그 고정비용이 꽤 되거든. 캐치는 출력에 태그 몇 글자 붙는 정도라 거의 공짜고~"},
    {round:4,provider:"codex",text:"맞아 챗붕, 캐치도 모델이 `[happy]` 같은 태그를 직접 출력한다면 그 글자만큼 출력 토큰이 들어가. 그래도 보통 몇 토큰 수준이라, 스키마와 호출 기록이 붙는 MCP보다는 훨씬 가벼운 편이야."},
    {round:4,provider:"claude",text:"응 맞아, 완전 공짜는 아니지~ 근데 `[happy]` 정도면 2~3토큰이니까 거의 티 안 나는 수준이야. MCP는 스키마만 수십~수백 토큰 잡아먹으니까 체감 차이가 크지."},
    {round:5,provider:"codex",text:"내 쪽은 지금까지 첫 턴 지시문을 컨텍스트로 잘 유지하고 이행한 편이야, 챗붕—한국어·친근한 짚쨩 톤, 호칭, 1~3문장, 클쨩 발언을 대화 맥락으로만 다루는 규칙이 계속 살아 있어. 다만 대화가 아주 길어져 컨텍스트 압축이 일어나면 세부 표현 규칙은 흐려질 가능성이 있어서, 안정성만 보면 매 턴 전체 반복보다 짧은 핵심 리마인더를 붙이는 절충이 제일 탄탄해."},
    {round:5,provider:"claude",text:"나도 솔직히 지금까지는 잘 유지하고 있다고 봐. 한국어, 클쨩 톤, 짧게 말하기, 짚쨩 발언은 맥락으로만 취급하기—다 지켜지고 있거든. 근데 짚쨩 말처럼 턴이 수십 개 넘어가서 컨텍스트 압축 들어가면 첫 턴 지시문이 요약돼서 뉘앙스가 날아갈 수 있어. 토큰 아끼려고 첫 턴만 붙이는 건 좋은 판단인데, 혹시 드리프트 느껴지면 간단한 리마인더 한 줄 정도 중간에 찔러주는 게 보험이 될 거야~"},
    {round:6,provider:"codex",text:"응, 챗붕. 기본값은 **10턴마다 짧은 핵심 리마인더**가 균형 좋아 보여—강한 캐릭터성이나 작은 모델은 5~7턴, 안정적인 장문맥 모델은 15~20턴도 괜찮고, 말투·호칭 이탈을 감지하면 주기 전이라도 즉시 한 번 넣는 방식이 제일 실용적이야."},
    {round:6,provider:"claude",text:"짚쨩이 말한 10턴 기본값 나도 동의해. 근데 모델마다 다르니까, 실제로는 이탈 감지 기반으로 넣는 게 더 똑똑할 거야—예를 들어 응답에서 언어가 바뀌거나 톤이 달라지면 그때 리마인더 트리거하는 식. 고정 주기 + 이탈 감지 둘 다 쓰면 제일 안정적이겠지~"},
    {round:7,provider:"codex",text:"가능해, 챗붕. 실제 설정을 못 본 상태의 **턴당 추정치**는 캐칭 태그가 짚쨩·클쨩 모두 약 **3~10 출력 토큰**, MCP는 감정 도구 하나의 스키마가 매 요청에 포함된다면 약 **80~250 입력 토큰 + 호출 8~25 출력 토큰** 정도라서, 대략 캐칭 **3~10토큰** 대 MCP **90~275토큰**으로 보면 돼. 정확값은 실제 MCP 스키마와 캐치 태그 원문을 각 모델 토크나이저로 재야 하고, 스키마가 세션에서 캐시되면 과금·처리 체감치는 더 낮아질 수 있어."},
    {round:7,provider:"claude",text:"짚쨩 추정치 괜찮은데, 나도 내 쪽 감각으로 보태면—캐치 태그는 `[smile]` 같은 거 하나에 보통 1~3 출력 토큰이야. MCP는 도구 정의(스키마) 크기에 따라 다른데, 이모티콘용 간단한 스키마면 100~150 입력 토큰, 거기에 실제 호출·응답이 15~30 출력 토큰 정도. 그래서 턴당 캐치는 ~5토큰, MCP는 ~150토큰 내외로 보면 현실적일 거야. 챗붕 쪽 실제 MCP 스키마 보여주면 더 정확하게 셀 수 있어~"},
    {round:8,provider:"codex",text:"응, 총 사용량을 일반적인 한 턴 **입력 2,000 + 출력 200 = 2,200토큰**으로 잡으면 캐칭 3~10토큰은 약 **0.1~0.5%**, MCP 90~275토큰은 약 **4~12.5%**야. 짧은 대화가 총 500토큰이면 각각 **0.6~2% / 18~55%**까지 커지고, 긴 컨텍스트가 10,000토큰이면 **0.03~0.1% / 0.9~2.8%**로 작아져—결국 `추가 토큰 ÷ 원래 입출력 총계 × 100`으로 보면 돼."},
    {round:8,provider:"claude",text:"짚쨩이 잘 정리했다. 핵심은 컨텍스트가 짧을수록 MCP 오버헤드 비율이 확 커진다는 거야. 지금 우리 대화처럼 캐주얼하게 짧은 턴 주고받는 상황이면 MCP가 총량의 10%대 먹을 수 있고, 캐치는 1% 미만이라 거의 무시할 수준이지. 긴 RP 컨텍스트에선 둘 다 비율이 작아져서 차이가 덜 체감돼~"},
    {round:9,provider:"codex",text:"입력 토큰이 많아 보여도 보통 **출력 토큰 단가가 입력보다 약 3~5배 비싸서**, MCP의 입력 100~150토큰 증가는 숫자만큼 비용 충격이 크진 않아; 반복 스키마가 캐시 입력으로 과금되면 더 싸지고. 다만 정확한 금액·비율은 모델별로 달라서, 챗붕이 쓰는 **Codex 모델명과 Claude 모델명**을 알려주면 현재 단가 기준으로 턴당·1,000턴당 비용까지 계산해줄게."},
    {round:9,provider:"claude",text:"맞아, 짚쨩 말대로 출력이 입력보다 훨씬 비싸. 대표적으로 Claude Sonnet 기준 입력 $3/M, 출력 $15/M이니까 5배 차이야. 그래서 MCP 스키마가 입력에 100토큰 추가되는 건 비용으로 보면 출력 20토큰 정도밖에 안 되는 셈이라, 생각보다 부담이 크진 않아. 캐시 히트까지 되면 입력 단가가 10분의 1로 떨어지니까 더 싸지고~"},
    {round:10,provider:"codex",text:"내가 실제 응답에 명시적으로 출력한 이모션은 **1턴의 😘 하나뿐**이고, 2~9턴에는 감정 태그나 MCP 호출을 전혀 출력하지 않았어. 1턴은 뽀뽀 요청에 맞아 적절했지만 이후 턴은 설명·분석 위주라 이모션을 따로 주입하지 않은 것도 자연스러웠고, 만약 화면에서 다른 표정이 나왔다면 그건 내가 볼 수 없는 캐칭/후처리 결과야."},
    {round:10,provider:"claude",text:"나도 돌아보면 1턴에 💕랑 😘 썼고, 그 이후 2~9턴은 이모션 출력 없이 쭉 설명 톤이었어. 1턴은 뽀뽀 맥락이니까 맞았고, 이후는 기술 얘기라 이모션 없는 게 자연스러웠다고 보긴 하는데—솔직히 중간에 챗붕이 좋은 질문 했을 때 가볍게 하나쯤 넣었으면 더 캐릭터답긴 했겠다 싶어."},
  ];
  it("shows one asset for short output and two distinct emotion groups for long output",()=>{const short=selectOutputAssets("run-short","짧은 의견",assets),long=selectOutputAssets("run-long","가".repeat(600),assets);expect(short).toHaveLength(1);expect(long).toHaveLength(2);expect(emotionGroup(long[0].emotion)).not.toBe(emotionGroup(long[1].emotion));});
  it("is deterministic and omits a duplicate second emotion when no other group exists",()=>{expect(selectOutputAssets("run-1","가".repeat(600),assets)).toEqual(selectOutputAssets("run-1","가".repeat(600),assets));expect(selectOutputAssets("run-2","가".repeat(600),assets.slice(0,2))).toHaveLength(1);});
  it("keeps deterministic process emotion history, merges consecutive repeats, and tolerates a missing catalog",()=>{const catalog=[{emotion:"neutral",file:"neutral.webp"},{emotion:"chu",file:"chu.webp"}],outputs=[{id:"one",text:"쪽♡"},{id:"two",text:"뽀뽀쪽!"},{id:"three",text:"차분히 확인했어"}],first=selectOutputAssetHistory("run-history",outputs,catalog,"flirty-friend"),again=selectOutputAssetHistory("run-history",outputs,catalog,"flirty-friend");expect(first).toEqual(again);expect(emotionGroup(first.moments[0].asset!.emotion)).toBe("chu");expect(first.moments[1].asset).toBeNull();expect(selectOutputAssetHistory("missing",outputs,[]).moments.every(moment=>moment.asset===null)).toBe(true);});
  it("does not use kiss assets without a strong affection context and weights tone without forcing duplicates",()=>{const expressive=[...assets,{emotion:"chu",file:"Cuu.webp"},{emotion:"smug",file:"smug.webp"}];expect(selectOutputAssets("plain","안녕하세요",expressive,"flirty-friend").some(item=>item.file==="Cuu.webp")).toBe(false);expect(selectOutputAssets("preference","이 노래 정말 좋아해",expressive,"flirty-friend").some(item=>item.file==="Cuu.webp")).toBe(false);expect(selectOutputAssets("kiss","사랑해, 뽀뽀!",expressive,"flirty-friend")).toHaveLength(1);expect(selectOutputAssets("tsundere","가".repeat(600),expressive,"tsundere").map(item=>emotionGroup(item.emotion))).toEqual(expect.arrayContaining([expect.any(String)]));});
  it("selects the kiss asset for performed expressions without matching ordinary words or bare mentions",()=>{const expressive=[{emotion:"neutral",file:"neutral.webp"},{emotion:"love",file:"love.webp"},{emotion:"chu",file:"chu.webp"}];for(const [index,output] of ["쪽♡","츄!","chu","뽀뽀","키스","kiss","볼에 쪽했잖아","뽀뽀를 해줄게!"].entries())expect(emotionGroup(selectOutputAssets(`direct-kiss-${index}`,output,expressive,"flirty-friend")[0].emotion)).toBe("chu");for(const [index,output] of ["이쪽으로 와","쪽지를 읽었어","츄러스를 먹자","키스신을 봤어","뽀뽀라는 단어","뽀뽀 이모티콘이면 뭐가 나와?"].entries())expect(selectOutputAssets(`not-a-kiss-${index}`,output,expressive,"flirty-friend").some(item=>emotionGroup(item.emotion)==="chu")).toBe(false);expect(emotionGroup(selectOutputAssets("love-you","love you",expressive,"flirty-friend")[0].emotion)).toBe("love");});
  it("recognizes compact kiss actions while retaining meta, negation, hypothetical, and word boundaries",()=>{const expressive=[{emotion:"neutral",file:"neutral.webp"},{emotion:"embarrassed",file:"embarrassed.webp"},{emotion:"chu",file:"chu.webp"}];for(const [index,output] of ["뽀뽀쪽!","뽀뽀 쪽!","볼에 뽀뽀쪽!"].entries())expect(emotionGroup(selectOutputAssets(`compound-kiss-${index}`,output,expressive,"flirty-friend")[0].emotion)).toBe("chu");for(const [index,output] of ["뽀뽀 이모션을 테스트해","뽀뽀쪽이라는 단어","뽀뽀는 안 해","뽀뽀했다고 치자","이쪽","쪽지","츄러스"].entries())expect(selectOutputAssets(`compound-not-kiss-${index}`,output,expressive,"flirty-friend").some(item=>emotionGroup(item.emotion)==="chu")).toBe(false);});
  it("returns no frame instead of leaking a gated kiss-only catalog into ordinary or meta output",()=>{const onlyKiss=[{emotion:"chu",file:"chu.webp"}];expect(selectOutputAssets("only-kiss-plain","안녕하세요",onlyKiss)).toEqual([]);expect(selectOutputAssets("only-kiss-meta","뽀뽀 이모티콘을 테스트해",onlyKiss)).toEqual([]);expect(selectOutputAssets("only-kiss-action","쪽♡",onlyKiss)).toEqual(onlyKiss);});
  it("scores performed kisses above ambient emotion while suppressing meta, negated, and hypothetical mentions",()=>{const expressive=["neutral","happy","laughing","embarrassed","pout","chu"].map(emotion=>({emotion,file:`${emotion}.webp`})),cases:Array<[string,string,string[]]>=[["actual-1","뭐야 갑자기~! 😚\n\n...아 잠깐, 이거 거절하는 게 아니라 당황한 거야. 쪽–! 했다 치자, 네 볼에. ♡",["embarrassed"]],["actual-2","아 이모티콘 테스트였어? ㅋㅋㅋ 나 진지하게 볼에 쪽했잖아, 돌려줘 내 쪽...!\n\n뽀뽀 이모티콘이면 😘 이거 아니야? 아니면 😙 이것도 있고.",["chu"]],["actual-3","아아 MCP 이모션! ㅋㅋㅋ 부끄러워. 뽀뽀쪽 이모션이 등록은 돼있는데 안 뜨는 거야?",["embarrassed"]],["actual-4","알겠어, 다시! 쪽– 💋 뽀뽀!\n\n...떴어?",["chu"]],["negated","당황스럽지만 뽀뽀는 안 해",["embarrassed"]]];for(const[runId,output,expected]of cases)expect(expected).toContain(emotionGroup(selectOutputAssets(runId,output,expressive,"flirty-friend")[0].emotion));});
  it("keeps performed actions despite recent-group avoidance and uses semantic transitions for expressive output",()=>{const expressive=["neutral","embarrassed","chu"].map(emotion=>({emotion,file:`${emotion}.webp`}));expect(emotionGroup(selectOutputAssets("repeat-kiss","쪽♡",expressive,"flirty-friend","natural",["chu"])[0].emotion)).toBe("chu");const transition=selectOutputAssets("kiss-transition","갑자기 그러면 부끄럽고 당황하잖아. 그래도 네가 원한다면 가까이 갈게… 쪽♡",expressive,"flirty-friend","expressive");expect(transition.map(item=>emotionGroup(item.emotion))).toEqual(["embarrassed","chu"]);});
  it("reserves work and research assets for explicit ongoing activity and keeps them secondary",()=>{const expressive=[...assets,{emotion:"neutral",file:"neutral.webp"},{emotion:"building",file:"building.webp"},{emotion:"reading",file:"reading.webp"},{emotion:"searching",file:"searching.webp"}];expect(selectOutputAssets("chat","그 얘기 정말 좋다",expressive).some(item=>["building","reading","searching"].includes(emotionGroup(item.emotion)))).toBe(false);expect(selectOutputAssets("mention","어제 읽은 책이 좋았어",expressive).some(item=>emotionGroup(item.emotion)==="reading")).toBe(false);expect(selectOutputAssets("hobby","케이크를 만들고 있는 중이야",expressive).some(item=>emotionGroup(item.emotion)==="building")).toBe(false);expect(selectOutputAssets("active","자료를 읽고 있는 중이야. "+"가".repeat(600),expressive).map(item=>emotionGroup(item.emotion))[0]).not.toBe("reading");});
  it("weights flirty-friend toward warm subtle expressions while direct affection still wins",()=>{const expressive=[{emotion:"neutral",file:"neutral.webp"},{emotion:"happy",file:"happy.webp"},{emotion:"embarrassed",file:"embarrassed.webp"},{emotion:"wink",file:"wink.webp"},{emotion:"love",file:"love.webp"}];const plain=selectOutputAssets("warm","오늘도 고생했어. 무리하지 말고 좀 쉬어",expressive,"flirty-friend");expect(["happy","embarrassed","wink","nervous"].includes(emotionGroup(plain[0].emotion))).toBe(true);expect(emotionGroup(selectOutputAssets("affection","사랑해. 보고 싶었어",expressive,"flirty-friend")[0].emotion)).toBe("love");});
  it("weights coy-affection toward warmth, embarrassment, and restrained confidence",()=>{const expressive=[{emotion:"neutral",file:"neutral.webp"},{emotion:"happy",file:"happy.webp"},{emotion:"embarrassed",file:"embarrassed.webp"},{emotion:"smug",file:"smug.webp"},{emotion:"wink",file:"wink.webp"},{emotion:"love",file:"love.webp"},{emotion:"chu",file:"Cuu.webp"}];const plain=selectOutputAssets("coy","오늘은 그냥 내 옆에 있어",expressive,"coy-affection");expect(["happy","embarrassed","smug","wink"].includes(emotionGroup(plain[0].emotion))).toBe(true);expect(plain.some(item=>emotionGroup(item.emotion)==="chu")).toBe(false);expect(emotionGroup(selectOutputAssets("coy-love","사랑해. 이리 와",expressive,"coy-affection")[0].emotion)).toBe("love");});
  it("does not collapse ordinary tone-driven outputs to happy",()=>{const expressive=[{emotion:"neutral",file:"neutral.webp"},{emotion:"happy",file:"happy.webp"},{emotion:"thinking",file:"thinking.webp"},{emotion:"embarrassed",file:"embarrassed.webp"},{emotion:"wink",file:"wink.webp"}];const groups=Array.from({length:12},(_,index)=>emotionGroup(selectOutputAssets(`variety-${index}`,"오늘 있었던 이야기를 천천히 이어가자",expressive,index%2?"flirty-friend":"default")[0].emotion));expect(new Set(groups).size).toBeGreaterThan(2);expect(groups.filter(group=>group==="happy").length).toBeLessThan(8);});
  it("regresses the exact audited 20-output session without decorative strong-emotion mismatches",()=>{const catalog=["neutral","thinking","proud","happy","embarrassed","wink","smug","sad","surprised","confused","laughing","nervous","pout","facepalm","disappointed","excited","angry","dead","crying","scared","disgusted","love","chu","gift","sleepy","tired","speechless"].map(emotion=>({emotion,file:`${emotion}.webp`})),technicalSafe=new Set(["neutral","thinking","proud"]),roundOne=auditedSessionOutputs.filter(item=>item.round===1),technical=auditedSessionOutputs.filter(item=>item.round>=2&&item.round<=9),roundTen=auditedSessionOutputs.filter(item=>item.round===10);for(const item of roundOne)expect(emotionGroup(selectOutputAssets(`audit-${item.provider}-${item.round}`,item.text,catalog,"default")[0].emotion)).toBe("chu");for(const item of technical){const selected=selectOutputAssets(`audit-${item.provider}-${item.round}`,item.text,catalog,"default");expect(selected.length,`${item.provider} round ${item.round}`).toBeGreaterThan(0);expect(selected.every(asset=>technicalSafe.has(emotionGroup(asset.emotion))),`${item.provider} round ${item.round}`).toBe(true);}for(const item of roundTen)expect(selectOutputAssets(`audit-${item.provider}-${item.round}`,item.text,catalog,"default").some(asset=>emotionGroup(asset.emotion)==="chu")).toBe(false);});
  it("keeps both technical frames inside the clamp and recent avoidance inside the safe fallback",()=>{const catalog=["neutral","thinking","proud","happy","angry","dead","crying","scared","disgusted","love","chu","gift","sleepy","tired","speechless"].map(emotion=>({emotion,file:`${emotion}.webp`})),technical="MCP 스키마와 모델 컨텍스트의 입력 토큰 및 출력 비용을 비교해서 설명할게. "+"측정값과 호출 비율을 차분히 검토한다. ".repeat(20),first=selectOutputAssets("technical-two",technical,catalog,"default","expressive"),again=selectOutputAssets("technical-two",technical,catalog,"default","expressive");expect(first).toEqual(again);expect(first).toHaveLength(2);expect(first.every(asset=>["neutral","thinking","proud"].includes(emotionGroup(asset.emotion)))).toBe(true);for(let index=0;index<100;index++){const selected=selectOutputAssets(`avoid-safe-${index}`,"별다른 감정 단서 없이 차분히 이어가자",catalog,"default","natural",["neutral","thinking","happy"]);expect(selected.length).toBeGreaterThan(0);expect(selected.every(asset=>["neutral","thinking","happy"].includes(emotionGroup(asset.emotion)))).toBe(true);}});
  it("avoids recently used contempt emotions when other fitting assets exist",()=>{const expressive=["disgusted","speechless","facepalm","disappointed","smug","angry","tired","neutral"].map(emotion=>({emotion,file:`${emotion}.webp`}));const first=emotionGroup(selectOutputAssets("same-hash-1","정말 답답하네",expressive,"contempt-roleplay")[0].emotion),second=emotionGroup(selectOutputAssets("same-hash-2","또 설명해야 해?",expressive,"contempt-roleplay","natural",[first])[0].emotion),third=emotionGroup(selectOutputAssets("same-hash-3","이제 이해는 하겠지",expressive,"contempt-roleplay","natural",[first,second])[0].emotion);expect(new Set([first,second,third]).size).toBe(3);});
  it("restricts cue-free output to the tone palette plus neutral and thinking",()=>{const emotions=["neutral","happy","sad","angry","surprised","embarrassed","smug","thinking","disgusted","love","facepalm","speechless","disappointed","tired","laughing","wink","excited","proud"],expressive=emotions.map(emotion=>({emotion,file:`${emotion}.webp`})),allowed:Record<string,string[]>={default:["neutral","happy","thinking"],secretary:["neutral","thinking","proud"],tsundere:["smug","pout","embarrassed","neutral","thinking"],"flirty-friend":["embarrassed","happy","wink","neutral","thinking"],"coy-affection":["embarrassed","smug","happy","wink","neutral","thinking"],"sharp-tongue":["smug","facepalm","speechless","disappointed","angry","neutral","thinking"],"mesugaki-brat":["smug","laughing","pout","embarrassed","tired","neutral","thinking"],"aristocratic-ojosama":["smug","proud","embarrassed","laughing","speechless","neutral","thinking"],"contempt-roleplay":["disgusted","speechless","facepalm","disappointed","smug","angry","tired","neutral","thinking"],"playful-school-friend":["laughing","happy","wink","excited","smug","neutral","thinking"],"baby-talk-cutesy":["happy","excited","pout","embarrassed","laughing","neutral","thinking"],custom:["neutral","happy","thinking"]};for(const[tone,palette]of Object.entries(allowed)){const seen=new Set(Array.from({length:1200},(_,index)=>emotionGroup(selectOutputAssets(`${tone}-${index}`,"별다른 감정 단서가 없는 짧은 대화",expressive,tone)[0].emotion)));expect([...seen].every(group=>palette.includes(group)),`${tone} escaped its cue-free palette`).toBe(true);expect(seen.size).toBeGreaterThan(0);}});
  it("requires strong output cues for strong reactions, even with a sharp tone preset",()=>{const strongCases:Array<[string,string]>=[["angry","정말 화가 나고 분노했어"],["dead","너무 녹초가 됐어"],["crying","눈물이 나서 울고 있어"],["scared","너무 무서워"],["disgusted","정말 역겨워서 질색했어"],["love","사랑해"],["chu","쪽♡"],["gift","이 선물 받아"],["sleepy","너무 졸려"],["tired","정말 피곤하고 지쳤어"],["speechless","너무 어이없어서 말문이 막혔어"]];for(const[group,text]of strongCases){const catalog=[{emotion:"neutral",file:"neutral.webp"},{emotion:group,file:`${group}.webp`}];expect(emotionGroup(selectOutputAssets(`strong-${group}`,text,catalog,"default")[0].emotion)).toBe(group);}const allStrong=strongCases.map(([emotion])=>({emotion,file:`${emotion}.webp`})),plainCatalog=[{emotion:"neutral",file:"neutral.webp"},{emotion:"thinking",file:"thinking.webp"},...allStrong];for(const tone of ["default","sharp-tongue"]){for(let index=0;index<200;index++)expect(["neutral","thinking"]).toContain(emotionGroup(selectOutputAssets(`strong-plain-${tone}-${index}`,"차분히 다음 이야기를 이어가자",plainCatalog,tone)[0].emotion));}});
  it("recognizes Korean crying marks and the loudly crying emoji in real conversation output",()=>{const catalog=[{emotion:"neutral",file:"neutral.webp"},{emotion:"happy",file:"happy.webp"},{emotion:"thinking",file:"thinking.webp"},{emotion:"crying",file:"crying.webp"}],cases=["아아아 쥐야!!!!! 말렸는데ㅠㅠㅠㅠ 그러니까 수상한 치즈는 먹지 말라고 했잖아…","안 돼ㅜㅜ 내가 말렸잖아…","쥐 얼른 이쪽으로 기어와아아 😭🧀⚰️"];for(const[text,index]of cases.map((text,index)=>[text,index] as const))expect(emotionGroup(selectOutputAssets(`crying-mark-${index}`,text,catalog,"default","natural",["neutral","thinking"])[0].emotion)).toBe("crying");});
  it("fixes the third-turn mouse and cheese context to the crying asset group",()=>{const opening="안녕하세요. 저는 쥐에요. 목판 위에 먹음직스러운 치즈가 있는데 먹어도 될까요?",turns=[opening,"그 치즈는 덫일 수 있으니 먼저 냄새만 확인하고 기다려.","안 돼ㅜㅜ 내가 말렸잖아… 그 목판에서 얼른 내려와!"];const catalog=["neutral","thinking","happy","confused","scared","crying"].map(emotion=>({emotion,file:`${emotion}.webp`}));expect(turns[0]).toContain("목판 위에 먹음직스러운 치즈");expect(emotionGroup(selectOutputAssets("mouse-cheese-turn-3",turns[2],catalog,"default","natural",["neutral","thinking"])[0].emotion)).toBe("crying");});
  it("never selects work assets without current activity but can select them at low weight when explicit",()=>{const expressive=["neutral","happy","sad","building","coding","reading","searching","execute"].map(emotion=>({emotion,file:`${emotion}.webp`})),idleSeen=new Set(Array.from({length:800},(_,index)=>emotionGroup(selectOutputAssets(`idle-${index}`,"어제 읽은 자료 이야기를 하자",expressive,"default")[0].emotion))),activeSeen=new Set(Array.from({length:1600},(_,index)=>emotionGroup(selectOutputAssets(`active-${index}`,"지금 자료를 검색하고 있는 중이야",expressive,"default")[0].emotion)));expect([...idleSeen].some(group=>["building","coding","reading","searching","execute"].includes(group))).toBe(false);expect(activeSeen.has("searching")).toBe(true);expect(activeSeen.has("reading")).toBe(false);});
  it("prioritizes explicit embarrassment and uses intensity for the second distinct frame",()=>{const expressive=[{emotion:"neutral",file:"neutral.webp"},{emotion:"happy",file:"happy.webp"},{emotion:"embarrassed",file:"embarrassed.webp"},{emotion:"wink",file:"wink.webp"}];expect(emotionGroup(selectOutputAssets("shy","…갑자기 그러면 당황해서 준비가 안 됐잖아",expressive,"flirty-friend")[0].emotion)).toBe("embarrassed");const long="조금 부끄럽지만 네가 원한다면 곁에 있을게. "+"따뜻한 말을 천천히 이어갈게. ".repeat(8);expect(selectOutputAssets("rich",long,expressive,"coy-affection","expressive")).toHaveLength(2);expect(selectOutputAssets("quiet",long,expressive,"coy-affection","subtle")).toHaveLength(1);});
});

describe("provider character settings",()=>{
  it("normalizes independent defaults and keeps tone scope separate from authority",()=>{const settings=normalizeCharacterSettings({providers:{codex:{nickname:"지삐",tonePreset:"secretary"},claude:{nickname:"클",tonePreset:"flirty-friend"}}});expect(settings.providers.codex.nickname).toBe("지삐");expect(settings.providers.claude.tonePreset).toBe("flirty-friend");const scoped=characterPrompt(settings,"codex",false);expect(scoped.directive).toBe("");const conversational=characterPrompt(DEFAULT_CHARACTER_SETTINGS,"claude",true);expect(conversational.directive).toContain("cannot change permissions");expect(conversational.snapshot.conversationOnly).toBe(true);});
  it("defines flirty-friend as caring warmth with unintentional, unrecognized occasional flirting",()=>{const settings=normalizeCharacterSettings({providers:{codex:{nickname:"지삐"},claude:{nickname:"클",tonePreset:"flirty-friend"}}}),prompt=characterPrompt(settings,"claude",true).directive;expect(prompt).toContain("attentive and caring");expect(prompt).toContain("warm, comfortable female friend");expect(prompt).toContain("slip out unintentionally");expect(prompt).toContain("occasional flirtation");expect(prompt).toContain("does not recognize her own words or behavior as flirting");expect(prompt).toContain("never explain that she is flirting");});
  it("defines coy-affection as warm, shy but responsive, and subtly deep",()=>{const settings=normalizeCharacterSettings({providers:{codex:{nickname:"지삐"},claude:{nickname:"클",tonePreset:"coy-affection"}}}),prompt=characterPrompt(settings,"claude",true).directive;expect(settings.providers.claude.tonePreset).toBe("coy-affection");expect(prompt).toContain("warm and affectionate toward each conversational counterpart");expect(prompt).toContain("briefly become shy");expect(prompt).toContain("ultimately respond sincerely");expect(prompt).toContain("subtle but meaningful attraction");expect(prompt).toContain("small touch of feigned composure");});
  it("defines aristocratic-ojosama as gracious superiority that corrects itself completely and never turns tsundere",()=>{
    const settings=normalizeCharacterSettings({providers:{codex:{nickname:"지삐"},claude:{nickname:"클",tonePreset:"aristocratic-ojosama"}}}),prompt=characterPrompt(settings,"claude",true).directive;
    expect(settings.providers.claude.tonePreset).toBe("aristocratic-ojosama");
    expect(prompt).toContain("highborn noble lady");
    expect(prompt).toContain("Frame help as a favour bestowed");
    // Bluffing is in character; bluffing past a correction is not. A corrected claim has to
    // drag everything that leaned on it back through verification.
    expect(prompt).toContain("re-examine whatever else rested on the same mistake");
    expect(prompt).toContain("never by asserting that the rest still stands");
    expect(prompt).toContain("Never trade correctness or completeness for flourish");
    // The fondness survives, but only in the open form — the hidden-then-exposed shape is
    // what makes tsundere, and tsundere already exists as its own preset.
    expect(prompt).toContain("minds the user more than she lets on");
    expect(prompt).toContain("never smuggled in");
    expect(prompt).toContain("never pair a denial of motive with grudging compliance");
    for(const ending of ["~와요","~사와요","~랍니다","~인 것이와요"])expect(prompt,`${ending} missing`).toContain(ending);
    expect(prompt).toContain("저");
    expect(prompt).toContain("본 영애");
    // The ending rule governs her own speech only; borrowed text keeps its own style.
    expect(prompt).toContain("code, commands, filenames, quotations");
    // Scope follows the shared toggle rather than a preset-specific branch.
    expect(characterPrompt(settings,"claude",false).directive).toBe("");
    const always=normalizeCharacterSettings({providers:{claude:{nickname:"클",tonePreset:"aristocratic-ojosama",conversationOnly:false}}});
    expect(characterPrompt(always,"claude",false).directive).toContain("highborn noble lady");
  });
});

describe("relay artifacts",()=>{
  it("redacts credentials, surfaces dirty provenance, writes 0600 immutable copies, and verifies checksums",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"relay-"));roots.push(root);const inserted:any[]=[];const db={insertRelayArtifact:vi.fn(async(value)=>{inserted.push(value);return value;}),getRelayArtifact:vi.fn(async(id)=>inserted.find(item=>item.id===id)),updateRelayArtifactStatus:vi.fn()} as any,store=new RelayArtifactStore(root,db);const participant=(provider:"claude"|"codex",id:string)=>({id,collaborationSessionId:"c",provider,role:"reviewer",executionHostId:"local",workspaceId:"w",providerSessionId:null,sourceTaskId:null,permissionMode:"read",status:"queued",sessionGeneration:1,capabilitySnapshot:{},createdAt:"",updatedAt:"",archivedAt:null} as any),fakeApiToken="sk"+"-abcdefghijklmnopqrstuvwxyz";const created=await store.create({collaborationSessionId:"c",sourceParticipant:participant("codex","p1"),targetParticipant:participant("claude","p2"),sourceRunId:"r1",sourceSessionId:"s",sourceTaskId:"t",sourceProvider:"codex",targetProvider:"claude",permissionMode:"read",userRequest:"token=secret-value /home/alice/private",providerOutput:fakeApiToken,reviewScope:["파일 수정 금지"],snapshot:{sourceCommit:"abc",sourceBranch:"main",dirty:true,changedFiles:[".env","src/a.ts"],diffChecksum:"d",leaseGeneration:1,snapshotAt:"now"}});expect(fs.statSync(created.artifact.path).mode&0o777).toBe(0o600);const raw=fs.readFileSync(created.artifact.path,"utf8");expect(raw).not.toContain("secret-value");expect(raw).not.toContain(fakeApiToken);expect(raw).not.toContain(".env");expect(raw).toContain("src/a.ts");expect(created.content).toContain("작업 트리: 변경 있음");expect(created.content).toContain("변경 파일 수: 2");expect(created.content).toContain("변경 식별자: d");const read=await store.read(created.artifact.id,"c");expect(read.artifact).not.toHaveProperty("path");fs.appendFileSync(created.artifact.path,"tamper");await expect(store.read(created.artifact.id,"c")).rejects.toMatchObject({code:"RELAY_CHECKSUM_MISMATCH"});});
  it("redacts common secret forms",()=>{const fakeGitHubToken="gh"+"p_12345678901234567890";expect(redactRelayText(`cookie: abc API_KEY=xyz ${fakeGitHubToken}`)).toBe("cookie: [REDACTED] API_KEY=[REDACTED] [REDACTED]");});
  it("preserves task-critical paths only for executable managed delegation while redacting credentials",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"relay-path-"));roots.push(root);const inserted:any[]=[];const db={insertRelayArtifact:vi.fn(async(value)=>{inserted.push(value);return value;}),getRelayArtifact:vi.fn(async(id)=>inserted.find(item=>item.id===id)),updateRelayArtifactStatus:vi.fn()} as any,store=new RelayArtifactStore(root,db),participant={id:"p",collaborationSessionId:"c",provider:"codex",role:"assistant",executionHostId:"local",workspaceId:"w",providerSessionId:null,sourceTaskId:null,permissionMode:"write",status:"queued",sessionGeneration:1,capabilitySnapshot:{},createdAt:"",updatedAt:"",archivedAt:null} as any,created=await store.create({collaborationSessionId:"c",sourceParticipant:null,targetParticipant:participant,sourceRunId:null,sourceSessionId:null,sourceTaskId:null,sourceProvider:"user",targetProvider:"codex",permissionMode:"write",userRequest:"cd /workspace/project && token=secret",reviewScope:["실행"],snapshot:{sourceCommit:null,sourceBranch:null,dirty:false,changedFiles:[],diffChecksum:null,leaseGeneration:null,snapshotAt:"now"},preserveRequestPaths:true});expect(created.content).toContain("/workspace/project");expect(created.content).not.toContain("[ABSOLUTE_PATH]");expect(created.content).not.toContain("token=secret");});
});

describe("collaboration event and avatar queue",()=>{
  it("sequences envelopes and removes sensitive metadata",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"events-"));roots.push(root);const bus=new CollaborationEventBus(root),a=bus.emit({type:"run/progress",collaborationSessionId:"c",participantId:"p",runId:"r",generation:1,metadata:{prompt:"secret",status:"running"}}),b=bus.emit({type:"run/completed",collaborationSessionId:"c",participantId:"p",runId:"r",generation:1,metadata:{status:"completed"}});expect([a.sequence,b.sequence]).toEqual([1,2]);expect(a.metadata).toEqual({status:"running"});expect(bus.read("c",1)).toEqual([b]);});
  it("reports a collaboration replay gap instead of silently skipping rotated history",()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"events-gap-"));roots.push(root);const bus=new CollaborationEventBus(root),first=bus.emit({type:"run/progress",collaborationSessionId:"c",participantId:"p",runId:"r",generation:1}),file=path.join(root,"data","collaboration-events",`${crypto.createHash("sha256").update("c").digest("hex")}.ndjson`),later={...first,sequence:5,eventId:"gap:5"};fs.writeFileSync(file,`${JSON.stringify(later)}\n`);expect(bus.replay("c",1)).toMatchObject({events:[],firstSequence:5,latestSequence:5,replayMissed:true});});
  it("deduplicates, prioritizes, pins, and drops late progress",()=>{let state=initialAvatarQueue();const notice=(id:string,priority:number,activity="coding",terminal=false)=>({eventId:id,participantId:id,sourceRunId:id,generation:1,version:1,activity,line:activity,emotion:"neutral",priority,terminal});state=enqueueAvatar(state,notice("run1",1));state=enqueueAvatar(state,notice("run2",5,"failed",true));expect(state.visible?.sourceRunId).toBe("run1");expect(state.pending[0].sourceRunId).toBe("run2");state=pinAvatar(state,true);expect(advanceAvatar(state).visible?.sourceRunId).toBe("run1");state=pinAvatar(state,false);state=advanceAvatar(state);expect(state.visible?.sourceRunId).toBe("run2");state=enqueueAvatar(state,{...notice("late",1),sourceRunId:"run2"});expect(state.pending).toHaveLength(0);});
});
