import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {afterEach,describe,expect,it,vi} from "vitest";
import {ApprovalLoopError,approvalRequestDisposition,assertCodexPolicy,classifySandboxFailure,executionPolicyErrorCode,probeNativeSandbox,resolveExecutionPolicy,sandboxBootstrapErrorCategory,sandboxCacheKey,trustedHostOptInValid,type SandboxCapability} from "../../src/server/execution-policy.js";
import {CodexProvider} from "../../src/server/providers/codex.js";

const capability=(status:SandboxCapability["status"]="native-supported"):SandboxCapability=>({status,reason:status==="native-supported"?null:"kernel-unsupported",checkedAt:"2026-01-01T00:00:00.000Z",cacheKey:"key",kernel:"linux",architecture:"x64",bwrapPath:"/usr/bin/bwrap",bwrapVersion:"1",codexVersion:"codex 1",workerVersion:"1",uid:1,gid:1,bootId:"boot",detail:null});
const input=(requestedAutomation:"full"|"auto"|"confirm"|"read",extra:Record<string,unknown>={})=>({provider:"codex" as const,requestedAutomation,hostId:"local",workspaceId:"workspace",sandboxCapability:capability(),hostFallbackPolicy:{trustedHost:false,isolatedWorker:false},providerCapabilities:{automatic:true,confirm:true,fullAccess:true,readOnly:true},runtimeVersion:"codex 1",...extra});
const roots:string[]=[];afterEach(()=>{vi.restoreAllMocks();for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});

describe("execution policy",()=>{
  it("fixes the four Codex contracts",()=>{
    expect(resolveExecutionPolicy(input("auto"))).toMatchObject({requestedAutomation:"automatic",effectiveSandbox:"workspace-write",effectiveApprovalPolicy:"never",executionBackend:"native-sandbox",allowed:true});
    expect(resolveExecutionPolicy(input("confirm"))).toMatchObject({effectiveSandbox:"workspace-write",effectiveApprovalPolicy:"on-request",executionBackend:"confirmation"});
    expect(resolveExecutionPolicy(input("full"))).toMatchObject({effectiveSandbox:"danger-full-access",effectiveApprovalPolicy:"never",executionBackend:"full-access"});
    expect(resolveExecutionPolicy(input("read"))).toMatchObject({effectiveSandbox:"read-only",effectiveApprovalPolicy:"never",executionBackend:"read-only"});
  });
  it("uses explicit trusted-host without recording full-access",()=>{const policy=resolveExecutionPolicy(input("auto",{sandboxCapability:capability("native-unavailable"),hostFallbackPolicy:{trustedHost:true,isolatedWorker:false}}));expect(policy).toMatchObject({effectiveSandbox:"none",effectiveApprovalPolicy:"never",executionBackend:"trusted-host",allowed:true});expect(assertCodexPolicy(policy)).toEqual({sandbox:"danger-full-access",approvalPolicy:"never"});});
  it("falls back to a no-bwrap compatibility transport instead of blocking automatic execution",()=>{const policy=resolveExecutionPolicy(input("auto",{sandboxCapability:capability("native-unavailable")}));expect(policy).toMatchObject({executionBackend:"compatibility",effectiveSandbox:"none",allowed:true,userActionRequired:false,reason:"sandbox-unavailable-compatibility-fallback",transportSandbox:"danger-full-access"});expect(assertCodexPolicy(policy)).toEqual({sandbox:"danger-full-access",approvalPolicy:"never"});});
  it("keeps requested read and confirmation behavior while avoiding bwrap on incompatible kernels",()=>{const read=resolveExecutionPolicy(input("read",{sandboxCapability:capability("native-unavailable")})),confirm=resolveExecutionPolicy(input("confirm",{sandboxCapability:capability("native-unavailable")}));expect(read).toMatchObject({executionBackend:"compatibility",effectiveSandbox:"none",effectiveApprovalPolicy:"never",allowed:true,transportSandbox:"danger-full-access"});expect(confirm).toMatchObject({executionBackend:"compatibility",effectiveSandbox:"none",effectiveApprovalPolicy:"on-request",allowed:true,transportSandbox:"danger-full-access"});expect(assertCodexPolicy(read)).toEqual({sandbox:"danger-full-access",approvalPolicy:"never"});expect(assertCodexPolicy(confirm)).toEqual({sandbox:"danger-full-access",approvalPolicy:"on-request"});});
  it("does not require a native sandbox capability for explicit full access",()=>{const policy=resolveExecutionPolicy(input("full",{sandboxCapability:null}));expect(policy).toMatchObject({allowed:true,executionBackend:"full-access",effectiveSandbox:"danger-full-access",effectiveApprovalPolicy:"never",transportSandbox:"danger-full-access"});});
  it("probes restricted launches, uses compatibility fallback, and skips probing for full access",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"execution-policy-"));roots.push(root);const db:any={getSystemSetting:async()=>null,getHost:async()=>({id:"local",capabilities:{}}),upsertHost:async(value:any)=>value},provider=new CodexProvider({root,dataDir:root,projects:[]} as any,db),probe=vi.spyOn(provider,"probeNativeExecution").mockResolvedValue(capability("native-unavailable"));const task={project:{id:"p",name:"p",path:root,realPath:root,enabled:true,error:null},prompt:"pwd",executionHostId:"local",workspaceId:"w"};await expect((provider as any).executionPolicy({...task,automationLevel:"read"},"read")).resolves.toMatchObject({policy:{executionBackend:"compatibility",transportSandbox:"danger-full-access"}});expect(probe).toHaveBeenCalledTimes(1);probe.mockClear();await expect((provider as any).executionPolicy({...task,automationLevel:"full",permissionProfile:":danger-full-access"},"full")).resolves.toMatchObject({policy:{executionBackend:"full-access",transportSandbox:"danger-full-access"},capability:null});expect(probe).not.toHaveBeenCalled();});
  it("retains Claude's verified read, automatic and full mappings",()=>{const base={...input("auto"),provider:"claude" as const,sandboxCapability:null,providerCapabilities:{automatic:true,confirm:false,fullAccess:true,readOnly:true}};expect(resolveExecutionPolicy(base)).toMatchObject({executionBackend:"provider-native",effectiveSandbox:"workspace-write",effectiveApprovalPolicy:"never"});expect(resolveExecutionPolicy({...base,requestedAutomation:"read"})).toMatchObject({effectiveSandbox:"read-only"});expect(resolveExecutionPolicy({...base,requestedAutomation:"full"})).toMatchObject({executionBackend:"full-access"});});
  it("classifies probe failures without converting them into approvals",()=>{expect(classifySandboxFailure("uid_map: No such file or directory")).toBe("uid-map-missing");expect(classifySandboxFailure("kernel does not support user namespaces")).toBe("kernel-unsupported");expect(classifySandboxFailure("Creating new namespace failed: Operation not permitted")).toBe("namespace-creation-denied");expect(classifySandboxFailure("mount denied")).toBe("mount-denied");expect(classifySandboxFailure("timed out","ETIMEDOUT")).toBe("timeout");});
  it("preserves a runtime bwrap failure as a concrete task category",()=>{expect(sandboxBootstrapErrorCategory(new Error("bwrap: Creating new namespace failed, likely because the kernel does not support user namespaces."))).toBe("SANDBOX_BOOTSTRAP_FAILED");expect(sandboxBootstrapErrorCategory(new Error("model failed"))).toBeNull();});
  it("binds trusted host opt-in to host, provider, OS identity and version",()=>{const setting={enabled:true,hostId:"local",provider:"codex",osIdentity:"linux:test:uid=1",version:1};expect(trustedHostOptInValid(setting,setting)).toBe(true);expect(trustedHostOptInValid(setting,{...setting,hostId:"other"})).toBe(false);expect(trustedHostOptInValid(setting,{...setting,provider:"claude"})).toBe(false);expect(trustedHostOptInValid(setting,{...setting,version:2})).toBe(false);});
  it("changes the capability cache key when boot/runtime identity changes",()=>{const base={bwrapPath:"/usr/bin/bwrap",bwrapVersion:"1",codexVersion:"codex 1",workerVersion:"1",bootId:"a"};expect(sandboxCacheKey(base)).not.toBe(sandboxCacheKey({...base,bootId:"b"}));expect(sandboxCacheKey(base)).not.toBe(sandboxCacheKey({...base,codexVersion:"codex 2"}));});
  it("reports Windows native isolation as unavailable without entering the bwrap smoke test",()=>{
    const root=fs.mkdtempSync(path.join(os.tmpdir(),"execution-policy-win-"));roots.push(root);
    const marker=path.join(root,"launched"),binary=path.join(root,"codex.exe");
    fs.writeFileSync(binary,`#!/bin/sh\nprintf launched > '${marker}'\n`);fs.chmodSync(binary,0o700);
    expect(probeNativeSandbox(root,binary,"local",1000,"local","win32")).toMatchObject({status:"native-unavailable",reason:"platform-unsupported",bwrapPath:null,codexVersion:null,bootId:null,detail:expect.stringContaining("win32")});
    expect(fs.existsSync(marker)).toBe(false);
  });
  it("uses a diagnostic terminal error for automatic approval requests",()=>{const error=new ApprovalLoopError("sandbox-escalation","approval-id");expect(error.code).toBe("APPROVAL_LOOP_DETECTED");expect(error).toMatchObject({reason:"sandbox-escalation",approvalId:"approval-id"});});
  it("suppresses an injected automatic approval and only shows confirmation approvals",()=>{
    expect(approvalRequestDisposition(resolveExecutionPolicy(input("auto")))).toBe("circuit-break");
    expect(approvalRequestDisposition(resolveExecutionPolicy(input("confirm")))).toBe("show");
  });
  it("does not include Claudex Workhouse workspace approval or scope state",()=>{const policy=resolveExecutionPolicy(input("auto"));for(const key of ["repositoryTrust","repositoryTrusted","workspaceAccessMode","primaryWorkspacePath","approvedExternalPaths","externalPathScopes","externalWorkspaceModification"])expect(policy).not.toHaveProperty(key);});
});
