import fs from"node:fs";
import os from"node:os";
import path from"node:path";
import{afterEach,describe,expect,it}from"vitest";
import{DeckDatabase}from"../../src/server/db/client.js";
const roots:string[]=[];
afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
describe("external access persistence",()=>{
 it("uses profile revisions, persists safe checks, enforces one active operation, and reconciles restart",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"external-access-db-"));roots.push(root);const db=new DeckDatabase(path.resolve("src/server/db/sqlite-worker.py"),path.join(root,"test.sqlite"));try{await db.ping(60_000);const now=new Date().toISOString(),profile={id:"10000000-0000-4000-8000-000000000001",provider:"tailscale",desiredMode:"enabled",configuration:{hostname:"node.ts.net",allowedEmail:"[stored separately by policy]"},configurationSource:"workhouse",managedResources:["tailscale-serve"],createdAt:now,updatedAt:now};const first=await db.upsertExternalAccessProfile(profile);expect(first).toMatchObject({updated:true,current:{revision:1,provider:"tailscale"}});const conflict=await db.upsertExternalAccessProfile({...profile,updatedAt:new Date().toISOString()},7);expect(conflict).toMatchObject({updated:false,current:{revision:1}});const operation={id:"20000000-0000-4000-8000-000000000001",profileId:first.current.id,provider:"tailscale",action:"tailscale_serve_apply",planDigest:"a".repeat(64),status:"running",stage:"applying",safeErrorCode:null,startedAt:now,updatedAt:now,finishedAt:null,rollbackStatus:null,interrupted:false};await db.createExternalAccessOperation(operation);await expect(db.createExternalAccessOperation({...operation,id:"20000000-0000-4000-8000-000000000002"})).rejects.toThrow();await db.appendExternalAccessCheck({operationId:operation.id,profileId:first.current.id,code:"local_health",status:"passed",detail:"Local health responded.",checkedAt:now});expect(await db.listExternalAccessChecks(operation.id)).toMatchObject([{checkCode:"local_health",status:"passed"}]);expect(await db.reconcileExternalAccessOperations(now)).toBe(1);expect(await db.getExternalAccessOperation(operation.id)).toMatchObject({status:"interrupted",safeErrorCode:"SERVER_RESTARTED",interrupted:1});}finally{await db.close();}});
});
