import Fastify from"fastify";
import{afterEach,describe,expect,it}from"vitest";
import{registerExternalAccessRoutes}from"../../src/server/external-access/routes.js";
const apps:Array<ReturnType<typeof Fastify>>=[];afterEach(async()=>{await Promise.all(apps.splice(0).map(app=>app.close()));});
function fixture(){const app=Fastify(),coordinator:any={methods:()=>({methods:[]}),detect:async()=>[],configuration:async()=>({profiles:[]}),createPlan:async(body:any)=>({id:"10000000-0000-4000-8000-000000000001",secretAccepted:Boolean(body.token),token:undefined}),getPlan:()=>({}),apply:async()=>({}),getOperation:async()=>({id:"x",checks:[]}),subscribe:()=>()=>{},test:async()=>[],cancel:async()=>({accepted:true}),rollback:async()=>({}),remove:async()=>({}),support:async()=>({})};registerExternalAccessRoutes(app,{coordinator,idempotent:async(_request,_action,_body,run)=>run()});apps.push(app);return app;}
describe("external access API boundary",()=>{
 it("rejects arbitrary execution fields before route handling",async()=>{const response=await fixture().inject({method:"POST",url:"/api/external-access/v1/detect",payload:{provider:"tailscale",nested:{argv:["serve","reset"]}}});expect(response.statusCode).toBe(400);expect(response.json()).toMatchObject({code:"ARBITRARY_EXECUTION_FIELD"});});
 it("accepts a bounded secret request without returning the token",async()=>{const token="secret-"+"A".repeat(70),response=await fixture().inject({method:"POST",url:"/api/external-access/v1/plans",headers:{"idempotency-key":"10000000-0000-4000-8000-000000000001"},payload:{provider:"cloudflare",action:"cloudflare_managed_config_apply",hostname:"workhouse.example.com",teamDomain:"https://team.cloudflareaccess.com",audience:"audience_123",allowedEmail:"owner@example.com",localTarget:"http://127.0.0.1:3410",runMode:"host",token}});expect(response.statusCode).toBe(200);expect(response.json()).toMatchObject({secretAccepted:true});expect(response.body).not.toContain(token);});
 it("enforces the smaller plan body limit",async()=>{const response=await fixture().inject({method:"POST",url:"/api/external-access/v1/plans",payload:{padding:"x".repeat(9000)}});expect(response.statusCode).toBe(413);});
});
