import {describe,expect,it} from "vitest";
import {modelEnabled,normalizeGlobalModelSettings,requireEnabledModels,validateGlobalModelSettings} from "../../src/server/global-model-settings.js";

const candidates={codex:[{id:"gpt-current",displayName:"GPT Current",source:"runtime" as const,validatedAt:null},{id:"gpt-fast",displayName:"GPT Fast",source:"runtime" as const,validatedAt:null}],claude:[{id:"claude-opus-4-8",displayName:"Opus 4.8",source:"runtime" as const,validatedAt:null},{id:"claude-opus-4-6[1m]",displayName:"Opus 4.6",source:"custom" as const,validatedAt:null}],deepseek:[{id:"deepseek-v4-pro",displayName:"DeepSeek V4 Pro",source:"runtime" as const,validatedAt:null}],ollama:[{id:"qwen3-coder",displayName:"qwen3-coder",source:"runtime" as const,validatedAt:null}],antigravity:[],grok:[{id:"grok-build",displayName:"Grok Build",source:"runtime" as const,validatedAt:null}]};

describe("global model settings",()=>{
  it("uses every current candidate for a new installation",()=>{const settings=normalizeGlobalModelSettings(null,candidates);expect(settings.codex.models).toHaveLength(2);expect(settings.claude.models.map(item=>item.id)).toContain("claude-opus-4-6[1m]");});
  it("does not widen a malformed persisted allowlist",()=>{const settings=normalizeGlobalModelSettings({version:1,broken:true},candidates);expect(settings.codex.models.map(item=>item.id)).toEqual(["gpt-current"]);expect(settings.claude.models.map(item=>item.id)).toEqual(["claude-opus-4-8"]);});
  it("drops missing runtime entries but preserves custom entries",()=>{const stored={version:1,codex:{models:[candidates.codex[0],{id:"gpt-retired",displayName:"Retired",source:"runtime",validatedAt:null}]},claude:{models:[candidates.claude[1],{id:"claude-retired",displayName:"Custom old",source:"custom",validatedAt:null}]},deepseek:{models:candidates.deepseek},ollama:{models:candidates.ollama},antigravity:{models:[]},grok:{models:candidates.grok}};const settings=normalizeGlobalModelSettings(stored,candidates);expect(settings.codex.models.map(item=>item.id)).toEqual(["gpt-current"]);expect(settings.claude.models.map(item=>item.id)).toEqual(["claude-opus-4-6[1m]","claude-retired"]);});
  it("keeps the saved Ollama allowlist while the local catalog is temporarily offline",()=>{const offline={...candidates,ollama:[]};const stored={version:1,codex:{models:[candidates.codex[0]]},claude:{models:[candidates.claude[0]]},deepseek:{models:candidates.deepseek},ollama:{models:candidates.ollama},antigravity:{models:[]},grok:{models:candidates.grok}};expect(normalizeGlobalModelSettings(stored,offline).ollama.models).toEqual(candidates.ollama);expect(()=>validateGlobalModelSettings(stored,offline)).not.toThrow();});
  it("rejects an unavailable entry disguised as runtime and exposes one shared allowlist",()=>{const compatible={antigravity:{models:[]},grok:{models:candidates.grok}},invalid={version:1,codex:{models:[{id:"gpt-missing",displayName:"Missing",source:"runtime",validatedAt:null}]},claude:{models:[candidates.claude[0]]},deepseek:{models:candidates.deepseek},ollama:{models:candidates.ollama},...compatible};expect(()=>validateGlobalModelSettings(invalid,candidates)).toThrow(/no longer available/);const settings=validateGlobalModelSettings({version:1,codex:{models:[candidates.codex[0]]},claude:{models:[candidates.claude[0]]},deepseek:{models:candidates.deepseek},ollama:{models:candidates.ollama},...compatible},candidates);expect(modelEnabled(settings,"codex","gpt-current")).toBe(true);expect(modelEnabled(settings,"codex","gpt-fast")).toBe(false);});
  it("validates every collaboration participant against one settings snapshot",()=>{const settings=normalizeGlobalModelSettings(null,candidates);expect(()=>requireEnabledModels(settings,[{provider:"deepseek",model:"deepseek-v4-pro"},{provider:"ollama",model:"qwen3-coder"}])).not.toThrow();expect(()=>requireEnabledModels(settings,[{provider:"deepseek",model:"missing"},{provider:"ollama",model:"qwen3-coder"}])).toThrow(/deepseek model is not enabled/);});
});
