import fs from"node:fs";
import os from"node:os";
import path from"node:path";
import{afterEach,describe,expect,it}from"vitest";
import{grokTaskEnvironment}from"../../src/server/grok-task-environment.js";

const roots:string[]=[];const original=process.env.CLAUDEX_WORKHOUSE_GROK_HOME;
afterEach(()=>{if(original===undefined)delete process.env.CLAUDEX_WORKHOUSE_GROK_HOME;else process.env.CLAUDEX_WORKHOUSE_GROK_HOME=original;for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});

describe("Grok task home",()=>{
  function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"grok-task-home-")),shared=path.join(root,"shared"),binary=path.join(shared,"bin","grok-1.0.0");roots.push(root);fs.mkdirSync(path.dirname(binary),{recursive:true});fs.writeFileSync(binary,"runtime",{mode:0o700});fs.mkdirSync(path.join(shared,"sessions"));fs.mkdirSync(path.join(shared,"skills"));fs.writeFileSync(path.join(shared,"skills","sample.md"),"skill");fs.writeFileSync(path.join(shared,"auth.json"),"secret",{mode:0o600});fs.writeFileSync(path.join(shared,"config.toml"),'[ui]\nsimple_mode = true\n\n[mcp_servers.existing]\nurl = "https://example.test/mcp"\n\n[plugins.sample]\nenabled = true\n\n[models]\ndefault = "grok-4.6"\n\n[mcp_servers.claudex_workhouse_emotion]\nurl = "http://127.0.0.1:1/old"\n');process.env.CLAUDEX_WORKHOUSE_GROK_HOME=shared;return{root,shared,binary};}
  it("preserves non-MCP config, private auth, sessions, and user extensions in default mode",()=>{const{root,shared,binary}=fixture(),env=grokTaskEnvironment(binary,path.join(root,"task"),3410,"grok:task","default"),home=String(env.GROK_HOME),config=fs.readFileSync(path.join(home,"config.toml"),"utf8");expect(fs.statSync(home).mode&0o777).toBe(0o700);expect(fs.statSync(path.join(home,"config.toml")).mode&0o777).toBe(0o600);expect(fs.statSync(path.join(home,"auth.json")).mode&0o777).toBe(0o600);expect(fs.realpathSync(path.join(home,"sessions"))).toBe(fs.realpathSync(path.join(shared,"sessions")));expect(fs.realpathSync(path.join(home,"skills"))).toBe(fs.realpathSync(path.join(shared,"skills")));expect(config).toContain("[ui]");expect(config).toContain("[models]");expect(config).toContain("[mcp_servers.existing]");expect(config.match(/\[mcp_servers\.claudex_workhouse_emotion\]/g)).toHaveLength(1);expect(config).toContain('url = "http://127.0.0.1:3410/mcp/grok"');expect(config).toContain('"X-Claudex-Workhouse-Task-Id" = "grok:task"');expect(config).not.toContain("127.0.0.1:1/old");});
  it("makes conversation emotion-only and browser MCP-free",()=>{const{root,binary}=fixture(),conversation=grokTaskEnvironment(binary,path.join(root,"conversation"),3410,"grok:conversation","conversation"),conversationConfig=fs.readFileSync(path.join(String(conversation.GROK_HOME),"config.toml"),"utf8"),browser=grokTaskEnvironment(binary,path.join(root,"browser"),3410,"grok:browser","browser"),browserConfig=fs.readFileSync(path.join(String(browser.GROK_HOME),"config.toml"),"utf8");roots.push(String(conversation.CLAUDEX_WORKHOUSE_GROK_ISOLATED_CWD),String(browser.CLAUDEX_WORKHOUSE_GROK_ISOLATED_CWD));expect(conversationConfig).toContain("[ui]");expect(conversationConfig).toContain("[models]");expect(conversationConfig).not.toContain("mcp_servers.existing");expect(conversationConfig).not.toContain("plugins.sample");expect(conversationConfig).toContain("mcp_servers.claudex_workhouse_emotion");expect(conversationConfig).toContain('"X-Claudex-Workhouse-Runtime-Profile" = "conversation"');expect(conversation.GROK_CLAUDE_MCPS_ENABLED).toBe("0");expect(path.isAbsolute(String(conversation.CLAUDEX_WORKHOUSE_GROK_ISOLATED_CWD))).toBe(true);expect(fs.statSync(String(conversation.CLAUDEX_WORKHOUSE_GROK_ISOLATED_CWD)).mode&0o777).toBe(0o700);expect(browserConfig).not.toContain("mcp_servers.");expect(browserConfig).not.toContain("plugins.sample");expect(browser.GROK_CURSOR_MCPS_ENABLED).toBe("0");});
});
