import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {spawnSync} from "node:child_process";
import {afterEach,describe,expect,it} from "vitest";
import {createAutomaticDatabaseSnapshot,SnapshotStore} from "../../src/server/snapshot-store.js";

const roots:string[]=[];
afterEach(()=>{for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
function root(){const value=fs.mkdtempSync(path.join(os.tmpdir(),"claudex-workhouse-snapshots-"));roots.push(value);fs.mkdirSync(path.join(value,"config"));fs.writeFileSync(path.join(value,"config","claudex-workhouse.json"),"{}\n");fs.writeFileSync(path.join(value,"config","projects.json"),'{"projects":[]}\n');return value;}
function database(root:string){const file=path.join(root,"data","claudex-workhouse.sqlite");fs.mkdirSync(path.dirname(file),{recursive:true});const result=spawnSync("python3",["-c",'import sqlite3,sys; d=sqlite3.connect(sys.argv[1]); d.execute("create table sample(value text)"); d.execute("insert into sample values (\\"ok\\")"); d.commit(); d.close()',file],{encoding:"utf8"});expect(result.status,result.stderr).toBe(0);return file;}
class MemoryDb{
  records=new Map<string,any>();
  listSnapshots(){return Promise.resolve([...this.records.values()].map(item=>({...item})));}
  getSnapshot(id:string){return Promise.resolve(this.records.has(id)?{...this.records.get(id)}:null);}
  upsertSnapshot(item:any){const previous=this.records.get(item.id)??{},next={...previous,...item};this.records.set(item.id,next);return Promise.resolve({...next});}
}

describe("SnapshotStore",()=>{
  it("publishes a verified daily snapshot once and reconciles the disk catalog",async()=>{const base=root(),dbPath=database(base),first=createAutomaticDatabaseSnapshot(base,dbPath,new Date("2026-07-20T01:00:00Z"))!,second=createAutomaticDatabaseSnapshot(base,dbPath,new Date("2026-07-20T20:00:00Z"))!;expect(first.reused).toBe(false);expect(second.reused).toBe(true);expect(second.id).toBe(first.id);expect(fs.existsSync(path.join(first.directory,"COMPLETE"))).toBe(true);for(const file of [first.database,path.join(first.directory,"manifest.json"),path.join(first.directory,"COMPLETE")])expect(fs.statSync(file).mode&0o777).toBe(0o600);expect(fs.statSync(first.directory).mode&0o777).toBe(0o700);const db=new MemoryDb(),store=new SnapshotStore(path.join(base,"snapshots"),db as any);expect(await store.reconcile()).toEqual({discovered:1,errors:0});expect(await store.summary()).toMatchObject({count:1,activeCount:1,trashCount:0,errors:0});});
  it("uses reversible trash before permanent purge",async()=>{const base=root(),dbPath=database(base),created=createAutomaticDatabaseSnapshot(base,dbPath,new Date("2026-07-20T01:00:00Z"))!,db=new MemoryDb(),store=new SnapshotStore(path.join(base,"snapshots"),db as any);await store.reconcile();expect((await store.trash(created.id)).state).toBe("trashed");expect(fs.existsSync(path.join(base,"snapshots","trash",created.id))).toBe(true);expect((await store.untrash(created.id)).state).toBe("ready");await store.trash(created.id);expect((await store.purge(created.id)).state).toBe("purged");expect(fs.existsSync(path.join(base,"snapshots","trash",created.id))).toBe(false);});
  it("blocks a symlinked managed snapshot during reconcile",async()=>{const base=root(),snapshotDir=path.join(base,"snapshots"),outside=path.join(base,"outside");fs.mkdirSync(path.join(snapshotDir,"objects"),{recursive:true});fs.mkdirSync(path.join(snapshotDir,"trash"),{recursive:true});fs.mkdirSync(path.join(snapshotDir,".staging"),{recursive:true});fs.mkdirSync(outside);const id="11111111-1111-4111-8111-111111111111";fs.symlinkSync(outside,path.join(snapshotDir,"objects",id));const db=new MemoryDb(),store=new SnapshotStore(snapshotDir,db as any),result=await store.reconcile();expect(result.errors).toBe(1);expect((await db.getSnapshot(id))?.state).toBe("error");expect(fs.existsSync(outside)).toBe(true);});
  it("keeps Claude runtime rollback files out of the legacy inventory",()=>{const base=root();fs.mkdirSync(path.join(base,"backups","claude-runtime"),{recursive:true});fs.writeFileSync(path.join(base,"backups","claude-runtime","claude"),"runtime");fs.mkdirSync(path.join(base,"backups","manual"));fs.writeFileSync(path.join(base,"backups","manual","state.txt"),"state");const store=new SnapshotStore(path.join(base,"snapshots"),new MemoryDb() as any),inventory=store.legacyInventory();expect(inventory.items.map(item=>item.name)).toEqual(["manual"]);});
  it("consolidates one explicitly selected legacy backup with an atomic move",async()=>{const base=root(),legacy=path.join(base,"backups","before-change");fs.mkdirSync(legacy,{recursive:true});fs.writeFileSync(path.join(legacy,"state.txt"),"preserved");const db=new MemoryDb(),store=new SnapshotStore(path.join(base,"snapshots"),db as any,base),candidate=store.legacyInventory().items[0];const imported=await store.importLegacy(String(candidate.id));expect(imported).toMatchObject({kind:"legacy",state:"ready",verification:"unverified"});expect(fs.existsSync(legacy)).toBe(false);expect(fs.readFileSync(path.join(base,"snapshots","objects",imported.id,"payload","state.txt"),"utf8")).toBe("preserved");expect(store.legacyInventory().items).toEqual([]);});
  it("discovers and consolidates loose config bak and backup files only",async()=>{const base=root(),backup=path.join(base,"config","claudex-workhouse.json.backup-1"),live=path.join(base,"config","live.json");fs.writeFileSync(backup,"backup");fs.writeFileSync(live,"live");const db=new MemoryDb(),store=new SnapshotStore(path.join(base,"snapshots"),db as any,base),inventory=store.legacyInventory(),candidate=inventory.items.find(item=>item.source==="config-backup");expect(candidate).toMatchObject({name:"claudex-workhouse.json.backup-1",kind:"file"});expect(inventory.items.some(item=>item.name==="live.json")).toBe(false);const imported=await store.importLegacy(String(candidate!.id));expect(fs.readFileSync(path.join(base,"snapshots","objects",imported.id,"payload"),"utf8")).toBe("backup");expect(fs.existsSync(backup)).toBe(false);expect(fs.readFileSync(live,"utf8")).toBe("live");});
  it("rolls an interrupted legacy move back from staging",async()=>{const base=root(),snapshotDir=path.join(base,"snapshots"),legacy=path.join(base,"backups","interrupted"),id="22222222-2222-4222-8222-222222222222",staging=path.join(snapshotDir,".staging",id);fs.mkdirSync(legacy,{recursive:true});fs.writeFileSync(path.join(legacy,"state.txt"),"safe");fs.mkdirSync(staging,{recursive:true});fs.renameSync(legacy,path.join(staging,"payload"));fs.writeFileSync(path.join(staging,"operation.json"),JSON.stringify({formatVersion:1,type:"legacy-import",source:"backups",name:"interrupted",sourcePath:"backups/interrupted"}));const store=new SnapshotStore(snapshotDir,new MemoryDb() as any,base);expect(await store.reconcile()).toEqual({discovered:0,errors:0});expect(fs.readFileSync(path.join(legacy,"state.txt"),"utf8")).toBe("safe");expect(fs.existsSync(staging)).toBe(false);});
  it("protects the newest verified automatic snapshot from UI deletion",async()=>{const base=root(),dbPath=database(base),created=createAutomaticDatabaseSnapshot(base,dbPath,new Date("2026-07-20T01:00:00Z"))!,db=new MemoryDb(),store=new SnapshotStore(path.join(base,"snapshots"),db as any,base);await store.applyAutomaticRetention();await expect(store.trash(created.id)).rejects.toMatchObject({code:"SNAPSHOT_PROTECTED"});});
});
