import crypto from"node:crypto";
import fs from"node:fs";
import path from"node:path";
import{afterEach,describe,expect,it,vi}from"vitest";
import{listVertexModels,streamVertexContent,testVertexConnection,vertexFunctionCallPart}from"../../src/server/vertex-ai.js";

const roots:string[]=[];
function fixture(){const root=fs.mkdtempSync(path.join(process.cwd(),".vertex-ai-test-"));roots.push(root);const{privateKey}=crypto.generateKeyPairSync("rsa",{modulusLength:2048});const file=path.join(root,"service-account.json");fs.writeFileSync(file,JSON.stringify({type:"service_account",project_id:"sample-project-123",private_key_id:"key-id",private_key:privateKey.export({format:"pem",type:"pkcs8"}),client_email:"worker@sample-project-123.iam.gserviceaccount.com"}),{mode:0o600});return{version:1 as const,backend:"vertex" as const,vertex:{projectId:"sample-project-123",location:"global",credentialsPath:file,creditsUrl:""}};}
afterEach(()=>{vi.unstubAllGlobals();for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});

describe("Vertex direct API",()=>{
  it("replays a thought signature on the same function-call part",()=>{expect(vertexFunctionCallPart({name:"managed_provider_task_get",args:{},thoughtSignature:"signed-state"})).toEqual({functionCall:{name:"managed_provider_task_get",args:{}},thoughtSignature:"signed-state"});});
  it("loads the paginated runtime catalog, filters non-conversation models, and probes countTokens",async()=>{const settings=fixture(),fetch=vi.fn()
    .mockResolvedValueOnce(new Response(JSON.stringify({access_token:"token",expires_in:3600}),{status:200,headers:{"Content-Type":"application/json"}}))
    .mockResolvedValueOnce(new Response(JSON.stringify({publisherModels:[{name:"publishers/google/models/gemini-3.1-pro-preview"},{name:"publishers/google/models/gemini-3.1-flash-image"},{name:"publishers/google/models/text-embedding-005"}],nextPageToken:"page-2"}),{status:200,headers:{"Content-Type":"application/json"}}))
    .mockResolvedValueOnce(new Response(JSON.stringify({publisherModels:[{name:"publishers/google/models/gemini-3-flash"},{name:"publishers/google/models/gemini-3.1-pro-preview"}]}),{status:200,headers:{"Content-Type":"application/json"}}))
    .mockResolvedValueOnce(new Response(JSON.stringify({totalTokens:1}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetch);
    await expect(testVertexConnection(settings)).resolves.toEqual([{id:"gemini-3.1-pro-preview",displayName:"Gemini 3.1 Pro Preview",source:"runtime"},{id:"gemini-3-flash",displayName:"Gemini 3 Flash",source:"runtime"}]);expect(String(fetch.mock.calls[0]?.[0])).toBe("https://oauth2.googleapis.com/token");expect(String(fetch.mock.calls[1]?.[0])).toContain("/v1beta1/publishers/google/models?");expect(String(fetch.mock.calls[2]?.[0])).toContain("pageToken=page-2");expect(String(fetch.mock.calls[3]?.[0])).toContain("/publishers/google/models/gemini-3.1-pro-preview:countTokens");expect(JSON.stringify(fetch.mock.calls)).not.toContain("BEGIN PRIVATE KEY");
  });
  it("rejects an empty publisher catalog instead of presenting it as connected",async()=>{const settings=fixture(),fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:"token"}),{status:200,headers:{"Content-Type":"application/json"}})).mockResolvedValueOnce(new Response(JSON.stringify({publisherModels:[{name:"publishers/google/models/gemini-3.1-flash-image"}]}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetch);await expect(listVertexModels(settings)).rejects.toThrow(/no conversational Gemini models/);});
  it("streams SSE text and usage metadata from Vertex",async()=>{const settings=fixture(),body='data: {"candidates":[{"content":{"parts":[{"text":"안녕"}]}}]}\n\ndata: {"candidates":[{"content":{"parts":[{"text":"하세요"}]}}],"usageMetadata":{"promptTokenCount":3,"candidatesTokenCount":2,"totalTokenCount":5}}\n\n';const fetch=vi.fn()
    .mockResolvedValueOnce(new Response(JSON.stringify({access_token:"token"}),{status:200,headers:{"Content-Type":"application/json"}}))
    .mockResolvedValueOnce(new Response(body,{status:200,headers:{"Content-Type":"text/event-stream"}}));vi.stubGlobal("fetch",fetch);const chunks:any[]=[];
    await streamVertexContent(settings,"gemini-2.5-flash",[{role:"user",parts:[{text:"hello"}]}],chunk=>chunks.push(chunk));expect(chunks.map(item=>item.text).join("")).toBe("안녕하세요");expect(chunks.at(-1).usage).toMatchObject({promptTokenCount:3,candidateTokenCount:2,totalTokenCount:5});expect(String(fetch.mock.calls[1]?.[0])).toContain(":streamGenerateContent?alt=sse");
  });
  it("sanitizes MCP JSON Schema and preserves Vertex thought signatures on function calls",async()=>{const settings=fixture(),body='data: {"candidates":[{"content":{"parts":[{"functionCall":{"name":"managed_provider_task_get","args":{"taskId":"task-1"}},"thoughtSignature":"signed-state"}]}}]}\n\n',fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:"token"}),{status:200,headers:{"Content-Type":"application/json"}})).mockResolvedValueOnce(new Response(body,{status:200,headers:{"Content-Type":"text/event-stream"}}));vi.stubGlobal("fetch",fetch);const chunks:any[]=[];await streamVertexContent(settings,"gemini-2.5-flash",[{role:"user",parts:[{text:"check"}]}],chunk=>chunks.push(chunk),undefined,[{name:"managed_provider_task_get",description:"Get task",parameters:{$schema:"https://json-schema.org/draft/2020-12/schema",type:"object",properties:{taskId:{type:"string",description:"Task ID",examples:["task-1"]}},required:["taskId"],additionalProperties:false,$defs:{unused:{type:"string"}}}}]);expect(chunks[0].functionCalls).toEqual([{name:"managed_provider_task_get",args:{taskId:"task-1"},thoughtSignature:"signed-state"}]);const request=JSON.parse(String((fetch.mock.calls[1]?.[1] as RequestInit).body)),declaration=request.tools[0].functionDeclarations[0];expect(declaration.name).toBe("managed_provider_task_get");expect(declaration.parameters).toEqual({type:"object",properties:{taskId:{type:"string",description:"Task ID"}},required:["taskId"]});expect(JSON.stringify(declaration)).not.toMatch(/\$schema|additionalProperties|\$defs|examples/);});
  it("sends runtime identity through Vertex systemInstruction",async()=>{const settings=fixture(),body='data: {"candidates":[{"content":{"parts":[{"text":"ok"}]}}]}\n\n',fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:"token"}),{status:200,headers:{"Content-Type":"application/json"}})).mockResolvedValueOnce(new Response(body,{status:200,headers:{"Content-Type":"text/event-stream"}}));vi.stubGlobal("fetch",fetch);await streamVertexContent(settings,"gemini-3.6-flash",[{role:"user",parts:[{text:"너는 누구야?"}]}],()=>{},undefined,[],"Runtime identity: gemini-3.6-flash");const request=JSON.parse(String((fetch.mock.calls[1]?.[1] as RequestInit).body));expect(request.contents).toEqual([{role:"user",parts:[{text:"너는 누구야?"}]}]);expect(request.systemInstruction).toEqual({parts:[{text:"Runtime identity: gemini-3.6-flash"}]});});
  it("enables Google Search and extracts bounded grounding metadata",async()=>{const settings=fixture(),groundingMetadata={webSearchQueries:["latest Gemini model"],groundingChunks:[{web:{uri:"https://vertexaisearch.cloud.google.com/grounding-api-redirect/source","title":"Google Cloud"}},{web:{uri:"javascript:alert(1)",title:"unsafe"}}],searchEntryPoint:{renderedContent:"<div>Search suggestion</div>"}},body=`data: ${JSON.stringify({candidates:[{content:{parts:[{text:"grounded"}]},groundingMetadata}]})}\n\n`,fetch=vi.fn().mockResolvedValueOnce(new Response(JSON.stringify({access_token:"token"}),{status:200,headers:{"Content-Type":"application/json"}})).mockResolvedValueOnce(new Response(body,{status:200,headers:{"Content-Type":"text/event-stream"}}));vi.stubGlobal("fetch",fetch);const chunks:any[]=[];await streamVertexContent(settings,"gemini-3.6-flash",[{role:"user",parts:[{text:"최신 모델은?"}]}],chunk=>chunks.push(chunk),undefined,[],"system",true);const request=JSON.parse(String((fetch.mock.calls[1]?.[1] as RequestInit).body));expect(request.tools).toEqual([{googleSearch:{}}]);expect(chunks[0].grounding).toEqual({webSearchQueries:["latest Gemini model"],sources:[{uri:"https://vertexaisearch.cloud.google.com/grounding-api-redirect/source",title:"Google Cloud"}],renderedContent:"<div>Search suggestion</div>"});});
  it("rejects unsupported search and function-tool combinations before authentication",async()=>{await expect(streamVertexContent(fixture(),"gemini-3.6-flash",[],()=>{},undefined,[{name:"managed_provider_task_get",parameters:{type:"object"}}],"system",true)).rejects.toThrow(/cannot be combined/);});
});
