import{describe,expect,it}from"vitest";
import{normalizeVertexGoogleSearchMode,normalizeVertexSessionContents,requestsManagedProviderDelegation,vertexSystemInstruction,vertexTurnToolSelection}from"../../src/server/vertex-prompt.js";

describe("Vertex prompt",()=>{
  it("declares the selected model, date, and automatic search capability as runtime facts",()=>{const prompt=vertexSystemInstruction({model:"gemini-3.6-flash",cwd:"/workspace",currentDate:"2026-08-06",managedEnabled:false,googleSearchMode:"auto",googleSearchEnabled:true,delegationInstructions:"Delegation rules."});expect(prompt).toContain("selected Vertex model identifier for this request is gemini-3.6-flash");expect(prompt).toContain("If asked which model you are, state this identifier exactly");expect(prompt).toContain("Current date: 2026-08-06");expect(prompt).toContain("Google Search grounding is available");expect(prompt).toContain("Current workspace label: /workspace");});
  it("defaults unknown and missing search settings to off",()=>{expect(normalizeVertexGoogleSearchMode(undefined)).toBe("off");expect(normalizeVertexGoogleSearchMode("invalid")).toBe("off");expect(vertexTurnToolSelection({prompt:"최신 Gemini 모델은?",managedEnabled:false,googleSearchMode:undefined})).toEqual({managedDelegation:false,extensionToolsEnabled:false,googleSearchEnabled:false});const prompt=vertexSystemInstruction({model:"gemini",cwd:"/workspace",currentDate:"2026-08-06",managedEnabled:false,googleSearchMode:"off",googleSearchEnabled:false,delegationInstructions:""});expect(prompt).toContain("disabled by this session's setting");});
  it("enables auto and always search while giving explicit managed delegation precedence",()=>{expect(vertexTurnToolSelection({prompt:"최신 정보를 알려줘",managedEnabled:true,googleSearchMode:"auto"})).toEqual({managedDelegation:false,extensionToolsEnabled:false,googleSearchEnabled:true});expect(vertexTurnToolSelection({prompt:"최신 정보를 알려줘",managedEnabled:true,googleSearchMode:"always"})).toEqual({managedDelegation:false,extensionToolsEnabled:false,googleSearchEnabled:true});expect(vertexTurnToolSelection({prompt:"Claude Code에게 검토시켜",managedEnabled:true,googleSearchMode:"always"})).toEqual({managedDelegation:true,extensionToolsEnabled:false,googleSearchEnabled:false});const prompt=vertexSystemInstruction({model:"gemini",cwd:"/workspace",currentDate:"2026-08-06",managedEnabled:false,googleSearchMode:"always",googleSearchEnabled:true,delegationInstructions:""});expect(prompt).toContain("required for this turn");});
  it("removes repeated legacy system text from persisted user turns",()=>{const contents=normalizeVertexSessionContents([{role:"user",parts:[{text:"You are the Vertex API mode of Gemini inside Claudex Workhouse. Old rules.\n\n# Current user prompt\n너는 제미나이 3.6플래쉬야"}]},{role:"model",parts:[{text:"old answer"}]}]);expect(contents).toEqual([{role:"user",parts:[{text:"너는 제미나이 3.6플래쉬야"}]},{role:"model",parts:[{text:"old answer"}]}]);});
  it("selects managed functions only for explicit named-provider delegation",()=>{expect(requestsManagedProviderDelegation("Claude Code에게 이 코드를 검토시켜")).toBe(true);expect(requestsManagedProviderDelegation("Codex가 뭐야?")).toBe(false);expect(requestsManagedProviderDelegation("최신 Gemini 모델을 검색해봐")).toBe(false);});
});
