import fs from"node:fs";
import path from"node:path";
import type{ExternalAccessDetection}from"../types.js";
import{boundedCommand,defaultExternalCommandRunner,findExecutable,type ExternalCommandRunner}from"../process.js";
function parseVersion(raw:string){return raw.match(/\b(20\d{2}\.\d+\.\d+)\b/)?.[1]??null;}
function candidateConfigs(){const values=[process.env.TUNNEL_CONFIG,process.env.CLOUDFLARED_CONFIG,process.platform==="win32"&&process.env.USERPROFILE?path.join(process.env.USERPROFILE,".cloudflared","config.yml"):null,process.env.HOME?path.join(process.env.HOME,".cloudflared","config.yml"):null,"/etc/cloudflared/config.yml","/etc/cloudflared/config.yaml"];return values.filter((v):v is string=>Boolean(v));}
function safeConfigSummary(file:string,expectedTarget:string){try{const stat=fs.lstatSync(file);if(!stat.isFile()||stat.isSymbolicLink()||stat.size>1024*1024)return null;const text=fs.readFileSync(file,"utf8"),services=[...text.matchAll(/^\s*service:\s*([^#\s]+)\s*$/gmi)].map(x=>x[1]).filter(x=>/^http:\/\/(?:127\.0\.0\.1|localhost|\[::1\]):\d+$/.test(x)),port=new URL(expectedTarget).port;return{configured:true,locallyManaged:/^\s*tunnel\s*:/mi.test(text),namedTunnel:/^\s*tunnel\s*:\s*\S+/mi.test(text),credentialsFile:/^\s*credentials-file\s*:/mi.test(text),tokenFile:/^\s*token-file\s*:/mi.test(text),ingressCount:services.length,ingressTargetMatches:services.some(service=>new URL(service).port===port),ingressTargets:services.map(()=>"[LOOPBACK_TARGET]")};}catch{return null;}}
function hostProcesses(){const found:Array<{pid:number;tokenArgument:boolean;tokenFile:boolean;credentialsFile:boolean}>=[];if(process.platform==="win32"||!fs.existsSync("/proc"))return found;for(const name of fs.readdirSync("/proc")){if(!/^\d+$/.test(name))continue;try{const command=fs.readFileSync(`/proc/${name}/cmdline`).toString("utf8").split("\0").filter(Boolean);if(!command.length||path.basename(command[0]).toLowerCase()!=="cloudflared")continue;found.push({pid:Number(name),tokenArgument:command.includes("--token"),tokenFile:command.includes("--token-file"),credentialsFile:command.some(item=>/credentials.*\.json$/i.test(item))});}catch{}}return found;}
export async function detectCloudflare(input:{runner?:ExternalCommandRunner;binary?:string|null;cwd?:string;configFiles?:string[];expectedLocalTarget?:string}={}):Promise<ExternalAccessDetection>{
 const checkedAt=new Date().toISOString(),runner=input.runner??defaultExternalCommandRunner,binary=input.binary===undefined?findExecutable("cloudflared"):input.binary,cwd=input.cwd??process.cwd(),expected=input.expectedLocalTarget??"http://127.0.0.1:3410",config=(input.configFiles??candidateConfigs()).map(file=>({file,summary:safeConfigSummary(file,expected)})).find(x=>x.summary),processes=hostProcesses();let containers:Array<{image:string;name:string}>=[];const docker=findExecutable("docker");if(docker){const listed=await boundedCommand(runner,docker,["ps","--format","{{.Image}}\t{{.Names}}"],cwd);if(listed.exitCode===0)containers=listed.stdout.split("\n").map(line=>line.split("\t")).filter(([image,name])=>Boolean(name)&&/cloudflared/i.test(`${image} ${name}`)).slice(0,20).map(([image,name])=>({image,name}));}const serviceRunning=processes.length>0||containers.length>0,ingressMismatch=Boolean(config?.summary?.ingressCount&&!config.summary.ingressTargetMatches);
 if(!binary)return{provider:"cloudflare",state:ingressMismatch?"misconfigured":serviceRunning||config?"configured":"not_detected",management:serviceRunning||config?"externally-managed":"guided",checkedAt,installed:false,serviceRunning,authenticated:config?true:null,connected:serviceRunning?true:null,configured:Boolean(config||serviceRunning),permission:"unknown",version:null,externalUrl:null,details:{configDetected:Boolean(config),config:config?.summary??null,hostProcessCount:processes.length,containerCount:containers.length,executionMode:containers.length?"docker":processes.length?"host":"none",credentialMode:processes.some(item=>item.tokenFile)?"token-file":processes.some(item=>item.tokenArgument)?"token-argument":processes.some(item=>item.credentialsFile)||config?.summary?.credentialsFile?"credentials-file":"unknown"},warnings:[...(config&&!serviceRunning?["A Cloudflare configuration exists, but no running cloudflared process was detected."]:[]),...(ingressMismatch?["Cloudflare ingress does not target the Workhouse loopback listener."]:[])]};
 const versionResult=await boundedCommand(runner,binary,["version"],cwd),version=parseVersion(versionResult.stdout||versionResult.stderr),configured=Boolean(config);
 return{provider:"cloudflare",state:ingressMismatch?"misconfigured":serviceRunning||configured?"configured":"installed",management:"guided",checkedAt,installed:true,serviceRunning,authenticated:configured?true:null,connected:serviceRunning?true:null,configured:configured||serviceRunning,permission:"unknown",version,externalUrl:null,details:{configDetected:configured,config:config?.summary??null,hostProcessCount:processes.length,containerCount:containers.length,executionMode:containers.length?"docker":processes.length?"host":"none",credentialMode:processes.some(item=>item.tokenFile)?"token-file":processes.some(item=>item.tokenArgument)?"token-argument":processes.some(item=>item.credentialsFile)||config?.summary?.credentialsFile?"credentials-file":"unknown",tokenFileSupported:version?Number(version.split(".")[0])>2025||version.startsWith("2025.")&&Number(version.split(".")[1])>=4:false},warnings:[...(processes.some(item=>item.tokenArgument)?["cloudflared is using a command-line token; token-file is recommended on supported versions."]:[]),...(ingressMismatch?["Cloudflare ingress does not target the Workhouse loopback listener."]:[])]};
}
