import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { runDockerHostUpdate } from "../../../deploy/updater/docker-host-updater.mjs";

const roots:string[]=[];afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();for(const root of roots.splice(0))fs.rmSync(root,{recursive:true,force:true});});
async function fixture(readiness:(env:string)=>boolean,sourceVersion="1.0.0"){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"docker-host-updater-"));roots.push(root);const compose=path.join(root,"compose"),requests=path.join(root,"runtime","application-updates","requests"),bin=path.join(root,"bin");fs.mkdirSync(compose,{recursive:true});fs.mkdirSync(requests,{recursive:true});fs.mkdirSync(bin);
  fs.writeFileSync(path.join(compose,"compose.yaml"),"services:\n  app:\n    image: ${CLAUDEX_WORKHOUSE_IMAGE_REFERENCE}\n");fs.writeFileSync(path.join(compose,".env"),`CLAUDEX_WORKHOUSE_VERSION=1.0.0\nCLAUDEX_WORKHOUSE_IMAGE_DIGEST=sha256:${"a".repeat(64)}\nCLAUDEX_WORKHOUSE_IMAGE_REFERENCE=ghcr.io/example/workhouse@sha256:${"a".repeat(64)}\nCLAUDEX_WORKHOUSE_UPDATER_PROTOCOL_VERSION=1\n`);
  const docker=path.join(bin,"docker");fs.writeFileSync(docker,"#!/bin/sh\nprintf '%s\\n' \"$*\" >> \"$DOCKER_LOG\"\ncase \"$*\" in\n  *docker-host-updater.mjs*) for destination do :; done; cp \"$UPDATER_SOURCE\" \"$destination\" ;;\n  *release-key-ring.json*) for destination do :; done; cp \"$KEY_RING_SOURCE\" \"$destination\" ;;\nesac\nexit 0\n",{mode:0o700});const dockerLog=path.join(root,"docker.log");vi.stubEnv("PATH",`${bin}:${process.env.PATH}`);vi.stubEnv("DOCKER_LOG",dockerLog);
  const pair=crypto.generateKeyPairSync("rsa",{modulusLength:2048,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}}),attemptId=crypto.randomUUID(),manifest={schemaVersion:3,version:"1.1.0",server:{image:"ghcr.io/example/workhouse",digest:`sha256:${"b".repeat(64)}`,minimumUpdaterProtocolVersion:1},signing:{keyId:"test-key",algorithm:"rsa-sha256"}},manifestBytes=Buffer.from(JSON.stringify(manifest)),manifestSha256=crypto.createHash("sha256").update(manifestBytes).digest("hex");
  const signature=crypto.sign("RSA-SHA256",manifestBytes,pair.privateKey),keyRingFile=path.join(root,"key-ring.json"),requestFile=path.join(requests,`${attemptId}.json`);fs.writeFileSync(keyRingFile,JSON.stringify({schemaVersion:1,keys:[{keyId:"test-key",algorithm:"rsa-sha256",publicKeyPem:pair.publicKey,notBefore:"2026-01-01T00:00:00.000Z",expiresAt:"2027-01-01T00:00:00.000Z",revoked:false}]}));fs.writeFileSync(requestFile,JSON.stringify({schemaVersion:1,attemptId,installMethod:"docker-compose",sourceVersion,targetVersion:"1.1.0",manifestSha256,snapshotId:attemptId,artifact:{repository:"ghcr.io/example/workhouse",digest:`sha256:${"b".repeat(64)}`},manifest:{url:"https://release.test/release-manifest.json",signatureUrl:"https://release.test/release-manifest.json.sig"},createdAt:new Date().toISOString()}));
  vi.stubEnv("UPDATER_SOURCE",path.resolve("../deploy/updater/docker-host-updater.mjs"));vi.stubEnv("KEY_RING_SOURCE",keyRingFile);vi.stubGlobal("fetch",vi.fn(async(input:string|URL|Request)=>{const url=new URL(typeof input==="string"||input instanceof URL?input:input.url);if(url.protocol==="https:")return new Response(url.pathname.endsWith(".sig")?signature:manifestBytes,{status:200});const env=fs.readFileSync(path.join(compose,".env"),"utf8");return new Response("ok",{status:readiness(env)?200:503});}));
  const environment={WORKHOUSE_UPDATE_REQUEST_FILE:requestFile,WORKHOUSE_RELEASE_KEY_RING_FILE:keyRingFile,WORKHOUSE_UPDATER_FILE:path.join(root,"installed-updater.mjs"),WORKHOUSE_COMPOSE_DIRECTORY:compose,WORKHOUSE_HEALTH_ORIGIN:"http://127.0.0.1:3410",WORKHOUSE_HEALTH_TIMEOUT_MS:"150"};return{root,compose,dockerLog,attemptId,environment};
}

describe("Docker host-side updater",()=>{
  it("pulls the signed digest, atomically switches Compose metadata, and records success",async()=>{const value=await fixture(()=>true);const result=await runDockerHostUpdate(value.environment);expect(result).toMatchObject({state:"completed",rollbackPerformed:false});expect(fs.readFileSync(path.join(value.compose,".env"),"utf8")).toContain("CLAUDEX_WORKHOUSE_VERSION=1.1.0");expect(fs.readFileSync(value.dockerLog,"utf8")).toContain(`pull ghcr.io/example/workhouse@sha256:${"b".repeat(64)}`);expect(JSON.parse(fs.readFileSync(path.join(value.root,"runtime","application-updates","results",`${value.attemptId}.json`),"utf8"))).toMatchObject({state:"completed"});});
  it("restores the previous Compose metadata when the new container is not ready",async()=>{const value=await fixture(env=>env.includes("CLAUDEX_WORKHOUSE_VERSION=1.0.0"));await expect(runDockerHostUpdate(value.environment)).rejects.toMatchObject({result:{state:"rolled-back",rollbackPerformed:true}});expect(fs.readFileSync(path.join(value.compose,".env"),"utf8")).toContain("CLAUDEX_WORKHOUSE_VERSION=1.0.0");expect(fs.readFileSync(value.dockerLog,"utf8").trim().split("\n").filter(line=>line.startsWith("compose "))).toHaveLength(2);});
  it("rejects a stale source-version request before pulling an image",async()=>{const value=await fixture(()=>true,"0.9.0");await expect(runDockerHostUpdate(value.environment)).rejects.toThrow(/source version/);expect(fs.existsSync(value.dockerLog)?fs.readFileSync(value.dockerLog,"utf8"):"").not.toContain("pull ");});
});
