import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { spawnSync } from "node:child_process";
import Fastify from "fastify";
import fastifyWebsocket from "@fastify/websocket";
import { afterEach, describe, expect, it, vi } from "vitest";
import { DeckDatabase } from "../../src/server/db/client.js";
import { WorkerHub } from "../../src/server/worker-hub.js";
import { DesktopWorkerClient, pairWorker } from "../../src/server/desktop-worker/client.js";
import { loadWorkerConfig, saveWorkerConfig } from "../../src/server/desktop-worker/config.js";
import { addRoot, workspaceCommand } from "../../src/server/desktop-worker/workspaces.js";
import { readStreamEvents } from "../../src/server/stream-events.js";
import { codexApprovalRecord, persistPendingApproval, waitForApprovalDecision, type ApprovalDecision } from "../../src/server/approval-bridge.js";

const created:string[]=[];
afterEach(()=>{vi.unstubAllEnvs();for(const item of created.splice(0))fs.rmSync(item,{recursive:true,force:true});});
async function until(check:()=>boolean,timeout=5000){const end=Date.now()+timeout;while(Date.now()<end){if(check())return;await new Promise(resolve=>setTimeout(resolve,25));}throw new Error("condition timed out");}
async function untilAsync(check:()=>Promise<boolean>,timeout=5000){const end=Date.now()+timeout;while(Date.now()<end){if(await check())return;await new Promise(resolve=>setTimeout(resolve,25));}throw new Error("condition timed out");}

describe("Desktop Worker connection",()=>{
  it("pairs once, authenticates WSS, and serves only typed capabilities",async()=>{
    const executableTemp=path.resolve("../data");fs.mkdirSync(executableTemp,{recursive:true});const base=fs.mkdtempSync(path.join(executableTemp,"claudex-workhouse-worker-connect-"));created.push(base);const workerHome=path.join(base,"worker");vi.stubEnv("CLAUDEX_WORKHOUSE_ROOT",base);vi.stubEnv("CLAUDEX_WORKHOUSE_WORKER_HOME",workerHome);
    const db=new DeckDatabase(path.resolve("src/server/db/sqlite-worker.py"),path.join(base,"test.sqlite"));await db.ping();const hub=new WorkerHub(db,base);const app=Fastify({logger:false});await app.register(fastifyWebsocket,{options:{maxPayload:1024*1024,perMessageDeflate:false}});await hub.register(app);await app.listen({host:"127.0.0.1",port:0});
    let client:DesktopWorkerClient|null=null;
    try{
      const address=app.server.address();if(!address||typeof address==="string")throw new Error("missing test address");const url=`http://127.0.0.1:${address.port}`,pairing=hub.createPairing();const paired=await pairWorker(url,pairing.code,"Integration Desktop");expect(hub.pairingStatus(pairing.id)?.status).toBe("paired");
      const workspacePath=path.join(base,"workspace");fs.mkdirSync(workspacePath);const fakeClaude=path.join(base,"fake-claude.mjs");fs.writeFileSync(fakeClaude,`#!/usr/bin/env node\nconst prompt=process.argv.at(-1)??\"\";\nconsole.log(JSON.stringify({type:\"system\",subtype:\"init\",session_id:\"fake-thread\"}));\nconsole.log(JSON.stringify({type:\"assistant\",session_id:\"fake-thread\",message:{content:[{type:\"text\",text:\"remote reply\"}]}}));\nconst finish=()=>console.log(JSON.stringify({type:\"result\",session_id:\"fake-thread\",is_error:false,result:\"done\"}));\nif(prompt.includes(\"wait-for-stop\"))setTimeout(finish,30000);else finish();\n`,{mode:0o700});
      const fakeCodex=path.join(base,"fake-codex.mjs");fs.writeFileSync(fakeCodex,`#!/usr/bin/env node\nif(process.argv.includes(\"--version\")){console.log(\"codex-fake 1.0\");process.exit(0);}\nconst readline=(await import(\"node:readline\")).default;const rl=readline.createInterface({input:process.stdin});const send=value=>console.log(JSON.stringify(value));\nrl.on(\"line\",line=>{const m=JSON.parse(line);if(m.method===\"initialized\")return;if(m.method===\"initialize\")return send({id:m.id,result:{}});if(m.method===\"thread/start\"||m.method===\"thread/resume\")return send({id:m.id,result:{thread:{id:m.params.threadId??\"fake-codex-thread\"}}});if(m.method===\"thread/fork\")return send({id:m.id,result:{thread:{id:\"fake-codex-fork\"}}});if(m.method===\"turn/start\"){const threadId=m.params.threadId,turn={id:\"fake-turn\",status:\"inProgress\"};send({id:m.id,result:{turn}});setTimeout(()=>{send({method:\"turn/started\",params:{threadId,turn}});send({method:\"item/completed\",params:{threadId,turnId:turn.id,item:{id:\"commentary\",type:\"agentMessage\",text:\"codex preliminary reply\",phase:\"commentary\"}}});send({method:\"turn/completed\",params:{threadId,turn:{...turn,status:\"completed\",items:[{id:\"message\",type:\"agentMessage\",text:\"codex remote reply\",phase:\"final_answer\"}]}}});},20);return;}if(m.method===\"turn/interrupt\")return send({id:m.id,result:{}});if(m.method===\"account/read\")return send({id:m.id,result:{requiresOpenaiAuth:true,account:{type:\"chatgpt\",planType:\"pro\"}}});send({id:m.id,result:{}});});\n`,{mode:0o700});
      const config=loadWorkerConfig(),root=addRoot(config,workspacePath,"Test root");const made=await workspaceCommand(config,"workspace.create",{rootId:root.id,projectId:"test-project",folderName:"project",displayName:"Project",mode:"empty"},paired.hostId) as any;config.claudeBinary=fakeClaude;config.codexBinary=fakeCodex;
      const approvalTaskId="codex:remote:approval",approvalState=path.join(workerHome,"approval-task.json"),timestamp=new Date().toISOString();fs.writeFileSync(approvalState,JSON.stringify({status:"completed",updatedAt:timestamp}));config.tasks.push({id:approvalTaskId,provider:"codex",workspaceId:made.workspace.id,stateFile:approvalState,pid:null,marker:"fixture",createdAt:timestamp,updatedAt:timestamp,status:"completed",threadId:"approval-thread",lastForwardedSequence:0});saveWorkerConfig(config);
      client=new DesktopWorkerClient();const running=client.run();await until(()=>hub.isOnline(paired.hostId));const capabilities=await hub.request(paired.hostId,"host.capabilities.read",{}) as any;expect(capabilities.commands).toContain("provider.task.start");expect(capabilities.commands).not.toContain("shell.exec");expect(capabilities.automationLevelsByProvider).toEqual({claude:["full","auto","read"],codex:["full","auto","confirm","read"],deepseek:["full","auto","read"],ollama:["full","auto","read"],antigravity:["full","auto","read"],grok:["full","auto","read"]});
      // The Worker advertises one capability row per provider it can be asked
      // to run, so the runtime screen never offers a provider the Worker would
      // reject at launch.
      expect((capabilities.providerCapabilities as any[]).map(item=>item.provider).sort()).toEqual(["antigravity","claude","codex","deepseek","grok","ollama"]);
      expect(capabilities.commands).toContain("provider.thread.command");expect((await db.getWorkerCredential(paired.hostId))?.credentialHash).toMatch(/^[a-f0-9]{64}$/);expect(fs.readFileSync(path.join(workerHome,"config.json"),"utf8")).not.toContain((await db.getWorkerCredential(paired.hostId))?.credentialHash??"impossible");
      for(const decision of ["accept","acceptForSession","decline"] satisfies ApprovalDecision[]){
        const approval=codexApprovalRecord({taskId:approvalTaskId,hostId:paired.hostId,workspaceId:made.workspace.id,cwd:made.workspace.canonicalPath,method:"item/commandExecution/requestApproval",params:{command:["git","status"],reason:`Fixture ${decision}`,availableDecisions:["accept","acceptForSession","decline"]},providerRequestId:`request-${decision}`,ttlMs:5000});persistPendingApproval(approvalState,approval);
        const listed=await hub.request(paired.hostId,"provider.approvals.list",{taskId:approvalTaskId,provider:"codex",workspaceId:made.workspace.id}) as any;expect(listed.approvals).toContainEqual(expect.objectContaining({id:approval.id,taskId:approvalTaskId,hostId:paired.hostId,workspaceId:made.workspace.id,risk:"medium"}));
        const response=await hub.request(paired.hostId,"provider.approval.respond",{taskId:approvalTaskId,provider:"codex",workspaceId:made.workspace.id,approvalId:approval.id,decision}) as any;expect(response).toMatchObject({accepted:true,approval:{id:approval.id}});
        await expect(waitForApprovalDecision(approvalState,approval)).resolves.toBe(decision);
      }
      const duplicate=codexApprovalRecord({taskId:approvalTaskId,hostId:paired.hostId,workspaceId:made.workspace.id,cwd:made.workspace.canonicalPath,method:"item/fileChange/requestApproval",params:{changes:[{path:path.join(made.workspace.canonicalPath,"changed.txt")}],availableDecisions:["decline"]},providerRequestId:"request-duplicate",ttlMs:5000});persistPendingApproval(approvalState,duplicate);const duplicateKey=crypto.randomUUID(),duplicatePayload={taskId:approvalTaskId,provider:"codex",workspaceId:made.workspace.id,approvalId:duplicate.id,decision:"decline"};const firstDuplicate=await hub.request(paired.hostId,"provider.approval.respond",duplicatePayload,duplicateKey),secondDuplicate=await hub.request(paired.hostId,"provider.approval.respond",duplicatePayload,duplicateKey);expect(secondDuplicate).toEqual(firstDuplicate);await expect(waitForApprovalDecision(approvalState,duplicate)).resolves.toBe("decline");await expect(hub.request(paired.hostId,"provider.approval.respond",duplicatePayload,crypto.randomUUID())).rejects.toMatchObject({code:"APPROVAL_NOT_PENDING",statusCode:409});
      const expired=codexApprovalRecord({taskId:approvalTaskId,hostId:paired.hostId,workspaceId:made.workspace.id,cwd:made.workspace.canonicalPath,method:"item/commandExecution/requestApproval",params:{command:["git","status"],availableDecisions:["accept","decline"]},providerRequestId:"request-expired",ttlMs:-1});persistPendingApproval(approvalState,expired);await expect(hub.request(paired.hostId,"provider.approval.respond",{taskId:approvalTaskId,provider:"codex",workspaceId:made.workspace.id,approvalId:expired.id,decision:"accept"})).rejects.toMatchObject({code:"APPROVAL_EXPIRED",statusCode:409});
      gitInit(made.workspace.canonicalPath);fs.writeFileSync(path.join(made.workspace.canonicalPath,"changed.txt"),"remote patch\n");const prepared=await hub.request(paired.hostId,"handoff.patch.prepare",{workspaceId:made.workspace.id}) as any,patchChunk=await hub.request(paired.hostId,"handoff.patch.chunk",{transferId:prepared.transferId,offset:0}) as any;expect(Buffer.from(patchChunk.dataBase64,"base64").toString()).toContain("changed.txt");const artifactId=crypto.randomUUID(),markdown=Buffer.from("# handoff\n"),manifest=Buffer.from("{}\n"),meta=(value:Buffer)=>({size:value.length,checksum:crypto.createHash("sha256").update(value).digest("hex")});await hub.request(paired.hostId,"handoff.receive.begin",{artifactId,files:{markdown:meta(markdown),manifest:meta(manifest)}});await hub.request(paired.hostId,"handoff.receive.chunk",{artifactId,file:"markdown",offset:0,dataBase64:markdown.toString("base64")});await hub.request(paired.hostId,"handoff.receive.chunk",{artifactId,file:"manifest",offset:0,dataBase64:manifest.toString("base64")});await hub.request(paired.hostId,"handoff.receive.complete",{artifactId});expect(fs.readFileSync(path.join(workerHome,"artifacts",artifactId,"handoff.md"),"utf8")).toBe("# handoff\n");
      const taskId="claude:remote:integration";await db.upsertTask({id:taskId,provider:"claude",nativeId:taskId,threadId:null,projectId:"test-project",title:"remote",prompt:"hello",status:"pending",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),result:null,error:null,log:"",owned:true,pid:null,pgid:null,processStart:null,commandMarker:null,parentThreadId:null,executionHostId:paired.hostId,workspaceId:made.workspace.id,hostTaskId:taskId});await hub.request(paired.hostId,"provider.task.start",{taskId,provider:"claude",workspaceId:made.workspace.id,prompt:"hello",permissionProfile:":read-only"});let status:any;for(let i=0;i<300;i++){status=await hub.request(paired.hostId,"provider.task.status",{taskId,provider:"claude",workspaceId:made.workspace.id});if(status.status==="completed"||status.status==="failed")break;await new Promise(resolve=>setTimeout(resolve,30));}expect(status.status,JSON.stringify(status)).toBe("completed");expect(status.threadId).toBe("fake-thread");await until(()=>readStreamEvents(base,taskId,0,100).events.some(event=>event.type==="task_completed"),10_000);
      const stopId="claude:remote:stop";await db.upsertTask({id:stopId,provider:"claude",nativeId:stopId,threadId:null,projectId:"test-project",title:"stop",prompt:"wait",status:"pending",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),result:null,error:null,log:"",owned:true,pid:null,pgid:null,processStart:null,commandMarker:null,parentThreadId:null,executionHostId:paired.hostId,workspaceId:made.workspace.id,hostTaskId:stopId});await hub.request(paired.hostId,"provider.task.start",{taskId:stopId,provider:"claude",workspaceId:made.workspace.id,prompt:"wait-for-stop",permissionProfile:":read-only"});for(let i=0;i<100;i++){status=await hub.request(paired.hostId,"provider.task.status",{taskId:stopId,provider:"claude",workspaceId:made.workspace.id});if(status.status==="running")break;await new Promise(resolve=>setTimeout(resolve,20));}expect((await hub.request(paired.hostId,"provider.task.stop",{taskId:stopId,provider:"claude",workspaceId:made.workspace.id}) as any).status).toBe("stopped");
      const compatible=await hub.request(paired.hostId,"provider.task.start",{taskId:"codex:remote:restricted",provider:"codex",workspaceId:made.workspace.id,prompt:"pwd",permissionProfile:":read-only",automationLevel:"read"}) as any;expect(compatible.executionPolicy).toMatchObject({requestedAutomation:"read",executionBackend:"compatibility",transportSandbox:"danger-full-access",allowed:true});for(let i=0;i<150;i++){status=await hub.request(paired.hostId,"provider.task.status",{taskId:"codex:remote:restricted",provider:"codex",workspaceId:made.workspace.id});if(status.status==="completed"||status.status==="failed")break;await new Promise(resolve=>setTimeout(resolve,30));}expect(status.status,JSON.stringify(status)).toBe("completed");
      const codexId="codex:remote:integration";await db.upsertTask({id:codexId,provider:"codex",nativeId:codexId,threadId:null,projectId:"test-project",title:"codex",prompt:"hello",status:"pending",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),result:null,error:null,log:"",owned:true,pid:null,pgid:null,processStart:null,commandMarker:null,parentThreadId:null,executionHostId:paired.hostId,workspaceId:made.workspace.id,hostTaskId:codexId,permissionProfile:":danger-full-access",metadata:{automationLevel:"full"}});await hub.request(paired.hostId,"provider.task.start",{taskId:codexId,provider:"codex",workspaceId:made.workspace.id,prompt:"hello",permissionProfile:":danger-full-access",automationLevel:"full"});for(let i=0;i<150;i++){status=await hub.request(paired.hostId,"provider.task.status",{taskId:codexId,provider:"codex",workspaceId:made.workspace.id});if(status.status==="completed"||status.status==="failed")break;await new Promise(resolve=>setTimeout(resolve,30));}expect(status.status,JSON.stringify(status)).toBe("completed");expect(status.threadId).toBe("fake-codex-thread");await until(()=>readStreamEvents(base,codexId,0,100).events.some(event=>event.type==="task_completed"),5000);const codexEvents=readStreamEvents(base,codexId,0,100).events,answerIndex=codexEvents.findIndex(event=>event.type==="message_completed"&&event.content==="codex remote reply"),terminalIndex=codexEvents.findIndex(event=>event.type==="task_completed");expect(answerIndex).toBeGreaterThanOrEqual(0);expect(terminalIndex).toBeGreaterThan(answerIndex);expect(codexEvents[answerIndex]?.metadata?.recoveredFromCompletedTurn).toBe(true);await hub.request(paired.hostId,"provider.session.resume",{taskId:codexId,provider:"codex",workspaceId:made.workspace.id,prompt:"follow-up",permissionProfile:":danger-full-access",automationLevel:"full"});for(let i=0;i<150;i++){status=await hub.request(paired.hostId,"provider.task.status",{taskId:codexId,provider:"codex",workspaceId:made.workspace.id});if(status.status==="completed")break;await new Promise(resolve=>setTimeout(resolve,30));}expect(status.status).toBe("completed");await hub.request(paired.hostId,"provider.session.fork",{taskId:codexId,provider:"codex",workspaceId:made.workspace.id,permissionProfile:":danger-full-access",automationLevel:"full"});for(let i=0;i<150;i++){status=await hub.request(paired.hostId,"provider.task.status",{taskId:codexId,provider:"codex",workspaceId:made.workspace.id});if(status.status==="completed"&&status.threadId==="fake-codex-fork")break;await new Promise(resolve=>setTimeout(resolve,30));}expect(status.threadId).toBe("fake-codex-fork");
      const oldCredential=await db.getWorkerCredential(paired.hostId),rotation=await hub.request(paired.hostId,"host.credential.rotate",{}) as any;expect(rotation.credentialHash).toMatch(/^[a-f0-9]{64}$/);expect(rotation.credentialHash).not.toBe(oldCredential?.credentialHash);await db.putWorkerCredential({hostId:paired.hostId,credentialHash:rotation.credentialHash,credentialVersion:rotation.credentialVersion,createdAt:new Date().toISOString(),rotatedAt:new Date().toISOString()});hub.reconnectAfterCredentialRotation(paired.hostId);let rotatedCapabilities:any=null;await untilAsync(async()=>{try{rotatedCapabilities=await hub.request(paired.hostId,"host.capabilities.read",{});return rotatedCapabilities?.protocolVersion===1;}catch{return false;}},10_000);expect(rotatedCapabilities.protocolVersion).toBe(1);await untilAsync(async()=>(await db.getHost(paired.hostId))?.status==="online",5_000);const rotatedConfig=loadWorkerConfig();expect(rotatedConfig.credentialVersion).toBe(2);expect(rotatedConfig.previousCredential).toBeNull();expect(rotatedConfig.previousCredentialExpiresAt).toBeNull();
      client.stop();await running;await untilAsync(async()=>(await db.getHost(paired.hostId))?.status==="offline",5_000);await expect(hub.request(paired.hostId,"provider.approvals.list",{taskId:approvalTaskId,provider:"codex",workspaceId:made.workspace.id})).rejects.toMatchObject({code:"HOST_OFFLINE",statusCode:503});
    }finally{client?.stop();hub.shutdown();await app.close();await db.ping();await db.close();}
  },45_000);
});

function gitInit(cwd:string){for(const args of [["init","-b","main"],["config","user.name","Test"],["config","user.email","test@example.invalid"]]){const result=spawnSync("git",args,{cwd,shell:false,encoding:"utf8"});if(result.status!==0)throw new Error(result.stderr);}fs.writeFileSync(path.join(cwd,"changed.txt"),"base\n");for(const args of [["add","changed.txt"],["commit","-m","base"]]){const result=spawnSync("git",args,{cwd,shell:false,encoding:"utf8"});if(result.status!==0)throw new Error(result.stderr);}}
